// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Interop;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api.Security;

/// <summary>
/// CryptoExtensionAbility 绑定（@ohos.security.CryptoExtensionAbility）。
/// </summary>
public static unsafe partial class CryptoExtensionAbility
{
    private const string ModuleName = "@ohos.security.CryptoExtensionAbility";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[security.CryptoExtensionAbility] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _onGetResourceId => "onGetResourceId"u8;
    private static ReadOnlySpan<byte> _onOpenResource => "onOpenResource"u8;
    private static ReadOnlySpan<byte> _onCloseResource => "onCloseResource"u8;
    private static ReadOnlySpan<byte> _onGetProperty => "onGetProperty"u8;
    private static ReadOnlySpan<byte> _onSetProperty => "onSetProperty"u8;
    private static ReadOnlySpan<byte> _onAuthUkeyPin => "onAuthUkeyPin"u8;
    private static ReadOnlySpan<byte> _onGetUkeyPinAuthState => "onGetUkeyPinAuthState"u8;
    private static ReadOnlySpan<byte> _onClearUkeyPinAuthState => "onClearUkeyPinAuthState"u8;
    private static ReadOnlySpan<byte> _onInitSession => "onInitSession"u8;
    private static ReadOnlySpan<byte> _onUpdateSession => "onUpdateSession"u8;
    private static ReadOnlySpan<byte> _onFinishSession => "onFinishSession"u8;
    private static ReadOnlySpan<byte> _onExportCertificate => "onExportCertificate"u8;
    private static ReadOnlySpan<byte> _onImportCertificate => "onImportCertificate"u8;
    private static ReadOnlySpan<byte> _onEnumCertificates => "onEnumCertificates"u8;
    private static ReadOnlySpan<byte> _onGenerateKeyItem => "onGenerateKeyItem"u8;
    private static ReadOnlySpan<byte> _onExportKeyItem => "onExportKeyItem"u8;
    private static ReadOnlySpan<byte> _onImportWrappedKeyItem => "onImportWrappedKeyItem"u8;

    /// <summary>
    /// onGetResourceId
    /// </summary>
    public static IntPtr OnGetResourceId(IntPtr[] @params)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onGetResourceId, NapiArg.Of(@params));
    }

    /// <summary>
    /// onOpenResource
    /// </summary>
    public static IntPtr OnOpenResource(string resourceId, IntPtr[] @params)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onOpenResource, resourceId, NapiArg.Of(@params));
    }

    /// <summary>
    /// onCloseResource
    /// </summary>
    public static IntPtr OnCloseResource(string handle, IntPtr[] @params)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onCloseResource, handle, NapiArg.Of(@params));
    }

    /// <summary>
    /// onGetProperty
    /// </summary>
    public static IntPtr OnGetProperty(string handle, string propertyId, IntPtr[] @params)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onGetProperty, handle, propertyId, NapiArg.Of(@params));
    }

    /// <summary>
    /// onSetProperty
    /// </summary>
    public static IntPtr OnSetProperty(string handle, string propertyId, IntPtr[] @params)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onSetProperty, handle, propertyId, NapiArg.Of(@params));
    }

    /// <summary>
    /// onAuthUkeyPin
    /// </summary>
    public static IntPtr OnAuthUkeyPin(string handle, IntPtr[] @params)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onAuthUkeyPin, handle, NapiArg.Of(@params));
    }

    /// <summary>
    /// onGetUkeyPinAuthState
    /// </summary>
    public static IntPtr OnGetUkeyPinAuthState(string handle, IntPtr[] @params)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onGetUkeyPinAuthState, handle, NapiArg.Of(@params));
    }

    /// <summary>
    /// onClearUkeyPinAuthState
    /// </summary>
    public static IntPtr OnClearUkeyPinAuthState(string handle, IntPtr[] @params)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onClearUkeyPinAuthState, handle, NapiArg.Of(@params));
    }

    /// <summary>
    /// onInitSession
    /// </summary>
    public static IntPtr OnInitSession(string handle, IntPtr @params)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onInitSession, handle, @params);
    }

    /// <summary>
    /// onUpdateSession
    /// </summary>
    public static IntPtr OnUpdateSession(string initHandle, IntPtr @params)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onUpdateSession, initHandle, @params);
    }

    /// <summary>
    /// onFinishSession
    /// </summary>
    public static IntPtr OnFinishSession(string initHandle, IntPtr @params)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onFinishSession, initHandle, @params);
    }

    /// <summary>
    /// onExportCertificate
    /// </summary>
    public static IntPtr OnExportCertificate(string resourceId, IntPtr[]? @params = null)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onExportCertificate, resourceId, NapiArg.Of(@params));
    }

    /// <summary>
    /// onImportCertificate
    /// </summary>
    public static IntPtr OnImportCertificate(string handle, IntPtr[] @params, IntPtr certInfo)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onImportCertificate, handle, NapiArg.Of(@params), certInfo);
    }

    /// <summary>
    /// onEnumCertificates
    /// </summary>
    public static IntPtr OnEnumCertificates(IntPtr[]? @params = null)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onEnumCertificates, NapiArg.Of(@params));
    }

    /// <summary>
    /// onGenerateKeyItem
    /// </summary>
    public static IntPtr OnGenerateKeyItem(string handle, IntPtr[] @params)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onGenerateKeyItem, handle, NapiArg.Of(@params));
    }

    /// <summary>
    /// onExportKeyItem
    /// </summary>
    public static IntPtr OnExportKeyItem(string handle, IntPtr[] @params)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onExportKeyItem, handle, NapiArg.Of(@params));
    }

    /// <summary>
    /// onImportWrappedKeyItem
    /// </summary>
    public static IntPtr OnImportWrappedKeyItem(string handle, string wrappingHandle, IntPtr[] @params, byte[] wrappedKey)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onImportWrappedKeyItem, handle, wrappingHandle, NapiArg.Of(@params), NapiArg.Of(wrappedKey));
    }

}
