// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// ArkLazyWaterFlowLayout 绑定（@ohos.arkui.components.ArkLazyWaterFlowLayout）。
/// </summary>
public static unsafe partial class ArkLazyWaterFlowLayout
{
    private const string ModuleName = "@ohos.arkui.components.ArkLazyWaterFlowLayout";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[arkui.components.ArkLazyWaterFlowLayout] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _rowsGap => "rowsGap"u8;
    private static ReadOnlySpan<byte> _columnsGap => "columnsGap"u8;
    private static ReadOnlySpan<byte> _header => "header"u8;
    private static ReadOnlySpan<byte> _footer => "footer"u8;
    private static ReadOnlySpan<byte> _sticky => "sticky"u8;
    private static ReadOnlySpan<byte> _onVisibleIndexesChange => "onVisibleIndexesChange"u8;
    private static ReadOnlySpan<byte> _columnsTemplate => "columnsTemplate"u8;

    /// <summary>
    /// rowsGap
    /// </summary>
    public static IntPtr RowsGap(IntPtr value)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _rowsGap, value);
    }

    /// <summary>
    /// columnsGap
    /// </summary>
    public static IntPtr ColumnsGap(IntPtr value)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _columnsGap, value);
    }

    /// <summary>
    /// header
    /// </summary>
    public static IntPtr Header(IntPtr builder)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _header, builder);
    }

    /// <summary>
    /// footer
    /// </summary>
    public static IntPtr Footer(IntPtr builder)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _footer, builder);
    }

    /// <summary>
    /// sticky
    /// </summary>
    public static IntPtr Sticky(IntPtr sticky)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _sticky, sticky);
    }

    /// <summary>
    /// onVisibleIndexesChange
    /// </summary>
    public static IntPtr OnVisibleIndexesChange(IntPtr callback)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onVisibleIndexesChange, callback);
    }

    /// <summary>
    /// columnsTemplate
    /// </summary>
    public static IntPtr ColumnsTemplate(string value)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _columnsTemplate, value);
    }

}
