// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Text;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// BatteryInfo 绑定（@ohos.batteryInfo）。
/// </summary>
public static unsafe partial class BatteryInfo
{
    private const string ModuleName = "@ohos.batteryInfo";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    private static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[batteryInfo] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _batterySOC => "batterySOC"u8;
    private static ReadOnlySpan<byte> _chargingStatus => "chargingStatus"u8;
    private static ReadOnlySpan<byte> _healthStatus => "healthStatus"u8;
    private static ReadOnlySpan<byte> _pluggedType => "pluggedType"u8;
    private static ReadOnlySpan<byte> _voltage => "voltage"u8;
    private static ReadOnlySpan<byte> _technology => "technology"u8;
    private static ReadOnlySpan<byte> _batteryTemperature => "batteryTemperature"u8;
    private static ReadOnlySpan<byte> _isBatteryPresent => "isBatteryPresent"u8;
    private static ReadOnlySpan<byte> _batteryCapacityLevel => "batteryCapacityLevel"u8;
    private static ReadOnlySpan<byte> _nowCurrent => "nowCurrent"u8;

    /// <summary>
    /// batterySOC
    /// </summary>
    public static double BatterySOC => NativeValue.ToDouble(NodeApi.GetProperty(Module, _batterySOC));

    /// <summary>
    /// chargingStatus
    /// </summary>
    public static IntPtr ChargingStatus => NodeApi.GetProperty(Module, _chargingStatus);

    /// <summary>
    /// healthStatus
    /// </summary>
    public static IntPtr HealthStatus => NodeApi.GetProperty(Module, _healthStatus);

    /// <summary>
    /// pluggedType
    /// </summary>
    public static IntPtr PluggedType => NodeApi.GetProperty(Module, _pluggedType);

    /// <summary>
    /// voltage
    /// </summary>
    public static double Voltage => NativeValue.ToDouble(NodeApi.GetProperty(Module, _voltage));

    /// <summary>
    /// technology
    /// </summary>
    public static string Technology => NativeValue.ToString(NodeApi.GetProperty(Module, _technology)) ?? string.Empty;

    /// <summary>
    /// batteryTemperature
    /// </summary>
    public static double BatteryTemperature => NativeValue.ToDouble(NodeApi.GetProperty(Module, _batteryTemperature));

    /// <summary>
    /// isBatteryPresent
    /// </summary>
    public static bool IsBatteryPresent => NativeValue.ToBool(NodeApi.GetProperty(Module, _isBatteryPresent));

    /// <summary>
    /// batteryCapacityLevel
    /// </summary>
    public static IntPtr BatteryCapacityLevel => NodeApi.GetProperty(Module, _batteryCapacityLevel);

    /// <summary>
    /// nowCurrent
    /// </summary>
    public static double NowCurrent => NativeValue.ToDouble(NodeApi.GetProperty(Module, _nowCurrent));

}