// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// CacheDownload 绑定（@ohos.request.cacheDownload）。
/// 所需权限：ohos.permission.GET_NETWORK_INFO, ohos.permission.INTERNET
/// </summary>
public static unsafe partial class CacheDownload
{
    private const string ModuleName = "@ohos.request.cacheDownload";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[request.cacheDownload] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _download => "download"u8;
    private static ReadOnlySpan<byte> _cancel => "cancel"u8;
    private static ReadOnlySpan<byte> _setMemoryCacheSize => "setMemoryCacheSize"u8;
    private static ReadOnlySpan<byte> _setFileCacheSize => "setFileCacheSize"u8;
    private static ReadOnlySpan<byte> _getDownloadInfo => "getDownloadInfo"u8;
    private static ReadOnlySpan<byte> _setDownloadInfoListSize => "setDownloadInfoListSize"u8;
    private static ReadOnlySpan<byte> _clearMemoryCache => "clearMemoryCache"u8;
    private static ReadOnlySpan<byte> _clearFileCache => "clearFileCache"u8;
    private static ReadOnlySpan<byte> _onDownloadSuccess => "onDownloadSuccess"u8;
    private static ReadOnlySpan<byte> _onDownloadError => "onDownloadError"u8;
    private static ReadOnlySpan<byte> _offDownloadSuccess => "offDownloadSuccess"u8;
    private static ReadOnlySpan<byte> _offDownloadError => "offDownloadError"u8;
    private static ReadOnlySpan<byte> _setGlobalRetryOptions => "setGlobalRetryOptions"u8;
    private static ReadOnlySpan<byte> _setGlobalTimeoutOptions => "setGlobalTimeoutOptions"u8;

    /// <summary>
    /// download
    /// </summary>
    public static void Download(string url, IntPtr options)
    {
        NodeApi.CallMethodVoid(Module, _download, url, options);
    }

    /// <summary>
    /// cancel
    /// </summary>
    public static void Cancel(string url)
    {
        NodeApi.CallMethodVoid(Module, _cancel, url);
    }

    /// <summary>
    /// setMemoryCacheSize
    /// </summary>
    public static void SetMemoryCacheSize(double bytes)
    {
        NodeApi.CallMethodVoid(Module, _setMemoryCacheSize, bytes);
    }

    /// <summary>
    /// setFileCacheSize
    /// </summary>
    public static void SetFileCacheSize(double bytes)
    {
        NodeApi.CallMethodVoid(Module, _setFileCacheSize, bytes);
    }

    /// <summary>
    /// getDownloadInfo
    /// </summary>
    public static DownloadInfo GetDownloadInfo(string url)
    {
        return NodeApi.CallMethod(Module, _getDownloadInfo, static h => new DownloadInfo(h), url);
    }

    /// <summary>
    /// setDownloadInfoListSize
    /// </summary>
    public static void SetDownloadInfoListSize(double size)
    {
        NodeApi.CallMethodVoid(Module, _setDownloadInfoListSize, size);
    }

    /// <summary>
    /// clearMemoryCache
    /// </summary>
    public static void ClearMemoryCache()
    {
        NodeApi.CallMethodVoid(Module, _clearMemoryCache);
    }

    /// <summary>
    /// clearFileCache
    /// </summary>
    public static void ClearFileCache()
    {
        NodeApi.CallMethodVoid(Module, _clearFileCache);
    }

    /// <summary>
    /// onDownloadSuccess
    /// </summary>
    public static void OnDownloadSuccess(string url, IntPtr callback)
    {
        NodeApi.CallMethodVoid(Module, _onDownloadSuccess, url, callback);
    }

    /// <summary>
    /// onDownloadError
    /// </summary>
    public static void OnDownloadError(string url, IntPtr callback)
    {
        NodeApi.CallMethodVoid(Module, _onDownloadError, url, callback);
    }

    /// <summary>
    /// offDownloadSuccess
    /// </summary>
    public static void OffDownloadSuccess(string url, IntPtr? callback = null)
    {
        NodeApi.CallMethodVoid(Module, _offDownloadSuccess, url, callback);
    }

    /// <summary>
    /// offDownloadError
    /// </summary>
    public static void OffDownloadError(string url, IntPtr? callback = null)
    {
        NodeApi.CallMethodVoid(Module, _offDownloadError, url, callback);
    }

    /// <summary>
    /// setGlobalRetryOptions
    /// </summary>
    public static void SetGlobalRetryOptions(RetryOptions? options = null)
    {
        NodeApi.CallMethodVoid(Module, _setGlobalRetryOptions, options);
    }

    /// <summary>
    /// setGlobalTimeoutOptions
    /// </summary>
    public static void SetGlobalTimeoutOptions(TimeoutOptions? options = null)
    {
        NodeApi.CallMethodVoid(Module, _setGlobalTimeoutOptions, options);
    }

}

/// <summary>
/// DownloadInfo 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class DownloadInfo : JsObject
{
    public DownloadInfo(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _resource => "resource"u8;
    private static ReadOnlySpan<byte> _network => "network"u8;
    private static ReadOnlySpan<byte> _performance => "performance"u8;
    /// <summary>
    /// resource
    /// </summary>
    public ResourceInfo Resource => new ResourceInfo(GetPropertyRaw(_resource));

    /// <summary>
    /// network
    /// </summary>
    public CacheDownloadNetworkInfo Network => new CacheDownloadNetworkInfo(GetPropertyRaw(_network));

    /// <summary>
    /// performance
    /// </summary>
    public PerformanceInfo Performance => new PerformanceInfo(GetPropertyRaw(_performance));

}

/// <summary>
/// RetryOptions（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record RetryOptions(
    double? MaxRetryCount = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _maxRetryCount = System.Text.Encoding.UTF8.GetBytes("maxRetryCount");
        var _maxRetryCountV = NativeValue.From(MaxRetryCount);
        if (_maxRetryCountV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _maxRetryCount, _maxRetryCountV);
    }
}

/// <summary>
/// TimeoutOptions（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record TimeoutOptions(
    double? NetworkCheckTimeout = null,
    double? HttpTotalTimeout = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _networkCheckTimeout = System.Text.Encoding.UTF8.GetBytes("networkCheckTimeout");
        var _networkCheckTimeoutV = NativeValue.From(NetworkCheckTimeout);
        if (_networkCheckTimeoutV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _networkCheckTimeout, _networkCheckTimeoutV);
        var _httpTotalTimeout = System.Text.Encoding.UTF8.GetBytes("httpTotalTimeout");
        var _httpTotalTimeoutV = NativeValue.From(HttpTotalTimeout);
        if (_httpTotalTimeoutV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _httpTotalTimeout, _httpTotalTimeoutV);
    }
}

/// <summary>
/// ResourceInfo 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class ResourceInfo : JsObject
{
    public ResourceInfo(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _size => "size"u8;
    /// <summary>
    /// size
    /// </summary>
    public double Size => NativeValue.ToDouble(GetPropertyRaw(_size));

}

/// <summary>
/// NetworkInfo 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class CacheDownloadNetworkInfo : JsObject
{
    public CacheDownloadNetworkInfo(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _dnsServers => "dnsServers"u8;
    private static ReadOnlySpan<byte> _ip => "ip"u8;
    /// <summary>
    /// dnsServers
    /// </summary>
    public string[] DnsServers => ValueConverter.ConvertArray(GetPropertyRaw(_dnsServers), static e => ValueConverter.Convert<string>(e));

    /// <summary>
    /// ip
    /// </summary>
    public string? IP => (string?)NativeValue.ToString(GetPropertyRaw(_ip)) ?? string.Empty;

}

/// <summary>
/// PerformanceInfo 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class PerformanceInfo : JsObject
{
    public PerformanceInfo(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _dnsTime => "dnsTime"u8;
    private static ReadOnlySpan<byte> _connectTime => "connectTime"u8;
    private static ReadOnlySpan<byte> _tlsTime => "tlsTime"u8;
    private static ReadOnlySpan<byte> _firstSendTime => "firstSendTime"u8;
    private static ReadOnlySpan<byte> _firstReceiveTime => "firstReceiveTime"u8;
    private static ReadOnlySpan<byte> _totalTime => "totalTime"u8;
    private static ReadOnlySpan<byte> _redirectTime => "redirectTime"u8;
    /// <summary>
    /// dnsTime
    /// </summary>
    public double DnsTime => NativeValue.ToDouble(GetPropertyRaw(_dnsTime));

    /// <summary>
    /// connectTime
    /// </summary>
    public double ConnectTime => NativeValue.ToDouble(GetPropertyRaw(_connectTime));

    /// <summary>
    /// tlsTime
    /// </summary>
    public double TlsTime => NativeValue.ToDouble(GetPropertyRaw(_tlsTime));

    /// <summary>
    /// firstSendTime
    /// </summary>
    public double FirstSendTime => NativeValue.ToDouble(GetPropertyRaw(_firstSendTime));

    /// <summary>
    /// firstReceiveTime
    /// </summary>
    public double FirstReceiveTime => NativeValue.ToDouble(GetPropertyRaw(_firstReceiveTime));

    /// <summary>
    /// totalTime
    /// </summary>
    public double TotalTime => NativeValue.ToDouble(GetPropertyRaw(_totalTime));

    /// <summary>
    /// redirectTime
    /// </summary>
    public double RedirectTime => NativeValue.ToDouble(GetPropertyRaw(_redirectTime));

}
