// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// Cdsm 绑定（@ohos.nearlink.cdsm）。
/// 所需权限：ohos.permission.ACCESS_NEARLINK
/// </summary>
public static unsafe partial class Cdsm
{
    private const string ModuleName = "@ohos.nearlink.cdsm";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[nearlink.cdsm] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _createCdsmClient => "createCdsmClient"u8;

    /// <summary>
    /// createCdsmClient
    /// </summary>
    public static CdsmClient CreateCdsmClient(string address)
    {
        return NodeApi.CallMethod(Module, _createCdsmClient, static h => new CdsmClient(h), address);
    }

}

/// <summary>
/// CdsmClient 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class CdsmClient : JsObject
{
    public CdsmClient(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _getCdsmInfo => "getCdsmInfo"u8;
    private static ReadOnlySpan<byte> _onCdsmInfoChange => "onCdsmInfoChange"u8;
    private static ReadOnlySpan<byte> _offCdsmInfoChange => "offCdsmInfoChange"u8;
    /// <summary>
    /// getCdsmInfo
    /// </summary>
    public IntPtr GetCdsmInfo()
    {
        return CallMethod<IntPtr>(_getCdsmInfo);
    }

    /// <summary>
    /// onCdsmInfoChange
    /// </summary>
    public void OnCdsmInfoChange(IntPtr callback)
    {
        CallMethodVoid(_onCdsmInfoChange, callback);
    }

    /// <summary>
    /// offCdsmInfoChange
    /// </summary>
    public void OffCdsmInfoChange(IntPtr? callback = null)
    {
        CallMethodVoid(_offCdsmInfoChange, callback);
    }

}
