using System;

using System.ComponentModel;

namespace HarmonyOS.ArkUI;

/// <summary>
/// Support 枚举
/// </summary>
public enum Support
{
    [Description("usual.event.BOOT_COMPLETED")]
    CommonEventBootCompleted,
    [Description("usual.event.LOCKED_BOOT_COMPLETED")]
    CommonEventLockedBootCompleted,
    [Description("usual.event.SHUTDOWN")]
    CommonEventShutdown,
    [Description("usual.event.BATTERY_CHANGED")]
    CommonEventBatteryChanged,
    [Description("usual.event.BATTERY_LOW")]
    CommonEventBatteryLow,
    [Description("usual.event.BATTERY_OKAY")]
    CommonEventBatteryOkay,
    [Description("usual.event.POWER_CONNECTED")]
    CommonEventPowerConnected,
    [Description("usual.event.POWER_DISCONNECTED")]
    CommonEventPowerDisconnected,
    [Description("usual.event.SCREEN_OFF")]
    CommonEventScreenOff,
    [Description("usual.event.SCREEN_ON")]
    CommonEventScreenOn,
    [Description("usual.event.THERMAL_LEVEL_CHANGED")]
    CommonEventThermalLevelChanged,
    [Description("usual.event.ENTER_FORCE_SLEEP")]
    CommonEventEnterForceSleep,
    [Description("usual.event.EXIT_FORCE_SLEEP")]
    CommonEventExitForceSleep,
    [Description("usual.event.ENTER_HIBERNATE")]
    CommonEventEnterHibernate,
    [Description("usual.event.EXIT_HIBERNATE")]
    CommonEventExitHibernate,
    [Description("usual.event.USER_PRESENT")]
    CommonEventUserPresent,
    [Description("usual.event.TIME_TICK")]
    CommonEventTimeTick,
    [Description("usual.event.TIME_CHANGED")]
    CommonEventTimeChanged,
    [Description("usual.event.DATE_CHANGED")]
    CommonEventDateChanged,
    [Description("usual.event.TIMEZONE_CHANGED")]
    CommonEventTimezoneChanged,
    [Description("usual.event.CLOSE_SYSTEM_DIALOGS")]
    CommonEventCloseSystemDialogs,
    [Description("usual.event.PACKAGE_ADDED")]
    CommonEventPackageAdded,
    [Description("usual.event.PACKAGE_REPLACED")]
    CommonEventPackageReplaced,
    [Description("usual.event.MY_PACKAGE_REPLACED")]
    CommonEventMyPackageReplaced,
    [Description("usual.event.PACKAGE_REMOVED")]
    CommonEventPackageRemoved,
    [Description("usual.event.BUNDLE_REMOVED")]
    CommonEventBundleRemoved,
    [Description("usual.event.PACKAGE_FULLY_REMOVED")]
    CommonEventPackageFullyRemoved,
    [Description("usual.event.PACKAGE_CHANGED")]
    CommonEventPackageChanged,
    [Description("usual.event.PACKAGE_RESTARTED")]
    CommonEventPackageRestarted,
    [Description("usual.event.PACKAGE_DATA_CLEARED")]
    CommonEventPackageDataCleared,
    [Description("usual.event.PACKAGE_CACHE_CLEARED")]
    CommonEventPackageCacheCleared,
    [Description("usual.event.PACKAGES_SUSPENDED")]
    CommonEventPackagesSuspended,
    [Description("usual.event.PACKAGES_UNSUSPENDED")]
    CommonEventPackagesUnsuspended,
    [Description("usual.event.MY_PACKAGE_SUSPENDED")]
    CommonEventMyPackageSuspended,
    [Description("usual.event.MY_PACKAGE_UNSUSPENDED")]
    CommonEventMyPackageUnsuspended,
    [Description("usual.event.UID_REMOVED")]
    CommonEventUidRemoved,
    [Description("usual.event.PACKAGE_FIRST_LAUNCH")]
    CommonEventPackageFirstLaunch,
    [Description("usual.event.PACKAGE_NEEDS_VERIFICATION")]
    CommonEventPackageNeedsVerification,
    [Description("usual.event.PACKAGE_VERIFIED")]
    CommonEventPackageVerified,
    [Description("usual.event.EXTERNAL_APPLICATIONS_AVAILABLE")]
    CommonEventExternalApplicationsAvailable,
    [Description("usual.event.EXTERNAL_APPLICATIONS_UNAVAILABLE")]
    CommonEventExternalApplicationsUnavailable,
    [Description("usual.event.CONFIGURATION_CHANGED")]
    CommonEventConfigurationChanged,
    [Description("usual.event.LOCALE_CHANGED")]
    CommonEventLocaleChanged,
    [Description("usual.event.MANAGE_PACKAGE_STORAGE")]
    CommonEventManagePackageStorage,
    [Description("common.event.DRIVE_MODE")]
    CommonEventDriveMode,
    [Description("common.event.HOME_MODE")]
    CommonEventHomeMode,
    [Description("common.event.OFFICE_MODE")]
    CommonEventOfficeMode,
    [Description("usual.event.USER_STARTED")]
    CommonEventUserStarted,
    [Description("usual.event.USER_BACKGROUND")]
    CommonEventUserBackground,
    [Description("usual.event.USER_FOREGROUND")]
    CommonEventUserForeground,
    [Description("usual.event.USER_SWITCHED")]
    CommonEventUserSwitched,
    [Description("usual.event.USER_STARTING")]
    CommonEventUserStarting,
    [Description("usual.event.USER_UNLOCKED")]
    CommonEventUserUnlocked,
    [Description("usual.event.USER_STOPPING")]
    CommonEventUserStopping,
    [Description("usual.event.USER_STOPPED")]
    CommonEventUserStopped,
    [Description("common.event.DISTRIBUTED_ACCOUNT_LOGIN")]
    CommonEventDistributedAccountLogin,
    [Description("common.event.DISTRIBUTED_ACCOUNT_LOGOUT")]
    CommonEventDistributedAccountLogout,
    [Description("common.event.DISTRIBUTED_ACCOUNT_TOKEN_INVALID")]
    CommonEventDistributedAccountTokenInvalid,
    [Description("common.event.DISTRIBUTED_ACCOUNT_LOGOFF")]
    CommonEventDistributedAccountLogoff,
    [Description("usual.event.wifi.POWER_STATE")]
    CommonEventWifiPowerState,
    [Description("usual.event.wifi.SCAN_FINISHED")]
    CommonEventWifiScanFinished,
    [Description("usual.event.wifi.RSSI_VALUE")]
    CommonEventWifiRssiValue,
    [Description("usual.event.wifi.CONN_STATE")]
    CommonEventWifiConnState,
    [Description("usual.event.wifi.HOTSPOT_STATE")]
    CommonEventWifiHotspotState,
    [Description("usual.event.wifi.WIFI_HS_STA_JOIN")]
    CommonEventWifiApStaJoin,
    [Description("usual.event.wifi.WIFI_HS_STA_LEAVE")]
    CommonEventWifiApStaLeave,
    [Description("usual.event.wifi.mplink.STATE_CHANGE")]
    CommonEventWifiMplinkStateChange,
    [Description("usual.event.wifi.p2p.CONN_STATE_CHANGE")]
    CommonEventWifiP2PConnState,
    [Description("usual.event.wifi.p2p.STATE_CHANGE")]
    CommonEventWifiP2PStateChanged,
    [Description("usual.event.wifi.p2p.DEVICES_CHANGE")]
    CommonEventWifiP2PPeersStateChanged,
    [Description("usual.event.wifi.p2p.PEER_DISCOVERY_STATE_CHANGE")]
    CommonEventWifiP2PPeersDiscoveryStateChanged,
    [Description("usual.event.wifi.p2p.CURRENT_DEVICE_CHANGE")]
    CommonEventWifiP2PCurrentDeviceStateChanged,
    [Description("usual.event.wifi.p2p.GROUP_STATE_CHANGED")]
    CommonEventWifiP2PGroupStateChanged,
    [Description("usual.event.bluetooth.handsfree.ag.CONNECT_STATE_UPDATE")]
    CommonEventBluetoothHandsfreeAgConnectStateUpdate,
    [Description("usual.event.bluetooth.handsfree.ag.CURRENT_DEVICE_UPDATE")]
    CommonEventBluetoothHandsfreeAgCurrentDeviceUpdate,
    [Description("usual.event.bluetooth.handsfree.ag.AUDIO_STATE_UPDATE")]
    CommonEventBluetoothHandsfreeAgAudioStateUpdate,
    [Description("usual.event.bluetooth.a2dpsource.CONNECT_STATE_UPDATE")]
    CommonEventBluetoothA2DpsourceConnectStateUpdate,
    [Description("usual.event.bluetooth.a2dpsource.CURRENT_DEVICE_UPDATE")]
    CommonEventBluetoothA2DpsourceCurrentDeviceUpdate,
    [Description("usual.event.bluetooth.a2dpsource.PLAYING_STATE_UPDATE")]
    CommonEventBluetoothA2DpsourcePlayingStateUpdate,
    [Description("usual.event.bluetooth.a2dpsource.AVRCP_CONNECT_STATE_UPDATE")]
    CommonEventBluetoothA2DpsourceAvrcpConnectStateUpdate,
    [Description("usual.event.bluetooth.a2dpsource.CODEC_VALUE_UPDATE")]
    CommonEventBluetoothA2DpsourceCodecValueUpdate,
    [Description("usual.event.bluetooth.remotedevice.DISCOVERED")]
    CommonEventBluetoothRemotedeviceDiscovered,
    [Description("usual.event.bluetooth.remotedevice.CLASS_VALUE_UPDATE")]
    CommonEventBluetoothRemotedeviceClassValueUpdate,
    [Description("usual.event.bluetooth.remotedevice.ACL_CONNECTED")]
    CommonEventBluetoothRemotedeviceAclConnected,
    [Description("usual.event.bluetooth.remotedevice.ACL_DISCONNECTED")]
    CommonEventBluetoothRemotedeviceAclDisconnected,
    [Description("usual.event.bluetooth.remotedevice.NAME_UPDATE")]
    CommonEventBluetoothRemotedeviceNameUpdate,
    [Description("usual.event.bluetooth.remotedevice.PAIR_STATE")]
    CommonEventBluetoothRemotedevicePairState,
    [Description("usual.event.bluetooth.remotedevice.BATTERY_VALUE_UPDATE")]
    CommonEventBluetoothRemotedeviceBatteryValueUpdate,
    [Description("usual.event.bluetooth.remotedevice.SDP_RESULT")]
    CommonEventBluetoothRemotedeviceSdpResult,
    [Description("usual.event.bluetooth.remotedevice.UUID_VALUE")]
    CommonEventBluetoothRemotedeviceUuidValue,
    [Description("usual.event.bluetooth.remotedevice.PAIRING_REQ")]
    CommonEventBluetoothRemotedevicePairingReq,
    [Description("usual.event.bluetooth.remotedevice.PAIRING_CANCEL")]
    CommonEventBluetoothRemotedevicePairingCancel,
    [Description("usual.event.bluetooth.remotedevice.CONNECT_REQ")]
    CommonEventBluetoothRemotedeviceConnectReq,
    [Description("usual.event.bluetooth.remotedevice.CONNECT_REPLY")]
    CommonEventBluetoothRemotedeviceConnectReply,
    [Description("usual.event.bluetooth.remotedevice.CONNECT_CANCEL")]
    CommonEventBluetoothRemotedeviceConnectCancel,
    [Description("usual.event.bluetooth.handsfreeunit.CONNECT_STATE_UPDATE")]
    CommonEventBluetoothHandsfreeunitConnectStateUpdate,
    [Description("usual.event.bluetooth.handsfreeunit.AUDIO_STATE_UPDATE")]
    CommonEventBluetoothHandsfreeunitAudioStateUpdate,
    [Description("usual.event.bluetooth.handsfreeunit.AG_COMMON_EVENT")]
    CommonEventBluetoothHandsfreeunitAgCommonEvent,
    [Description("usual.event.bluetooth.handsfreeunit.AG_CALL_STATE_UPDATE")]
    CommonEventBluetoothHandsfreeunitAgCallStateUpdate,
    [Description("usual.event.bluetooth.host.STATE_UPDATE")]
    CommonEventBluetoothHostStateUpdate,
    [Description("usual.event.bluetooth.host.REQ_DISCOVERABLE")]
    CommonEventBluetoothHostReqDiscoverable,
    [Description("usual.event.bluetooth.host.REQ_ENABLE")]
    CommonEventBluetoothHostReqEnable,
    [Description("usual.event.bluetooth.host.REQ_DISABLE")]
    CommonEventBluetoothHostReqDisable,
    [Description("usual.event.bluetooth.host.SCAN_MODE_UPDATE")]
    CommonEventBluetoothHostScanModeUpdate,
    [Description("usual.event.bluetooth.host.SCAN_MODE_CHANGE")]
    CommonEventBluetoothHostScanModeChange,
    [Description("usual.event.bluetooth.host.DISCOVERY_STARTED")]
    CommonEventBluetoothHostDiscoveryStarted,
    [Description("usual.event.bluetooth.host.DISCOVERY_FINISHED")]
    CommonEventBluetoothHostDiscoveryFinished,
    [Description("usual.event.bluetooth.host.NAME_UPDATE")]
    CommonEventBluetoothHostNameUpdate,
    [Description("usual.event.bluetooth.a2dpsink.CONNECT_STATE_UPDATE")]
    CommonEventBluetoothA2DpsinkConnectStateUpdate,
    [Description("usual.event.bluetooth.a2dpsink.PLAYING_STATE_UPDATE")]
    CommonEventBluetoothA2DpsinkPlayingStateUpdate,
    [Description("usual.event.bluetooth.a2dpsink.AUDIO_STATE_UPDATE")]
    CommonEventBluetoothA2DpsinkAudioStateUpdate,
    [Description("usual.event.nfc.action.ADAPTER_STATE_CHANGED")]
    CommonEventNfcActionAdapterStateChanged,
    [Description("usual.event.nfc.action.RF_FIELD_ON_DETECTED")]
    CommonEventNfcActionRfFieldOnDetected,
    [Description("usual.event.nfc.action.RF_FIELD_OFF_DETECTED")]
    CommonEventNfcActionRfFieldOffDetected,
    [Description("usual.event.DISCHARGING")]
    CommonEventDischarging,
    [Description("usual.event.CHARGING")]
    CommonEventCharging,
    [Description("usual.event.DEVICE_IDLE_MODE_CHANGED")]
    CommonEventDeviceIdleModeChanged,
    [Description("usual.event.CHARGE_IDLE_MODE_CHANGED")]
    CommonEventChargeIdleModeChanged,
    [Description("usual.event.POWER_SAVE_MODE_CHANGED")]
    CommonEventPowerSaveModeChanged,
    [Description("usual.event.USER_ADDED")]
    CommonEventUserAdded,
    [Description("usual.event.USER_REMOVED")]
    CommonEventUserRemoved,
    [Description("common.event.ABILITY_ADDED")]
    CommonEventAbilityAdded,
    [Description("common.event.ABILITY_REMOVED")]
    CommonEventAbilityRemoved,
    [Description("common.event.ABILITY_UPDATED")]
    CommonEventAbilityUpdated,
    [Description("usual.event.location.MODE_STATE_CHANGED")]
    CommonEventLocationModeStateChanged,
    [Description("common.event.IVI_SLEEP")]
    CommonEventIviSleep,
    [Description("common.event.IVI_PAUSE")]
    CommonEventIviPause,
    [Description("common.event.IVI_STANDBY")]
    CommonEventIviStandby,
    [Description("common.event.IVI_LASTMODE_SAVE")]
    CommonEventIviLastmodeSave,
    [Description("common.event.IVI_VOLTAGE_ABNORMAL")]
    CommonEventIviVoltageAbnormal,
    [Description("common.event.IVI_HIGH_TEMPERATURE")]
    CommonEventIviHighTemperature,
    [Description("common.event.IVI_EXTREME_TEMPERATURE")]
    CommonEventIviExtremeTemperature,
    [Description("common.event.IVI_TEMPERATURE_ABNORMAL")]
    CommonEventIviTemperatureAbnormal,
    [Description("common.event.IVI_VOLTAGE_RECOVERY")]
    CommonEventIviVoltageRecovery,
    [Description("common.event.IVI_TEMPERATURE_RECOVERY")]
    CommonEventIviTemperatureRecovery,
    [Description("common.event.IVI_ACTIVE")]
    CommonEventIviActive,
    [Description("usual.event.hardware.usb.action.USB_STATE")]
    CommonEventUsbState,
    [Description("usual.event.hardware.usb.action.USB_PORT_CHANGED")]
    CommonEventUsbPortChanged,
    [Description("usual.event.hardware.usb.action.USB_DEVICE_ATTACHED")]
    CommonEventUsbDeviceAttached,
    [Description("usual.event.hardware.usb.action.USB_DEVICE_DETACHED")]
    CommonEventUsbDeviceDetached,
    [Description("usual.event.hardware.usb.action.USB_ACCESSORY_ATTACHED")]
    CommonEventUsbAccessoryAttached,
    [Description("usual.event.hardware.usb.action.USB_ACCESSORY_DETACHED")]
    CommonEventUsbAccessoryDetached,
    [Description("usual.event.data.DISK_REMOVED")]
    CommonEventDiskRemoved,
    [Description("usual.event.data.DISK_UNMOUNTED")]
    CommonEventDiskUnmounted,
    [Description("usual.event.data.DISK_MOUNTED")]
    CommonEventDiskMounted,
    [Description("usual.event.data.DISK_BAD_REMOVAL")]
    CommonEventDiskBadRemoval,
    [Description("usual.event.data.DISK_UNMOUNTABLE")]
    CommonEventDiskUnmountable,
    [Description("usual.event.data.DISK_EJECT")]
    CommonEventDiskEject,
    [Description("usual.event.data.VOLUME_REMOVED")]
    CommonEventVolumeRemoved,
    [Description("usual.event.data.VOLUME_UNMOUNTED")]
    CommonEventVolumeUnmounted,
    [Description("usual.event.data.VOLUME_MOUNTED")]
    CommonEventVolumeMounted,
    [Description("usual.event.data.VOLUME_BAD_REMOVAL")]
    CommonEventVolumeBadRemoval,
    [Description("usual.event.data.VOLUME_EJECT")]
    CommonEventVolumeEject,
    [Description("usual.event.data.VISIBLE_ACCOUNTS_UPDATED")]
    CommonEventVisibleAccountsUpdated,
    [Description("usual.event.data.ACCOUNT_DELETED")]
    CommonEventAccountDeleted,
    [Description("common.event.FOUNDATION_READY")]
    CommonEventFoundationReady,
    [Description("usual.event.AIRPLANE_MODE")]
    CommonEventAirplaneModeChanged,
    [Description("common.event.SPLIT_SCREEN")]
    CommonEventSplitScreen,
    [Description("usual.event.SLOT_CHANGE")]
    CommonEventSlotChange,
    [Description("usual.event.SPN_INFO_CHANGED")]
    CommonEventSpnInfoChanged,
    [Description("usual.event.QUICK_FIX_APPLY_RESULT")]
    CommonEventQuickFixApplyResult,
    [Description("usual.event.QUICK_FIX_REVOKE_RESULT")]
    CommonEventQuickFixRevokeResult,
    [Description("usual.event.USER_INFO_UPDATED")]
    CommonEventUserInfoUpdated,
    [Description("usual.event.HTTP_PROXY_CHANGE")]
    CommonEventHttpProxyChange,
    [Description("usual.event.SIM_STATE_CHANGED")]
    CommonEventSimStateChanged,
    [Description("usual.event.CALL_STATE_CHANGED")]
    CommonEventCallStateChanged,
    [Description("usual.event.NETWORK_STATE_CHANGED")]
    CommonEventNetworkStateChanged,
    [Description("usual.event.SIGNAL_INFO_CHANGED")]
    CommonEventSignalInfoChanged,
    [Description("usual.event.SCREEN_UNLOCKED")]
    CommonEventScreenUnlocked,
    [Description("usual.event.SCREEN_LOCKED")]
    CommonEventScreenLocked,
    [Description("usual.event.CONNECTIVITY_CHANGE")]
    CommonEventConnectivityChange,
    [Description("usual.event.bluetooth.handsfree.ag.CONNECT_STATE_CHANGE")]
    CommonEventBluetoothHandsfreeAgConnectStateChange,
    [Description("usual.event.MINORSMODE_ON")]
    CommonEventMinorsmodeOn,
    [Description("usual.event.MINORSMODE_OFF")]
    CommonEventMinorsmodeOff,
    [Description("usual.event.DATA_SHARE_READY")]
    CommonEventDataShareReady,
    [Description("usual.event.bluetooth.a2dpsource.CONNECT_STATE_CHANGE")]
    CommonEventBluetoothA2DpsourceConnectStateChange,
    [Description("usual.event.bluetooth.a2dpsource.AVRCP_CONNECT_STATE_CHANGE")]
    CommonEventBluetoothA2DpsourceAvrcpConnectStateChange,
    [Description("usual.event.bluetooth.a2dpsource.CODEC_VALUE_CHANGE")]
    CommonEventBluetoothA2DpsourceCodecValueChange,
    [Description("usual.event.bluetooth.a2dpsource.PLAY_STATE_CHANGE")]
    CommonEventBluetoothA2DpsourcePlayStateChange,
    [Description("usual.event.bluetooth.SCO_CONNECT_STATE_CHANGE")]
    CommonEventBluetoothScoConnectStateChange,
    [Description("usual.event.bluetooth.remotedevice.ACL_STATE_CHANGE")]
    CommonEventBluetoothRemotedeviceAclStateChange,
    [Description("usual.event.bluetooth.remotedevice.PAIR_STATE_CHANGE")]
    CommonEventBluetoothRemotedevicePairStateChange,
    [Description("usual.event.MANAGED_BROWSER_POLICY_CHANGED")]
    CommonEventManagedBrowserPolicyChanged,
    [Description("usual.event.KIOSK_MODE_ON")]
    CommonEventKioskModeOn,
    [Description("usual.event.KIOSK_MODE_OFF")]
    CommonEventKioskModeOff,
    [Description("usual.event.TABLET_MODE_CHANGED")]
    CommonEventTabletModeChanged,
    [Description("usual.event.VOLUME_DECRYPTED")]
    CommonEventVolumeDecrypted,
    [Description("usual.event.VOLUME_ENCRYPTED")]
    CommonEventVolumeEncrypted,
    [Description("usual.event.VOLUME_ENCRYPTION_POLICY_SET")]
    CommonEventVolumeEncryptionPolicySet,
    [Description("usual.event.SKILL_CHANGED")]
    CommonEventSkillChanged,
    [Description("usual.event.LID_STATE_CHANGED")]
    CommonEventLidStateChanged
}