// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Text;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;
using System.Threading.Tasks;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// Display 绑定（@ohos.display）。
/// 所需权限：ohos.permission.ACCESS_VIRTUAL_SCREEN
/// </summary>
public static unsafe partial class Display
{
    private const string ModuleName = "@ohos.display";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    private static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[display] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _getDefaultDisplay => "getDefaultDisplay"u8;
    private static ReadOnlySpan<byte> _getDefaultDisplaySync => "getDefaultDisplaySync"u8;
    private static ReadOnlySpan<byte> _getPrimaryDisplaySync => "getPrimaryDisplaySync"u8;
    private static ReadOnlySpan<byte> _getDisplayByIdSync => "getDisplayByIdSync"u8;
    private static ReadOnlySpan<byte> _getAllDisplay => "getAllDisplay"u8;
    private static ReadOnlySpan<byte> _getAllDisplays => "getAllDisplays"u8;
    private static ReadOnlySpan<byte> _getAllDisplayPhysicalResolution => "getAllDisplayPhysicalResolution"u8;
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    private static ReadOnlySpan<byte> _isFoldable => "isFoldable"u8;
    private static ReadOnlySpan<byte> _getFoldStatus => "getFoldStatus"u8;
    private static ReadOnlySpan<byte> _isCaptured => "isCaptured"u8;
    private static ReadOnlySpan<byte> _getFoldDisplayMode => "getFoldDisplayMode"u8;
    private static ReadOnlySpan<byte> _getCurrentFoldCreaseRegion => "getCurrentFoldCreaseRegion"u8;
    private static ReadOnlySpan<byte> _createVirtualScreen => "createVirtualScreen"u8;
    private static ReadOnlySpan<byte> _destroyVirtualScreen => "destroyVirtualScreen"u8;
    private static ReadOnlySpan<byte> _setVirtualScreenSurface => "setVirtualScreenSurface"u8;
    private static ReadOnlySpan<byte> _makeUnique => "makeUnique"u8;
    private static ReadOnlySpan<byte> _convertRelativeToGlobalCoordinate => "convertRelativeToGlobalCoordinate"u8;
    private static ReadOnlySpan<byte> _convertGlobalToRelativeCoordinate => "convertGlobalToRelativeCoordinate"u8;
    private static ReadOnlySpan<byte> _getBrightnessInfo => "getBrightnessInfo"u8;

    /// <summary>
    /// getDefaultDisplay 方法
    /// </summary>
    public static Task<IntPtr> GetDefaultDisplay()
    {
        return NodeApi.CallMethodAsync<IntPtr>(Module, _getDefaultDisplay);
    }

    /// <summary>
    /// getDefaultDisplaySync 方法
    /// </summary>
    public static IntPtr GetDefaultDisplaySync()
    {
        return NodeApi.CallMethod<IntPtr>(Module, _getDefaultDisplaySync);
    }

    /// <summary>
    /// getPrimaryDisplaySync 方法
    /// </summary>
    public static IntPtr GetPrimaryDisplaySync()
    {
        return NodeApi.CallMethod<IntPtr>(Module, _getPrimaryDisplaySync);
    }

    /// <summary>
    /// getDisplayByIdSync 方法
    /// </summary>
    public static IntPtr GetDisplayByIdSync(double displayId)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _getDisplayByIdSync, displayId);
    }

    /// <summary>
    /// getAllDisplay 方法
    /// </summary>
    public static Task<IntPtr[]> GetAllDisplay()
    {
        return NodeApi.CallMethodAsync<IntPtr[]>(Module, _getAllDisplay);
    }

    /// <summary>
    /// getAllDisplays 方法
    /// </summary>
    public static Task<IntPtr[]> GetAllDisplays()
    {
        return NodeApi.CallMethodAsync<IntPtr[]>(Module, _getAllDisplays);
    }

    /// <summary>
    /// getAllDisplayPhysicalResolution 方法
    /// </summary>
    public static IntPtr GetAllDisplayPhysicalResolution()
    {
        return NodeApi.CallMethod<IntPtr>(Module, _getAllDisplayPhysicalResolution);
    }

    /// <summary>
    /// on 方法
    /// </summary>
    public static void On(string type, IntPtr callback)
    {
        NodeApi.CallMethodVoid(Module, _on, type, callback);
    }

    /// <summary>
    /// off 方法
    /// </summary>
    public static void Off(string type, IntPtr callback)
    {
        NodeApi.CallMethodVoid(Module, _off, type, callback);
    }

    /// <summary>
    /// isFoldable 方法
    /// </summary>
    public static bool IsFoldable()
    {
        return NodeApi.CallMethod<bool>(Module, _isFoldable);
    }

    /// <summary>
    /// getFoldStatus 方法
    /// </summary>
    public static IntPtr GetFoldStatus()
    {
        return NodeApi.CallMethod<IntPtr>(Module, _getFoldStatus);
    }

    /// <summary>
    /// isCaptured 方法
    /// </summary>
    public static bool IsCaptured()
    {
        return NodeApi.CallMethod<bool>(Module, _isCaptured);
    }

    /// <summary>
    /// isCaptured 方法
    /// </summary>
    public static bool IsCaptured(string[] bundleNameList)
    {
        return NodeApi.CallMethod<bool>(Module, _isCaptured, bundleNameList);
    }

    /// <summary>
    /// getFoldDisplayMode 方法
    /// </summary>
    public static IntPtr GetFoldDisplayMode()
    {
        return NodeApi.CallMethod<IntPtr>(Module, _getFoldDisplayMode);
    }

    /// <summary>
    /// getCurrentFoldCreaseRegion 方法
    /// </summary>
    public static IntPtr GetCurrentFoldCreaseRegion()
    {
        return NodeApi.CallMethod<IntPtr>(Module, _getCurrentFoldCreaseRegion);
    }

    /// <summary>
    /// createVirtualScreen 方法
    /// </summary>
    public static Task<double> CreateVirtualScreen(IntPtr config)
    {
        return NodeApi.CallMethodAsync<double>(Module, _createVirtualScreen, config);
    }

    /// <summary>
    /// destroyVirtualScreen 方法
    /// </summary>
    public static Task DestroyVirtualScreen(double screenId)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _destroyVirtualScreen, screenId);
    }

    /// <summary>
    /// setVirtualScreenSurface 方法
    /// </summary>
    public static Task SetVirtualScreenSurface(double screenId, string surfaceId)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _setVirtualScreenSurface, screenId, surfaceId);
    }

    /// <summary>
    /// makeUnique 方法
    /// </summary>
    public static Task MakeUnique(double screenId)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _makeUnique, screenId);
    }

    /// <summary>
    /// convertRelativeToGlobalCoordinate 方法
    /// </summary>
    public static IntPtr ConvertRelativeToGlobalCoordinate(IntPtr relativePosition)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _convertRelativeToGlobalCoordinate, relativePosition);
    }

    /// <summary>
    /// convertGlobalToRelativeCoordinate 方法
    /// </summary>
    public static IntPtr ConvertGlobalToRelativeCoordinate(IntPtr position, double displayId)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _convertGlobalToRelativeCoordinate, position, displayId);
    }

    /// <summary>
    /// getBrightnessInfo 方法
    /// </summary>
    public static IntPtr GetBrightnessInfo(double displayId)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _getBrightnessInfo, displayId);
    }

}