// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// EnterpriseBluetoothManager 绑定（@ohos.enterprise.bluetoothManager）。
/// 所需权限：ohos.permission.ENTERPRISE_MANAGE_BLUETOOTH
/// </summary>
public static unsafe partial class EnterpriseBluetoothManager
{
    private const string ModuleName = "@ohos.enterprise.bluetoothManager";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[enterprise.bluetoothManager] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _getBluetoothInfo => "getBluetoothInfo"u8;
    private static ReadOnlySpan<byte> _addAllowedBluetoothDevices => "addAllowedBluetoothDevices"u8;
    private static ReadOnlySpan<byte> _removeAllowedBluetoothDevices => "removeAllowedBluetoothDevices"u8;
    private static ReadOnlySpan<byte> _getAllowedBluetoothDevices => "getAllowedBluetoothDevices"u8;
    private static ReadOnlySpan<byte> _turnOnBluetooth => "turnOnBluetooth"u8;
    private static ReadOnlySpan<byte> _turnOffBluetooth => "turnOffBluetooth"u8;
    private static ReadOnlySpan<byte> _addDisallowedBluetoothDevices => "addDisallowedBluetoothDevices"u8;
    private static ReadOnlySpan<byte> _removeDisallowedBluetoothDevices => "removeDisallowedBluetoothDevices"u8;
    private static ReadOnlySpan<byte> _getDisallowedBluetoothDevices => "getDisallowedBluetoothDevices"u8;
    private static ReadOnlySpan<byte> _addDisallowedBluetoothProtocols => "addDisallowedBluetoothProtocols"u8;
    private static ReadOnlySpan<byte> _removeDisallowedBluetoothProtocols => "removeDisallowedBluetoothProtocols"u8;
    private static ReadOnlySpan<byte> _getDisallowedBluetoothProtocols => "getDisallowedBluetoothProtocols"u8;

    /// <summary>
    /// getBluetoothInfo
    /// </summary>
    public static IntPtr GetBluetoothInfo(IntPtr admin)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _getBluetoothInfo, admin);
    }

    /// <summary>
    /// addAllowedBluetoothDevices
    /// </summary>
    public static void AddAllowedBluetoothDevices(IntPtr admin, string[] deviceIds)
    {
        NodeApi.CallMethodVoid(Module, _addAllowedBluetoothDevices, admin, deviceIds);
    }

    /// <summary>
    /// removeAllowedBluetoothDevices
    /// </summary>
    public static void RemoveAllowedBluetoothDevices(IntPtr admin, string[] deviceIds)
    {
        NodeApi.CallMethodVoid(Module, _removeAllowedBluetoothDevices, admin, deviceIds);
    }

    /// <summary>
    /// getAllowedBluetoothDevices
    /// </summary>
    public static string[] GetAllowedBluetoothDevices(IntPtr admin)
    {
        return NodeApi.CallMethod(Module, _getAllowedBluetoothDevices, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<string>(e)), admin);
    }

    /// <summary>
    /// turnOnBluetooth
    /// </summary>
    public static void TurnOnBluetooth(IntPtr admin)
    {
        NodeApi.CallMethodVoid(Module, _turnOnBluetooth, admin);
    }

    /// <summary>
    /// turnOffBluetooth
    /// </summary>
    public static void TurnOffBluetooth(IntPtr admin)
    {
        NodeApi.CallMethodVoid(Module, _turnOffBluetooth, admin);
    }

    /// <summary>
    /// addDisallowedBluetoothDevices
    /// </summary>
    public static void AddDisallowedBluetoothDevices(IntPtr admin, string[] deviceIds)
    {
        NodeApi.CallMethodVoid(Module, _addDisallowedBluetoothDevices, admin, deviceIds);
    }

    /// <summary>
    /// removeDisallowedBluetoothDevices
    /// </summary>
    public static void RemoveDisallowedBluetoothDevices(IntPtr admin, string[] deviceIds)
    {
        NodeApi.CallMethodVoid(Module, _removeDisallowedBluetoothDevices, admin, deviceIds);
    }

    /// <summary>
    /// getDisallowedBluetoothDevices
    /// </summary>
    public static string[] GetDisallowedBluetoothDevices(IntPtr admin)
    {
        return NodeApi.CallMethod(Module, _getDisallowedBluetoothDevices, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<string>(e)), admin);
    }

    /// <summary>
    /// addDisallowedBluetoothProtocols
    /// </summary>
    public static void AddDisallowedBluetoothProtocols(IntPtr admin, double accountId, global::HarmonyOS.ArkUI.Protocol[] protocols)
    {
        NodeApi.CallMethodVoid(Module, _addDisallowedBluetoothProtocols, admin, accountId, protocols);
    }

    /// <summary>
    /// removeDisallowedBluetoothProtocols
    /// </summary>
    public static void RemoveDisallowedBluetoothProtocols(IntPtr admin, double accountId, global::HarmonyOS.ArkUI.Protocol[] protocols)
    {
        NodeApi.CallMethodVoid(Module, _removeDisallowedBluetoothProtocols, admin, accountId, protocols);
    }

    /// <summary>
    /// getDisallowedBluetoothProtocols
    /// </summary>
    public static global::HarmonyOS.ArkUI.Protocol[] GetDisallowedBluetoothProtocols(IntPtr admin, double accountId)
    {
        return NodeApi.CallMethod(Module, _getDisallowedBluetoothProtocols, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<global::HarmonyOS.ArkUI.Protocol>(e)), admin, accountId);
    }

    /// <summary>
    /// addDisallowedBluetoothProtocols
    /// </summary>
    public static void AddDisallowedBluetoothProtocols(IntPtr admin, double accountId, global::HarmonyOS.ArkUI.Protocol[] protocols, global::HarmonyOS.ArkUI.TransferPolicy policy)
    {
        NodeApi.CallMethodVoid(Module, _addDisallowedBluetoothProtocols, admin, accountId, protocols, policy);
    }

    /// <summary>
    /// removeDisallowedBluetoothProtocols
    /// </summary>
    public static void RemoveDisallowedBluetoothProtocols(IntPtr admin, double accountId, global::HarmonyOS.ArkUI.Protocol[] protocols, global::HarmonyOS.ArkUI.TransferPolicy policy)
    {
        NodeApi.CallMethodVoid(Module, _removeDisallowedBluetoothProtocols, admin, accountId, protocols, policy);
    }

    /// <summary>
    /// getDisallowedBluetoothProtocols
    /// </summary>
    public static global::HarmonyOS.ArkUI.Protocol[] GetDisallowedBluetoothProtocols(IntPtr admin, double accountId, global::HarmonyOS.ArkUI.TransferPolicy policy)
    {
        return NodeApi.CallMethod(Module, _getDisallowedBluetoothProtocols, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<global::HarmonyOS.ArkUI.Protocol>(e)), admin, accountId, policy);
    }

}
