// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// FloatView 绑定（@ohos.window.floatView）。
/// 所需权限：ohos.permission.FLOAT_VIEW, ohos.permission.USE_FLOAT_BALL
/// </summary>
public static unsafe partial class FloatView
{
    private const string ModuleName = "@ohos.window.floatView";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[window.floatView] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _isFloatViewEnabled => "isFloatViewEnabled"u8;
    private static ReadOnlySpan<byte> _create => "create"u8;
    private static ReadOnlySpan<byte> _bind => "bind"u8;
    private static ReadOnlySpan<byte> _unbind => "unbind"u8;
    private static ReadOnlySpan<byte> _getFloatViewLimits => "getFloatViewLimits"u8;

    /// <summary>
    /// isFloatViewEnabled
    /// </summary>
    public static bool IsFloatViewEnabled()
    {
        return NodeApi.CallMethod<bool>(Module, _isFloatViewEnabled);
    }

    /// <summary>
    /// create
    /// </summary>
    public static Task<FloatViewController> CreateAsync(IntPtr config)
    {
        return NodeApi.CallMethodAsync(Module, _create, static h => new FloatViewController(h), config);
    }

    /// <summary>
    /// bind
    /// </summary>
    public static Task BindAsync(FloatViewController floatViewController, IntPtr floatingBallController, IntPtr floatingBallParams)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _bind, floatViewController, floatingBallController, floatingBallParams);
    }

    /// <summary>
    /// unbind
    /// </summary>
    public static Task UnbindAsync(FloatViewController floatViewController, IntPtr floatingBallController)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _unbind, floatViewController, floatingBallController);
    }

    /// <summary>
    /// getFloatViewLimits
    /// </summary>
    public static IntPtr GetFloatViewLimits(global::HarmonyOS.ArkUI.FloatViewTemplateType templateType)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _getFloatViewLimits, templateType);
    }

}

/// <summary>
/// FloatViewController 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class FloatViewController : JsObject
{
    public FloatViewController(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _setUIContext => "setUIContext"u8;
    private static ReadOnlySpan<byte> _setUIContextByName => "setUIContextByName"u8;
    private static ReadOnlySpan<byte> _setWindowSize => "setWindowSize"u8;
    private static ReadOnlySpan<byte> _switchTemplate => "switchTemplate"u8;
    private static ReadOnlySpan<byte> _start => "start"u8;
    private static ReadOnlySpan<byte> _stop => "stop"u8;
    private static ReadOnlySpan<byte> _setFloatViewVisibilityInApp => "setFloatViewVisibilityInApp"u8;
    private static ReadOnlySpan<byte> _restoreMainWindow => "restoreMainWindow"u8;
    private static ReadOnlySpan<byte> _getWindowProperties => "getWindowProperties"u8;
    private static ReadOnlySpan<byte> _onStateChange => "onStateChange"u8;
    private static ReadOnlySpan<byte> _offStateChange => "offStateChange"u8;
    private static ReadOnlySpan<byte> _onRectChange => "onRectChange"u8;
    private static ReadOnlySpan<byte> _offRectChange => "offRectChange"u8;
    private static ReadOnlySpan<byte> _onLimitsChange => "onLimitsChange"u8;
    private static ReadOnlySpan<byte> _offLimitsChange => "offLimitsChange"u8;
    /// <summary>
    /// setUIContext
    /// </summary>
    public Task SetUiContextAsync(string path, IntPtr? storage = null)
    {
        return CallMethodAsyncVoid(_setUIContext, path, storage);
    }

    /// <summary>
    /// setUIContextByName
    /// </summary>
    public Task SetUiContextByNameAsync(string name, IntPtr? storage = null)
    {
        return CallMethodAsyncVoid(_setUIContextByName, name, storage);
    }

    /// <summary>
    /// setWindowSize
    /// </summary>
    public Task SetWindowSizeAsync(IntPtr size)
    {
        return CallMethodAsyncVoid(_setWindowSize, size);
    }

    /// <summary>
    /// switchTemplate
    /// </summary>
    public Task SwitchTemplateAsync(IntPtr templateProperty)
    {
        return CallMethodAsyncVoid(_switchTemplate, templateProperty);
    }

    /// <summary>
    /// start
    /// </summary>
    public Task StartAsync()
    {
        return CallMethodAsyncVoid(_start);
    }

    /// <summary>
    /// stop
    /// </summary>
    public Task StopAsync()
    {
        return CallMethodAsyncVoid(_stop);
    }

    /// <summary>
    /// setFloatViewVisibilityInApp
    /// </summary>
    public Task SetFloatViewVisibilityInAppAsync(bool isVisible)
    {
        return CallMethodAsyncVoid(_setFloatViewVisibilityInApp, isVisible);
    }

    /// <summary>
    /// restoreMainWindow
    /// </summary>
    public Task RestoreMainWindowAsync(IntPtr? wantParameters = null)
    {
        return CallMethodAsyncVoid(_restoreMainWindow, wantParameters);
    }

    /// <summary>
    /// getWindowProperties
    /// </summary>
    public IntPtr GetWindowProperties()
    {
        return CallMethod<IntPtr>(_getWindowProperties);
    }

    /// <summary>
    /// onStateChange
    /// </summary>
    public void OnStateChange(IntPtr callback)
    {
        CallMethodVoid(_onStateChange, callback);
    }

    /// <summary>
    /// offStateChange
    /// </summary>
    public void OffStateChange(IntPtr? callback = null)
    {
        CallMethodVoid(_offStateChange, callback);
    }

    /// <summary>
    /// onRectChange
    /// </summary>
    public void OnRectChange(IntPtr callback)
    {
        CallMethodVoid(_onRectChange, callback);
    }

    /// <summary>
    /// offRectChange
    /// </summary>
    public void OffRectChange(IntPtr? callback = null)
    {
        CallMethodVoid(_offRectChange, callback);
    }

    /// <summary>
    /// onLimitsChange
    /// </summary>
    public void OnLimitsChange(IntPtr callback)
    {
        CallMethodVoid(_onLimitsChange, callback);
    }

    /// <summary>
    /// offLimitsChange
    /// </summary>
    public void OffLimitsChange(IntPtr? callback = null)
    {
        CallMethodVoid(_offLimitsChange, callback);
    }

}
