// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// Font 绑定（@ohos.font）。
/// </summary>
public static unsafe partial class Font
{
    private const string ModuleName = "@ohos.font";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[font] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _registerFont => "registerFont"u8;
    private static ReadOnlySpan<byte> _getSystemFontList => "getSystemFontList"u8;
    private static ReadOnlySpan<byte> _getFontByName => "getFontByName"u8;
    private static ReadOnlySpan<byte> _getUIFontConfig => "getUIFontConfig"u8;

    /// <summary>
    /// registerFont
    /// </summary>
    public static void RegisterFont(FontOptions options)
    {
        NodeApi.CallMethodVoid(Module, _registerFont, options);
    }

    /// <summary>
    /// getSystemFontList
    /// </summary>
    public static string[] GetSystemFontList()
    {
        return NodeApi.CallMethod(Module, _getSystemFontList, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<string>(e)));
    }

    /// <summary>
    /// getFontByName
    /// </summary>
    public static FontInfo GetFontByName(string fontName)
    {
        return NodeApi.CallMethod(Module, _getFontByName, static h => new FontInfo(h), fontName);
    }

    /// <summary>
    /// getUIFontConfig
    /// </summary>
    public static IntPtr GetUiFontConfig()
    {
        return NodeApi.CallMethod<IntPtr>(Module, _getUIFontConfig);
    }

}

/// <summary>
/// FontOptions（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record FontOptions(
    string FamilyName,
    string FamilySrc
) : INapiRecord
{
    private static ReadOnlySpan<byte> _familyNameName => "familyName"u8;
    private static ReadOnlySpan<byte> _familySrcName => "familySrc"u8;
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _familyNameV = NativeValue.From(FamilyName);
        if (_familyNameV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _familyNameName, _familyNameV);
        var _familySrcV = NativeValue.From(FamilySrc);
        if (_familySrcV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _familySrcName, _familySrcV);
    }
}

/// <summary>
/// FontInfo 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class FontInfo : JsObject
{
    public FontInfo(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _path => "path"u8;
    private static ReadOnlySpan<byte> _postScriptName => "postScriptName"u8;
    private static ReadOnlySpan<byte> _fullName => "fullName"u8;
    private static ReadOnlySpan<byte> _family => "family"u8;
    private static ReadOnlySpan<byte> _subfamily => "subfamily"u8;
    private static ReadOnlySpan<byte> _weight => "weight"u8;
    private static ReadOnlySpan<byte> _width => "width"u8;
    private static ReadOnlySpan<byte> _italic => "italic"u8;
    private static ReadOnlySpan<byte> _monoSpace => "monoSpace"u8;
    private static ReadOnlySpan<byte> _symbolic => "symbolic"u8;
    /// <summary>
    /// path
    /// </summary>
    public string Path => NativeValue.ToString(GetPropertyRaw(_path)) ?? string.Empty;

    /// <summary>
    /// postScriptName
    /// </summary>
    public string PostScriptName => NativeValue.ToString(GetPropertyRaw(_postScriptName)) ?? string.Empty;

    /// <summary>
    /// fullName
    /// </summary>
    public string FullName => NativeValue.ToString(GetPropertyRaw(_fullName)) ?? string.Empty;

    /// <summary>
    /// family
    /// </summary>
    public string Family => NativeValue.ToString(GetPropertyRaw(_family)) ?? string.Empty;

    /// <summary>
    /// subfamily
    /// </summary>
    public string Subfamily => NativeValue.ToString(GetPropertyRaw(_subfamily)) ?? string.Empty;

    /// <summary>
    /// weight
    /// </summary>
    public double Weight => NativeValue.ToDouble(GetPropertyRaw(_weight));

    /// <summary>
    /// width
    /// </summary>
    public double Width => NativeValue.ToDouble(GetPropertyRaw(_width));

    /// <summary>
    /// italic
    /// </summary>
    public bool Italic => NativeValue.ToBool(GetPropertyRaw(_italic));

    /// <summary>
    /// monoSpace
    /// </summary>
    public bool MonoSpace => NativeValue.ToBool(GetPropertyRaw(_monoSpace));

    /// <summary>
    /// symbolic
    /// </summary>
    public bool Symbolic => NativeValue.ToBool(GetPropertyRaw(_symbolic));

}
