// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// Fs 绑定（@ohos.file.fs）。
/// 所需权限：ohos.permission.DISTRIBUTED_DATASYNC
/// </summary>
public static unsafe partial class Fs
{
    private const string ModuleName = "@ohos.file.fs";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[file.fs] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _READ_ONLY => "READ_ONLY"u8;
    private static ReadOnlySpan<byte> _WRITE_ONLY => "WRITE_ONLY"u8;
    private static ReadOnlySpan<byte> _READ_WRITE => "READ_WRITE"u8;
    private static ReadOnlySpan<byte> _CREATE => "CREATE"u8;
    private static ReadOnlySpan<byte> _TRUNC => "TRUNC"u8;
    private static ReadOnlySpan<byte> _APPEND => "APPEND"u8;
    private static ReadOnlySpan<byte> _NONBLOCK => "NONBLOCK"u8;
    private static ReadOnlySpan<byte> _DIR => "DIR"u8;
    private static ReadOnlySpan<byte> _NOFOLLOW => "NOFOLLOW"u8;
    private static ReadOnlySpan<byte> _SYNC => "SYNC"u8;
    private static ReadOnlySpan<byte> _UNCACHE => "UNCACHE"u8;
    private static ReadOnlySpan<byte> _access => "access"u8;
    private static ReadOnlySpan<byte> _accessSync => "accessSync"u8;
    private static ReadOnlySpan<byte> _close => "close"u8;
    private static ReadOnlySpan<byte> _closeSync => "closeSync"u8;
    private static ReadOnlySpan<byte> _copy => "copy"u8;
    private static ReadOnlySpan<byte> _copyDir => "copyDir"u8;
    private static ReadOnlySpan<byte> _copyDirSync => "copyDirSync"u8;
    private static ReadOnlySpan<byte> _copyFile => "copyFile"u8;
    private static ReadOnlySpan<byte> _copyFileSync => "copyFileSync"u8;
    private static ReadOnlySpan<byte> _createStream => "createStream"u8;
    private static ReadOnlySpan<byte> _createStreamSync => "createStreamSync"u8;
    private static ReadOnlySpan<byte> _createRandomAccessFile => "createRandomAccessFile"u8;
    private static ReadOnlySpan<byte> _createRandomAccessFileSync => "createRandomAccessFileSync"u8;
    private static ReadOnlySpan<byte> _createReadStream => "createReadStream"u8;
    private static ReadOnlySpan<byte> _createWriteStream => "createWriteStream"u8;
    private static ReadOnlySpan<byte> _createWatcher => "createWatcher"u8;
    private static ReadOnlySpan<byte> _dup => "dup"u8;
    private static ReadOnlySpan<byte> _fdatasync => "fdatasync"u8;
    private static ReadOnlySpan<byte> _fdatasyncSync => "fdatasyncSync"u8;
    private static ReadOnlySpan<byte> _fdopenStream => "fdopenStream"u8;
    private static ReadOnlySpan<byte> _fdopenStreamSync => "fdopenStreamSync"u8;
    private static ReadOnlySpan<byte> _fsync => "fsync"u8;
    private static ReadOnlySpan<byte> _fsyncSync => "fsyncSync"u8;
    private static ReadOnlySpan<byte> _listFile => "listFile"u8;
    private static ReadOnlySpan<byte> _listFileSync => "listFileSync"u8;
    private static ReadOnlySpan<byte> _listFileExt => "listFileExt"u8;
    private static ReadOnlySpan<byte> _listFileExtSync => "listFileExtSync"u8;
    private static ReadOnlySpan<byte> _lseek => "lseek"u8;
    private static ReadOnlySpan<byte> _lstat => "lstat"u8;
    private static ReadOnlySpan<byte> _lstatSync => "lstatSync"u8;
    private static ReadOnlySpan<byte> _mkdir => "mkdir"u8;
    private static ReadOnlySpan<byte> _mkdirSync => "mkdirSync"u8;
    private static ReadOnlySpan<byte> _mkdtemp => "mkdtemp"u8;
    private static ReadOnlySpan<byte> _mkdtempSync => "mkdtempSync"u8;
    private static ReadOnlySpan<byte> _mmap => "mmap"u8;
    private static ReadOnlySpan<byte> _mmapSync => "mmapSync"u8;
    private static ReadOnlySpan<byte> _moveDir => "moveDir"u8;
    private static ReadOnlySpan<byte> _moveDirSync => "moveDirSync"u8;
    private static ReadOnlySpan<byte> _moveFile => "moveFile"u8;
    private static ReadOnlySpan<byte> _moveFileSync => "moveFileSync"u8;
    private static ReadOnlySpan<byte> _open => "open"u8;
    private static ReadOnlySpan<byte> _openSync => "openSync"u8;
    private static ReadOnlySpan<byte> _read => "read"u8;
    private static ReadOnlySpan<byte> _readSync => "readSync"u8;
    private static ReadOnlySpan<byte> _readLines => "readLines"u8;
    private static ReadOnlySpan<byte> _readLinesSync => "readLinesSync"u8;
    private static ReadOnlySpan<byte> _readText => "readText"u8;
    private static ReadOnlySpan<byte> _readTextSync => "readTextSync"u8;
    private static ReadOnlySpan<byte> _rename => "rename"u8;
    private static ReadOnlySpan<byte> _renameSync => "renameSync"u8;
    private static ReadOnlySpan<byte> _rmdir => "rmdir"u8;
    private static ReadOnlySpan<byte> _rmdirSync => "rmdirSync"u8;
    private static ReadOnlySpan<byte> _stat => "stat"u8;
    private static ReadOnlySpan<byte> _statSync => "statSync"u8;
    private static ReadOnlySpan<byte> _symlink => "symlink"u8;
    private static ReadOnlySpan<byte> _symlinkSync => "symlinkSync"u8;
    private static ReadOnlySpan<byte> _truncate => "truncate"u8;
    private static ReadOnlySpan<byte> _truncateSync => "truncateSync"u8;
    private static ReadOnlySpan<byte> _unlink => "unlink"u8;
    private static ReadOnlySpan<byte> _unlinkSync => "unlinkSync"u8;
    private static ReadOnlySpan<byte> _utimes => "utimes"u8;
    private static ReadOnlySpan<byte> _write => "write"u8;
    private static ReadOnlySpan<byte> _writeSync => "writeSync"u8;
    private static ReadOnlySpan<byte> _connectDfs => "connectDfs"u8;
    private static ReadOnlySpan<byte> _disconnectDfs => "disconnectDfs"u8;
    private static ReadOnlySpan<byte> _setxattr => "setxattr"u8;
    private static ReadOnlySpan<byte> _setxattrSync => "setxattrSync"u8;
    private static ReadOnlySpan<byte> _getxattr => "getxattr"u8;
    private static ReadOnlySpan<byte> _getxattrSync => "getxattrSync"u8;

    /// <summary>
    /// READ_ONLY
    /// </summary>
    public static double ReadOnly => NativeValue.ToDouble(NodeApi.GetProperty(Module, _READ_ONLY));

    /// <summary>
    /// WRITE_ONLY
    /// </summary>
    public static double WriteOnly => NativeValue.ToDouble(NodeApi.GetProperty(Module, _WRITE_ONLY));

    /// <summary>
    /// READ_WRITE
    /// </summary>
    public static double ReadWrite => NativeValue.ToDouble(NodeApi.GetProperty(Module, _READ_WRITE));

    /// <summary>
    /// CREATE
    /// </summary>
    public static double Create => NativeValue.ToDouble(NodeApi.GetProperty(Module, _CREATE));

    /// <summary>
    /// TRUNC
    /// </summary>
    public static double Trunc => NativeValue.ToDouble(NodeApi.GetProperty(Module, _TRUNC));

    /// <summary>
    /// APPEND
    /// </summary>
    public static double Append => NativeValue.ToDouble(NodeApi.GetProperty(Module, _APPEND));

    /// <summary>
    /// NONBLOCK
    /// </summary>
    public static double Nonblock => NativeValue.ToDouble(NodeApi.GetProperty(Module, _NONBLOCK));

    /// <summary>
    /// DIR
    /// </summary>
    public static double Dir => NativeValue.ToDouble(NodeApi.GetProperty(Module, _DIR));

    /// <summary>
    /// NOFOLLOW
    /// </summary>
    public static double Nofollow => NativeValue.ToDouble(NodeApi.GetProperty(Module, _NOFOLLOW));

    /// <summary>
    /// SYNC
    /// </summary>
    public static double Sync => NativeValue.ToDouble(NodeApi.GetProperty(Module, _SYNC));

    /// <summary>
    /// UNCACHE
    /// </summary>
    public static double Uncache => NativeValue.ToDouble(NodeApi.GetProperty(Module, _UNCACHE));

    /// <summary>
    /// access
    /// </summary>
    public static Task<bool> AccessAsync(string path, global::HarmonyOS.ArkUI.AccessModeType? mode = null)
    {
        return NodeApi.CallMethodAsync<bool>(Module, _access, path, mode);
    }

    /// <summary>
    /// access
    /// </summary>
    public static Task<bool> AccessAsync(string path)
    {
        return NodeApi.CallMethodAsyncCallback<bool>(Module, _access, null, path);
    }

    /// <summary>
    /// access
    /// </summary>
    public static Task<bool> AccessAsync(string path, global::HarmonyOS.ArkUI.AccessModeType mode, global::HarmonyOS.ArkUI.AccessFlagType flag)
    {
        return NodeApi.CallMethodAsync<bool>(Module, _access, path, mode, flag);
    }

    /// <summary>
    /// accessSync
    /// </summary>
    public static bool AccessSync(string path, global::HarmonyOS.ArkUI.AccessModeType? mode = null)
    {
        return NodeApi.CallMethod<bool>(Module, _accessSync, path, mode);
    }

    /// <summary>
    /// accessSync
    /// </summary>
    public static bool AccessSync(string path, global::HarmonyOS.ArkUI.AccessModeType mode, global::HarmonyOS.ArkUI.AccessFlagType flag)
    {
        return NodeApi.CallMethod<bool>(Module, _accessSync, path, mode, flag);
    }

    /// <summary>
    /// close
    /// </summary>
    public static Task CloseAsync(double file)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _close, file);
    }

    /// <summary>
    /// closeSync
    /// </summary>
    public static void CloseSync(double file)
    {
        NodeApi.CallMethodVoid(Module, _closeSync, file);
    }

    /// <summary>
    /// copy
    /// </summary>
    public static Task CopyAsync(string srcUri, string destUri, IntPtr? options = null)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _copy, srcUri, destUri, options);
    }

    /// <summary>
    /// copy
    /// </summary>
    public static Task CopyAsync(string srcUri, string destUri)
    {
        return NodeApi.CallMethodAsyncCallbackVoid(Module, _copy, srcUri, destUri);
    }

    /// <summary>
    /// copyDir
    /// </summary>
    public static Task CopyDirAsync(string src, string dest, double? mode = null)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _copyDir, src, dest, mode);
    }

    /// <summary>
    /// copyDir
    /// </summary>
    public static Task CopyDirAsync(string src, string dest)
    {
        return NodeApi.CallMethodAsyncCallbackVoid(Module, _copyDir, src, dest);
    }

    /// <summary>
    /// copyDirSync
    /// </summary>
    public static void CopyDirSync(string src, string dest, double? mode = null)
    {
        NodeApi.CallMethodVoid(Module, _copyDirSync, src, dest, mode);
    }

    /// <summary>
    /// copyFile
    /// </summary>
    public static Task CopyFileAsync(string src, string dest, double? mode = null)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _copyFile, src, dest, mode);
    }

    /// <summary>
    /// copyFile
    /// </summary>
    public static Task CopyFileAsync(string src, string dest)
    {
        return NodeApi.CallMethodAsyncCallbackVoid(Module, _copyFile, src, dest);
    }

    /// <summary>
    /// copyFileSync
    /// </summary>
    public static void CopyFileSync(string src, string dest, double? mode = null)
    {
        NodeApi.CallMethodVoid(Module, _copyFileSync, src, dest, mode);
    }

    /// <summary>
    /// createStream
    /// </summary>
    public static Task<IntPtr> CreateStreamAsync(string path, string mode)
    {
        return NodeApi.CallMethodAsync<IntPtr>(Module, _createStream, path, mode);
    }

    /// <summary>
    /// createStreamSync
    /// </summary>
    public static IntPtr CreateStreamSync(string path, string mode)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _createStreamSync, path, mode);
    }

    /// <summary>
    /// createRandomAccessFile
    /// </summary>
    public static Task<IntPtr> CreateRandomAccessFileAsync(string file, double? mode = null, RandomAccessFileOptions? options = null)
    {
        return NodeApi.CallMethodAsync<IntPtr>(Module, _createRandomAccessFile, file, mode, options);
    }

    /// <summary>
    /// createRandomAccessFile
    /// </summary>
    public static Task<RandomAccessFile> CreateRandomAccessFileAsync(string file)
    {
        return NodeApi.CallMethodAsyncCallback(Module, _createRandomAccessFile, static h => new RandomAccessFile(h), file);
    }

    /// <summary>
    /// createRandomAccessFile
    /// </summary>
    public static Task<RandomAccessFile> CreateRandomAccessFileAsync(string file, double mode)
    {
        return NodeApi.CallMethodAsyncCallback(Module, _createRandomAccessFile, static h => new RandomAccessFile(h), file, mode);
    }

    /// <summary>
    /// createRandomAccessFileSync
    /// </summary>
    public static IntPtr CreateRandomAccessFileSync(string file, double? mode = null, RandomAccessFileOptions? options = null)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _createRandomAccessFileSync, file, mode, options);
    }

    /// <summary>
    /// createReadStream
    /// </summary>
    public static IntPtr CreateReadStream(string path, ReadStreamOptions? options = null)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _createReadStream, path, options);
    }

    /// <summary>
    /// createWriteStream
    /// </summary>
    public static IntPtr CreateWriteStream(string path, WriteStreamOptions? options = null)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _createWriteStream, path, options);
    }

    /// <summary>
    /// createWatcher
    /// </summary>
    public static IntPtr CreateWatcher(string path, double events, WatchEventListener listener)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _createWatcher, path, events, listener);
    }

    /// <summary>
    /// dup
    /// </summary>
    public static FsFile Dup(double fd)
    {
        return NodeApi.CallMethod(Module, _dup, static h => new FsFile(h), fd);
    }

    /// <summary>
    /// fdatasync
    /// </summary>
    public static Task FdatasyncAsync(double fd)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _fdatasync, fd);
    }

    /// <summary>
    /// fdatasyncSync
    /// </summary>
    public static void FdatasyncSync(double fd)
    {
        NodeApi.CallMethodVoid(Module, _fdatasyncSync, fd);
    }

    /// <summary>
    /// fdopenStream
    /// </summary>
    public static Task<IntPtr> FdopenStreamAsync(double fd, string mode)
    {
        return NodeApi.CallMethodAsync<IntPtr>(Module, _fdopenStream, fd, mode);
    }

    /// <summary>
    /// fdopenStreamSync
    /// </summary>
    public static IntPtr FdopenStreamSync(double fd, string mode)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _fdopenStreamSync, fd, mode);
    }

    /// <summary>
    /// fsync
    /// </summary>
    public static Task FsyncAsync(double fd)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _fsync, fd);
    }

    /// <summary>
    /// fsyncSync
    /// </summary>
    public static void FsyncSync(double fd)
    {
        NodeApi.CallMethodVoid(Module, _fsyncSync, fd);
    }

    /// <summary>
    /// listFile
    /// </summary>
    public static Task<string[]> ListFileAsync(string path, ListFileOptions? options = null)
    {
        return NodeApi.CallMethodAsync(Module, _listFile, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<string>(e)), path, options);
    }

    /// <summary>
    /// listFile
    /// </summary>
    public static Task<string[]> ListFileAsync(string path)
    {
        return NodeApi.CallMethodAsyncCallback(Module, _listFile, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<string>(e)), path);
    }

    /// <summary>
    /// listFileSync
    /// </summary>
    public static string[] ListFileSync(string path, ListFileOptions? options = null)
    {
        return NodeApi.CallMethod(Module, _listFileSync, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<string>(e)), path, options);
    }

    /// <summary>
    /// listFileExt
    /// </summary>
    public static Task<string[]> ListFileExtAsync(string path, ListFileExtOptions? options = null)
    {
        return NodeApi.CallMethodAsync(Module, _listFileExt, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<string>(e)), path, options);
    }

    /// <summary>
    /// listFileExtSync
    /// </summary>
    public static string[] ListFileExtSync(string path, ListFileExtOptions? options = null)
    {
        return NodeApi.CallMethod(Module, _listFileExtSync, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<string>(e)), path, options);
    }

    /// <summary>
    /// lseek
    /// </summary>
    public static double Lseek(double fd, double offset, global::HarmonyOS.ArkUI.WhenceType? whence = null)
    {
        return NodeApi.CallMethod<double>(Module, _lseek, fd, offset, whence);
    }

    /// <summary>
    /// lstat
    /// </summary>
    public static Task<IntPtr> LstatAsync(string path)
    {
        return NodeApi.CallMethodAsync<IntPtr>(Module, _lstat, path);
    }

    /// <summary>
    /// lstatSync
    /// </summary>
    public static IntPtr LstatSync(string path)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _lstatSync, path);
    }

    /// <summary>
    /// mkdir
    /// </summary>
    public static Task MkdirAsync(string path)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _mkdir, path);
    }

    /// <summary>
    /// mkdir
    /// </summary>
    public static Task MkdirAsync(string path, bool recursion)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _mkdir, path, recursion);
    }

    /// <summary>
    /// mkdirSync
    /// </summary>
    public static void MkdirSync(string path)
    {
        NodeApi.CallMethodVoid(Module, _mkdirSync, path);
    }

    /// <summary>
    /// mkdirSync
    /// </summary>
    public static void MkdirSync(string path, bool recursion)
    {
        NodeApi.CallMethodVoid(Module, _mkdirSync, path, recursion);
    }

    /// <summary>
    /// mkdtemp
    /// </summary>
    public static Task<string> MkdtempAsync(string prefix)
    {
        return NodeApi.CallMethodAsync<string>(Module, _mkdtemp, prefix);
    }

    /// <summary>
    /// mkdtempSync
    /// </summary>
    public static string MkdtempSync(string prefix)
    {
        return NodeApi.CallMethod<string>(Module, _mkdtempSync, prefix);
    }

    /// <summary>
    /// mmap
    /// </summary>
    public static Task<IntPtr> MmapAsync(double file, global::HarmonyOS.ArkUI.MappingMode mode, double offset, double size)
    {
        return NodeApi.CallMethodAsync<IntPtr>(Module, _mmap, file, mode, offset, size);
    }

    /// <summary>
    /// mmapSync
    /// </summary>
    public static IntPtr MmapSync(double file, global::HarmonyOS.ArkUI.MappingMode mode, double offset, double size)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _mmapSync, file, mode, offset, size);
    }

    /// <summary>
    /// moveDir
    /// </summary>
    public static Task MoveDirAsync(string src, string dest, double? mode = null)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _moveDir, src, dest, mode);
    }

    /// <summary>
    /// moveDir
    /// </summary>
    public static Task MoveDirAsync(string src, string dest)
    {
        return NodeApi.CallMethodAsyncCallbackVoid(Module, _moveDir, src, dest);
    }

    /// <summary>
    /// moveDirSync
    /// </summary>
    public static void MoveDirSync(string src, string dest, double? mode = null)
    {
        NodeApi.CallMethodVoid(Module, _moveDirSync, src, dest, mode);
    }

    /// <summary>
    /// moveFile
    /// </summary>
    public static Task MoveFileAsync(string src, string dest, double? mode = null)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _moveFile, src, dest, mode);
    }

    /// <summary>
    /// moveFile
    /// </summary>
    public static Task MoveFileAsync(string src, string dest)
    {
        return NodeApi.CallMethodAsyncCallbackVoid(Module, _moveFile, src, dest);
    }

    /// <summary>
    /// moveFileSync
    /// </summary>
    public static void MoveFileSync(string src, string dest, double? mode = null)
    {
        NodeApi.CallMethodVoid(Module, _moveFileSync, src, dest, mode);
    }

    /// <summary>
    /// open
    /// </summary>
    public static Task<FsFile> OpenAsync(string path, double? mode = null)
    {
        return NodeApi.CallMethodAsync(Module, _open, static h => new FsFile(h), path, mode);
    }

    /// <summary>
    /// open
    /// </summary>
    public static Task<FsFile> OpenAsync(string path)
    {
        return NodeApi.CallMethodAsyncCallback(Module, _open, static h => new FsFile(h), path);
    }

    /// <summary>
    /// openSync
    /// </summary>
    public static FsFile OpenSync(string path, double? mode = null)
    {
        return NodeApi.CallMethod(Module, _openSync, static h => new FsFile(h), path, mode);
    }

    /// <summary>
    /// read
    /// </summary>
    public static Task<double> ReadAsync(double fd, byte[] buffer, ReadOptions? options = null)
    {
        return NodeApi.CallMethodAsync<double>(Module, _read, fd, buffer, options);
    }

    /// <summary>
    /// read
    /// </summary>
    public static Task<double> ReadAsync(double fd, byte[] buffer)
    {
        return NodeApi.CallMethodAsyncCallback<double>(Module, _read, null, fd, buffer);
    }

    /// <summary>
    /// readSync
    /// </summary>
    public static double ReadSync(double fd, byte[] buffer, ReadOptions? options = null)
    {
        return NodeApi.CallMethod<double>(Module, _readSync, fd, buffer, options);
    }

    /// <summary>
    /// readLines
    /// </summary>
    public static Task<IntPtr> ReadLinesAsync(string filePath, FsOptions? options = null)
    {
        return NodeApi.CallMethodAsync<IntPtr>(Module, _readLines, filePath, options);
    }

    /// <summary>
    /// readLines
    /// </summary>
    public static Task<ReaderIterator> ReadLinesAsync(string filePath)
    {
        return NodeApi.CallMethodAsyncCallback(Module, _readLines, static h => new ReaderIterator(h), filePath);
    }

    /// <summary>
    /// readLinesSync
    /// </summary>
    public static IntPtr ReadLinesSync(string filePath, FsOptions? options = null)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _readLinesSync, filePath, options);
    }

    /// <summary>
    /// readText
    /// </summary>
    public static Task<string> ReadTextAsync(string filePath, ReadTextOptions? options = null)
    {
        return NodeApi.CallMethodAsync<string>(Module, _readText, filePath, options);
    }

    /// <summary>
    /// readText
    /// </summary>
    public static Task<string> ReadTextAsync(string filePath)
    {
        return NodeApi.CallMethodAsyncCallback<string>(Module, _readText, null, filePath);
    }

    /// <summary>
    /// readTextSync
    /// </summary>
    public static string ReadTextSync(string filePath, ReadTextOptions? options = null)
    {
        return NodeApi.CallMethod<string>(Module, _readTextSync, filePath, options);
    }

    /// <summary>
    /// rename
    /// </summary>
    public static Task RenameAsync(string oldPath, string newPath)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _rename, oldPath, newPath);
    }

    /// <summary>
    /// renameSync
    /// </summary>
    public static void RenameSync(string oldPath, string newPath)
    {
        NodeApi.CallMethodVoid(Module, _renameSync, oldPath, newPath);
    }

    /// <summary>
    /// rmdir
    /// </summary>
    public static Task RmdirAsync(string path)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _rmdir, path);
    }

    /// <summary>
    /// rmdirSync
    /// </summary>
    public static void RmdirSync(string path)
    {
        NodeApi.CallMethodVoid(Module, _rmdirSync, path);
    }

    /// <summary>
    /// stat
    /// </summary>
    public static Task<IntPtr> StatAsync(string file)
    {
        return NodeApi.CallMethodAsync<IntPtr>(Module, _stat, file);
    }

    /// <summary>
    /// statSync
    /// </summary>
    public static IntPtr StatSync(string file)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _statSync, file);
    }

    /// <summary>
    /// symlink
    /// </summary>
    public static Task SymlinkAsync(string target, string srcPath)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _symlink, target, srcPath);
    }

    /// <summary>
    /// symlinkSync
    /// </summary>
    public static void SymlinkSync(string target, string srcPath)
    {
        NodeApi.CallMethodVoid(Module, _symlinkSync, target, srcPath);
    }

    /// <summary>
    /// truncate
    /// </summary>
    public static Task TruncateAsync(string file, double? len = null)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _truncate, file, len);
    }

    /// <summary>
    /// truncate
    /// </summary>
    public static Task TruncateAsync(string file)
    {
        return NodeApi.CallMethodAsyncCallbackVoid(Module, _truncate, file);
    }

    /// <summary>
    /// truncateSync
    /// </summary>
    public static void TruncateSync(string file, double? len = null)
    {
        NodeApi.CallMethodVoid(Module, _truncateSync, file, len);
    }

    /// <summary>
    /// unlink
    /// </summary>
    public static Task UnlinkAsync(string path)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _unlink, path);
    }

    /// <summary>
    /// unlinkSync
    /// </summary>
    public static void UnlinkSync(string path)
    {
        NodeApi.CallMethodVoid(Module, _unlinkSync, path);
    }

    /// <summary>
    /// utimes
    /// </summary>
    public static void Utimes(string path, double mtime)
    {
        NodeApi.CallMethodVoid(Module, _utimes, path, mtime);
    }

    /// <summary>
    /// write
    /// </summary>
    public static Task<double> WriteAsync(double fd, byte[] buffer, WriteOptions? options = null)
    {
        return NodeApi.CallMethodAsync<double>(Module, _write, fd, buffer, options);
    }

    /// <summary>
    /// write
    /// </summary>
    public static Task<double> WriteAsync(double fd, byte[] buffer)
    {
        return NodeApi.CallMethodAsyncCallback<double>(Module, _write, null, fd, buffer);
    }

    /// <summary>
    /// writeSync
    /// </summary>
    public static double WriteSync(double fd, byte[] buffer, WriteOptions? options = null)
    {
        return NodeApi.CallMethod<double>(Module, _writeSync, fd, buffer, options);
    }

    /// <summary>
    /// connectDfs
    /// </summary>
    public static Task ConnectDfsAsync(string networkId, DfsListeners listeners)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _connectDfs, networkId, listeners);
    }

    /// <summary>
    /// disconnectDfs
    /// </summary>
    public static Task DisconnectDfsAsync(string networkId)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _disconnectDfs, networkId);
    }

    /// <summary>
    /// setxattr
    /// </summary>
    public static Task SetxattrAsync(string path, string key, string value)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _setxattr, path, key, value);
    }

    /// <summary>
    /// setxattrSync
    /// </summary>
    public static void SetxattrSync(string path, string key, string value)
    {
        NodeApi.CallMethodVoid(Module, _setxattrSync, path, key, value);
    }

    /// <summary>
    /// getxattr
    /// </summary>
    public static Task<string> GetxattrAsync(string path, string key)
    {
        return NodeApi.CallMethodAsync<string>(Module, _getxattr, path, key);
    }

    /// <summary>
    /// getxattrSync
    /// </summary>
    public static string GetxattrSync(string path, string key)
    {
        return NodeApi.CallMethod<string>(Module, _getxattrSync, path, key);
    }

}

/// <summary>
/// RandomAccessFileOptions（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record RandomAccessFileOptions(
    double? Start = null,
    double? End = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _start = System.Text.Encoding.UTF8.GetBytes("start");
        var _startV = NativeValue.From(Start);
        if (_startV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _start, _startV);
        var _end = System.Text.Encoding.UTF8.GetBytes("end");
        var _endV = NativeValue.From(End);
        if (_endV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _end, _endV);
    }
}

/// <summary>
/// RandomAccessFile 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class RandomAccessFile : JsObject
{
    public RandomAccessFile(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _fd => "fd"u8;
    private static ReadOnlySpan<byte> _filePointer => "filePointer"u8;
    private static ReadOnlySpan<byte> _setFilePointer => "setFilePointer"u8;
    private static ReadOnlySpan<byte> _close => "close"u8;
    private static ReadOnlySpan<byte> _write => "write"u8;
    private static ReadOnlySpan<byte> _writeSync => "writeSync"u8;
    private static ReadOnlySpan<byte> _read => "read"u8;
    private static ReadOnlySpan<byte> _readSync => "readSync"u8;
    private static ReadOnlySpan<byte> _getReadStream => "getReadStream"u8;
    private static ReadOnlySpan<byte> _getWriteStream => "getWriteStream"u8;
    /// <summary>
    /// fd
    /// </summary>
    public double Fd => NativeValue.ToDouble(GetPropertyRaw(_fd));

    /// <summary>
    /// filePointer
    /// </summary>
    public double FilePointer => NativeValue.ToDouble(GetPropertyRaw(_filePointer));

    /// <summary>
    /// setFilePointer
    /// </summary>
    public void SetFilePointer(double filePointer)
    {
        CallMethodVoid(_setFilePointer, filePointer);
    }

    /// <summary>
    /// close
    /// </summary>
    public void Close()
    {
        CallMethodVoid(_close);
    }

    /// <summary>
    /// write
    /// </summary>
    public Task<double> WriteAsync(byte[] buffer, WriteOptions? options = null)
    {
        return CallMethodAsync<double>(_write, buffer, options);
    }

    /// <summary>
    /// write
    /// </summary>
    public Task<double> WriteAsync(byte[] buffer)
    {
        return CallMethodAsyncCallback<double>(_write, null, buffer);
    }

    /// <summary>
    /// writeSync
    /// </summary>
    public double WriteSync(byte[] buffer, WriteOptions? options = null)
    {
        return CallMethod<double>(_writeSync, buffer, options);
    }

    /// <summary>
    /// read
    /// </summary>
    public Task<double> ReadAsync(byte[] buffer, ReadOptions? options = null)
    {
        return CallMethodAsync<double>(_read, buffer, options);
    }

    /// <summary>
    /// read
    /// </summary>
    public Task<double> ReadAsync(byte[] buffer)
    {
        return CallMethodAsyncCallback<double>(_read, null, buffer);
    }

    /// <summary>
    /// readSync
    /// </summary>
    public double ReadSync(byte[] buffer, ReadOptions? options = null)
    {
        return CallMethod<double>(_readSync, buffer, options);
    }

    /// <summary>
    /// getReadStream
    /// </summary>
    public ReadStream GetReadStream()
    {
        return CallMethod(_getReadStream, static h => new ReadStream(h));
    }

    /// <summary>
    /// getWriteStream
    /// </summary>
    public WriteStream GetWriteStream()
    {
        return CallMethod(_getWriteStream, static h => new WriteStream(h));
    }

}

/// <summary>
/// ReadStreamOptions（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record ReadStreamOptions(
    double? Start = null,
    double? End = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _start = System.Text.Encoding.UTF8.GetBytes("start");
        var _startV = NativeValue.From(Start);
        if (_startV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _start, _startV);
        var _end = System.Text.Encoding.UTF8.GetBytes("end");
        var _endV = NativeValue.From(End);
        if (_endV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _end, _endV);
    }
}

/// <summary>
/// WriteStreamOptions（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record WriteStreamOptions(
    double? Mode = null,
    double? Start = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _mode = System.Text.Encoding.UTF8.GetBytes("mode");
        var _modeV = NativeValue.From(Mode);
        if (_modeV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _mode, _modeV);
        var _start = System.Text.Encoding.UTF8.GetBytes("start");
        var _startV = NativeValue.From(Start);
        if (_startV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _start, _startV);
    }
}

/// <summary>
/// WatchEventListener 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class WatchEventListener : JsObject
{
    public WatchEventListener(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> ___call__ => "__call__"u8;
}

/// <summary>
/// File 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class FsFile : JsObject
{
    public FsFile(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _fd => "fd"u8;
    private static ReadOnlySpan<byte> _path => "path"u8;
    private static ReadOnlySpan<byte> _name => "name"u8;
    private static ReadOnlySpan<byte> _getParent => "getParent"u8;
    private static ReadOnlySpan<byte> _lock => "lock"u8;
    private static ReadOnlySpan<byte> _tryLock => "tryLock"u8;
    private static ReadOnlySpan<byte> _unlock => "unlock"u8;
    /// <summary>
    /// fd
    /// </summary>
    public double Fd => NativeValue.ToDouble(GetPropertyRaw(_fd));

    /// <summary>
    /// path
    /// </summary>
    public string Path => NativeValue.ToString(GetPropertyRaw(_path)) ?? string.Empty;

    /// <summary>
    /// name
    /// </summary>
    public string Name => NativeValue.ToString(GetPropertyRaw(_name)) ?? string.Empty;

    /// <summary>
    /// getParent
    /// </summary>
    public string GetParent()
    {
        return CallMethod<string>(_getParent);
    }

    /// <summary>
    /// lock
    /// </summary>
    public Task LockAsync(bool? exclusive = null)
    {
        return CallMethodAsyncVoid(_lock, exclusive);
    }

    /// <summary>
    /// lock
    /// </summary>
    public Task LockAsync()
    {
        return CallMethodAsyncCallbackVoid(_lock);
    }

    /// <summary>
    /// tryLock
    /// </summary>
    public void TryLock(bool? exclusive = null)
    {
        CallMethodVoid(_tryLock, exclusive);
    }

    /// <summary>
    /// unlock
    /// </summary>
    public void Unlock()
    {
        CallMethodVoid(_unlock);
    }

}

/// <summary>
/// ListFileOptions（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record ListFileOptions(
    bool? Recursion = null,
    double? ListNum = null,
    FsFilter? Filter = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _recursion = System.Text.Encoding.UTF8.GetBytes("recursion");
        var _recursionV = NativeValue.From(Recursion);
        if (_recursionV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _recursion, _recursionV);
        var _listNum = System.Text.Encoding.UTF8.GetBytes("listNum");
        var _listNumV = NativeValue.From(ListNum);
        if (_listNumV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _listNum, _listNumV);
        var _filter = System.Text.Encoding.UTF8.GetBytes("filter");
        var _filterV = NativeValue.From(Filter);
        if (_filterV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _filter, _filterV);
    }
}

/// <summary>
/// ListFileExtOptions（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record ListFileExtOptions(
    bool? Recursion = null,
    double? ListNum = null,
    FileFilter? FileFilter = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _recursion = System.Text.Encoding.UTF8.GetBytes("recursion");
        var _recursionV = NativeValue.From(Recursion);
        if (_recursionV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _recursion, _recursionV);
        var _listNum = System.Text.Encoding.UTF8.GetBytes("listNum");
        var _listNumV = NativeValue.From(ListNum);
        if (_listNumV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _listNum, _listNumV);
        var _fileFilter = System.Text.Encoding.UTF8.GetBytes("fileFilter");
        var _fileFilterV = NativeValue.From(FileFilter);
        if (_fileFilterV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _fileFilter, _fileFilterV);
    }
}

/// <summary>
/// ReadOptions（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record ReadOptions(
    double? Offset = null,
    double? Length = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _offset = System.Text.Encoding.UTF8.GetBytes("offset");
        var _offsetV = NativeValue.From(Offset);
        if (_offsetV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _offset, _offsetV);
        var _length = System.Text.Encoding.UTF8.GetBytes("length");
        var _lengthV = NativeValue.From(Length);
        if (_lengthV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _length, _lengthV);
    }
}

/// <summary>
/// Options（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record FsOptions(
    string? Encoding = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _encoding = System.Text.Encoding.UTF8.GetBytes("encoding");
        var _encodingV = NativeValue.From(Encoding);
        if (_encodingV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _encoding, _encodingV);
    }
}

/// <summary>
/// ReaderIterator 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class ReaderIterator : JsObject
{
    public ReaderIterator(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _next => "next"u8;
    /// <summary>
    /// next
    /// </summary>
    public ReaderIteratorResult Next()
    {
        return CallMethod(_next, static h => new ReaderIteratorResult(h));
    }

}

/// <summary>
/// ReadTextOptions（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record ReadTextOptions(
    double? Offset = null,
    double? Length = null,
    string? Encoding = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _offset = System.Text.Encoding.UTF8.GetBytes("offset");
        var _offsetV = NativeValue.From(Offset);
        if (_offsetV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _offset, _offsetV);
        var _length = System.Text.Encoding.UTF8.GetBytes("length");
        var _lengthV = NativeValue.From(Length);
        if (_lengthV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _length, _lengthV);
        var _encoding = System.Text.Encoding.UTF8.GetBytes("encoding");
        var _encodingV = NativeValue.From(Encoding);
        if (_encodingV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _encoding, _encodingV);
    }
}

/// <summary>
/// WriteOptions（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record WriteOptions(
    string? Encoding = null,
    double? Offset = null,
    double? Length = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _encoding = System.Text.Encoding.UTF8.GetBytes("encoding");
        var _encodingV = NativeValue.From(Encoding);
        if (_encodingV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _encoding, _encodingV);
        var _offset = System.Text.Encoding.UTF8.GetBytes("offset");
        var _offsetV = NativeValue.From(Offset);
        if (_offsetV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _offset, _offsetV);
        var _length = System.Text.Encoding.UTF8.GetBytes("length");
        var _lengthV = NativeValue.From(Length);
        if (_lengthV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _length, _lengthV);
    }
}

/// <summary>
/// DfsListeners 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class DfsListeners : JsObject
{
    public DfsListeners(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _onStatus => "onStatus"u8;
    /// <summary>
    /// onStatus
    /// </summary>
    public void OnStatus(string networkId, double status)
    {
        CallMethodVoid(_onStatus, networkId, status);
    }

}

/// <summary>
/// ReadStream 实例包装（@ohos 命名空间内嵌套类）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class ReadStream : JsObject
{
    public ReadStream(IntPtr handle) : base(handle) { }

    private static ReadOnlySpan<byte> _ReadStream => "ReadStream"u8;

    public ReadStream()
        : this(NodeApi.CreateInstance(Fs.Module, _ReadStream)) { }
    private static ReadOnlySpan<byte> _bytesRead => "bytesRead"u8;
    private static ReadOnlySpan<byte> _path => "path"u8;
    private static ReadOnlySpan<byte> _seek => "seek"u8;
    private static ReadOnlySpan<byte> _close => "close"u8;
    /// <summary>
    /// bytesRead
    /// </summary>
    public double BytesRead => NativeValue.ToDouble(GetPropertyRaw(_bytesRead));

    /// <summary>
    /// path
    /// </summary>
    public string Path => NativeValue.ToString(GetPropertyRaw(_path)) ?? string.Empty;

    /// <summary>
    /// seek
    /// </summary>
    public double Seek(double offset, global::HarmonyOS.ArkUI.WhenceType? whence = null)
    {
        return CallMethod<double>(_seek, offset, whence);
    }

    /// <summary>
    /// close
    /// </summary>
    public void Close()
    {
        CallMethodVoid(_close);
    }

}

/// <summary>
/// WriteStream 实例包装（@ohos 命名空间内嵌套类）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class WriteStream : JsObject
{
    public WriteStream(IntPtr handle) : base(handle) { }

    private static ReadOnlySpan<byte> _WriteStream => "WriteStream"u8;

    public WriteStream()
        : this(NodeApi.CreateInstance(Fs.Module, _WriteStream)) { }
    private static ReadOnlySpan<byte> _bytesWritten => "bytesWritten"u8;
    private static ReadOnlySpan<byte> _path => "path"u8;
    private static ReadOnlySpan<byte> _seek => "seek"u8;
    private static ReadOnlySpan<byte> _close => "close"u8;
    /// <summary>
    /// bytesWritten
    /// </summary>
    public double BytesWritten => NativeValue.ToDouble(GetPropertyRaw(_bytesWritten));

    /// <summary>
    /// path
    /// </summary>
    public string Path => NativeValue.ToString(GetPropertyRaw(_path)) ?? string.Empty;

    /// <summary>
    /// seek
    /// </summary>
    public double Seek(double offset, global::HarmonyOS.ArkUI.WhenceType? whence = null)
    {
        return CallMethod<double>(_seek, offset, whence);
    }

    /// <summary>
    /// close
    /// </summary>
    public void Close()
    {
        CallMethodVoid(_close);
    }

}

/// <summary>
/// AtomicFile 实例包装（@ohos 命名空间内嵌套类）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class AtomicFile : JsObject
{
    public AtomicFile(IntPtr handle) : base(handle) { }

    private static ReadOnlySpan<byte> _AtomicFile => "AtomicFile"u8;

    public AtomicFile(string path)
        : this(NodeApi.CreateInstance(Fs.Module, _AtomicFile, path)) { }
    private static ReadOnlySpan<byte> _getBaseFile => "getBaseFile"u8;
    private static ReadOnlySpan<byte> _openRead => "openRead"u8;
    private static ReadOnlySpan<byte> _readFully => "readFully"u8;
    private static ReadOnlySpan<byte> _startWrite => "startWrite"u8;
    private static ReadOnlySpan<byte> _finishWrite => "finishWrite"u8;
    private static ReadOnlySpan<byte> _failWrite => "failWrite"u8;
    private static ReadOnlySpan<byte> _delete => "delete"u8;
    /// <summary>
    /// getBaseFile
    /// </summary>
    public FsFile GetBaseFile()
    {
        return CallMethod(_getBaseFile, static h => new FsFile(h));
    }

    /// <summary>
    /// openRead
    /// </summary>
    public ReadStream OpenRead()
    {
        return CallMethod(_openRead, static h => new ReadStream(h));
    }

    /// <summary>
    /// readFully
    /// </summary>
    public byte[] ReadFully()
    {
        return CallMethod(_readFully, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<byte>(e)));
    }

    /// <summary>
    /// startWrite
    /// </summary>
    public WriteStream StartWrite()
    {
        return CallMethod(_startWrite, static h => new WriteStream(h));
    }

    /// <summary>
    /// finishWrite
    /// </summary>
    public void FinishWrite()
    {
        CallMethodVoid(_finishWrite);
    }

    /// <summary>
    /// failWrite
    /// </summary>
    public void FailWrite()
    {
        CallMethodVoid(_failWrite);
    }

    /// <summary>
    /// delete
    /// </summary>
    public void Delete()
    {
        CallMethodVoid(_delete);
    }

}

/// <summary>
/// WatchEvent（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record WatchEvent(
    string FileName,
    double Event,
    double Cookie
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _fileName = System.Text.Encoding.UTF8.GetBytes("fileName");
        var _fileNameV = NativeValue.From(FileName);
        if (_fileNameV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _fileName, _fileNameV);
        var _event = System.Text.Encoding.UTF8.GetBytes("event");
        var _eventV = NativeValue.From(Event);
        if (_eventV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _event, _eventV);
        var _cookie = System.Text.Encoding.UTF8.GetBytes("cookie");
        var _cookieV = NativeValue.From(Cookie);
        if (_cookieV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _cookie, _cookieV);
    }
}

/// <summary>
/// Filter（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record FsFilter(
    string[]? Suffix = null,
    string[]? DisplayName = null,
    string[]? MimeType = null,
    double? FileSizeOver = null,
    double? LastModifiedAfter = null,
    bool? ExcludeMedia = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _suffix = System.Text.Encoding.UTF8.GetBytes("suffix");
        var _suffixV = NativeValue.From(Suffix);
        if (_suffixV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _suffix, _suffixV);
        var _displayName = System.Text.Encoding.UTF8.GetBytes("displayName");
        var _displayNameV = NativeValue.From(DisplayName);
        if (_displayNameV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _displayName, _displayNameV);
        var _mimeType = System.Text.Encoding.UTF8.GetBytes("mimeType");
        var _mimeTypeV = NativeValue.From(MimeType);
        if (_mimeTypeV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _mimeType, _mimeTypeV);
        var _fileSizeOver = System.Text.Encoding.UTF8.GetBytes("fileSizeOver");
        var _fileSizeOverV = NativeValue.From(FileSizeOver);
        if (_fileSizeOverV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _fileSizeOver, _fileSizeOverV);
        var _lastModifiedAfter = System.Text.Encoding.UTF8.GetBytes("lastModifiedAfter");
        var _lastModifiedAfterV = NativeValue.From(LastModifiedAfter);
        if (_lastModifiedAfterV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _lastModifiedAfter, _lastModifiedAfterV);
        var _excludeMedia = System.Text.Encoding.UTF8.GetBytes("excludeMedia");
        var _excludeMediaV = NativeValue.From(ExcludeMedia);
        if (_excludeMediaV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _excludeMedia, _excludeMediaV);
    }
}

/// <summary>
/// FileFilter 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class FileFilter : JsObject
{
    public FileFilter(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _filter => "filter"u8;
    /// <summary>
    /// filter
    /// </summary>
    public bool Filter(string name)
    {
        return CallMethod<bool>(_filter, name);
    }

}

/// <summary>
/// ReaderIteratorResult 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class ReaderIteratorResult : JsObject
{
    public ReaderIteratorResult(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _done => "done"u8;
    private static ReadOnlySpan<byte> _value => "value"u8;
    /// <summary>
    /// done
    /// </summary>
    public bool Done => NativeValue.ToBool(GetPropertyRaw(_done));

    /// <summary>
    /// value
    /// </summary>
    public string Value => NativeValue.ToString(GetPropertyRaw(_value)) ?? string.Empty;

}
