// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// HiAppEvent 绑定（@ohos.hiAppEvent）。
/// </summary>
public static unsafe partial class HiAppEvent
{
    private const string ModuleName = "@ohos.hiAppEvent";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[hiAppEvent] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _USER_LOGIN => "USER_LOGIN"u8;
    private static ReadOnlySpan<byte> _USER_LOGOUT => "USER_LOGOUT"u8;
    private static ReadOnlySpan<byte> _DISTRIBUTED_SERVICE_START => "DISTRIBUTED_SERVICE_START"u8;
    private static ReadOnlySpan<byte> _USER_ID => "USER_ID"u8;
    private static ReadOnlySpan<byte> _DISTRIBUTED_SERVICE_NAME => "DISTRIBUTED_SERVICE_NAME"u8;
    private static ReadOnlySpan<byte> _DISTRIBUTED_SERVICE_INSTANCE_ID => "DISTRIBUTED_SERVICE_INSTANCE_ID"u8;
    private static ReadOnlySpan<byte> _write => "write"u8;
    private static ReadOnlySpan<byte> _configure => "configure"u8;

    /// <summary>
    /// USER_LOGIN
    /// </summary>
    public static string UserLogin => NativeValue.ToString(NodeApi.GetProperty(Module, _USER_LOGIN)) ?? string.Empty;

    /// <summary>
    /// USER_LOGOUT
    /// </summary>
    public static string UserLogout => NativeValue.ToString(NodeApi.GetProperty(Module, _USER_LOGOUT)) ?? string.Empty;

    /// <summary>
    /// DISTRIBUTED_SERVICE_START
    /// </summary>
    public static string DistributedServiceStart => NativeValue.ToString(NodeApi.GetProperty(Module, _DISTRIBUTED_SERVICE_START)) ?? string.Empty;

    /// <summary>
    /// USER_ID
    /// </summary>
    public static string UserId => NativeValue.ToString(NodeApi.GetProperty(Module, _USER_ID)) ?? string.Empty;

    /// <summary>
    /// DISTRIBUTED_SERVICE_NAME
    /// </summary>
    public static string DistributedServiceName => NativeValue.ToString(NodeApi.GetProperty(Module, _DISTRIBUTED_SERVICE_NAME)) ?? string.Empty;

    /// <summary>
    /// DISTRIBUTED_SERVICE_INSTANCE_ID
    /// </summary>
    public static string DistributedServiceInstanceId => NativeValue.ToString(NodeApi.GetProperty(Module, _DISTRIBUTED_SERVICE_INSTANCE_ID)) ?? string.Empty;

    /// <summary>
    /// write
    /// </summary>
    public static Task WriteAsync(string eventName, global::HarmonyOS.ArkUI.EventType eventType, IntPtr keyValues)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _write, eventName, eventType, keyValues);
    }

    /// <summary>
    /// configure
    /// </summary>
    public static bool Configure(ConfigOption config)
    {
        return NodeApi.CallMethod<bool>(Module, _configure, config);
    }

}

/// <summary>
/// ConfigOption（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record ConfigOption(
    bool? Disable = null,
    string? MaxStorage = null
) : INapiRecord
{
    private static ReadOnlySpan<byte> _disableName => "disable"u8;
    private static ReadOnlySpan<byte> _maxStorageName => "maxStorage"u8;
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _disableV = NativeValue.From(Disable);
        if (_disableV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _disableName, _disableV);
        var _maxStorageV = NativeValue.From(MaxStorage);
        if (_maxStorageV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _maxStorageName, _maxStorageV);
    }
}
