// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// HiRetrieval 绑定（@ohos.hiviewdfx.hiRetrieval）。
/// </summary>
public static unsafe partial class HiRetrieval
{
    private const string ModuleName = "@ohos.hiviewdfx.hiRetrieval";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[hiviewdfx.hiRetrieval] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _init => "init"u8;
    private static ReadOnlySpan<byte> _participate => "participate"u8;
    private static ReadOnlySpan<byte> _quit => "quit"u8;
    private static ReadOnlySpan<byte> _isParticipant => "isParticipant"u8;
    private static ReadOnlySpan<byte> _getLastParticipationTimestamp => "getLastParticipationTimestamp"u8;
    private static ReadOnlySpan<byte> _run => "run"u8;
    private static ReadOnlySpan<byte> _getCurrentConfig => "getCurrentConfig"u8;

    /// <summary>
    /// init
    /// </summary>
    public static void Init()
    {
        NodeApi.CallMethodVoid(Module, _init);
    }

    /// <summary>
    /// participate
    /// </summary>
    public static void Participate(HiRetrievalConfig config)
    {
        NodeApi.CallMethodVoid(Module, _participate, config);
    }

    /// <summary>
    /// quit
    /// </summary>
    public static void Quit()
    {
        NodeApi.CallMethodVoid(Module, _quit);
    }

    /// <summary>
    /// isParticipant
    /// </summary>
    public static bool IsParticipant()
    {
        return NodeApi.CallMethod<bool>(Module, _isParticipant);
    }

    /// <summary>
    /// getLastParticipationTimestamp
    /// </summary>
    public static double GetLastParticipationTimestamp()
    {
        return NodeApi.CallMethod<double>(Module, _getLastParticipationTimestamp);
    }

    /// <summary>
    /// run
    /// </summary>
    public static void Run()
    {
        NodeApi.CallMethodVoid(Module, _run);
    }

    /// <summary>
    /// getCurrentConfig
    /// </summary>
    public static HiRetrievalConfig GetCurrentConfig()
    {
        return NodeApi.CallMethod(Module, _getCurrentConfig, static h => new HiRetrievalConfig(h));
    }

}

/// <summary>
/// HiRetrievalConfig 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class HiRetrievalConfig : JsObject
{
    public HiRetrievalConfig(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _userType => "userType"u8;
    private static ReadOnlySpan<byte> _deviceType => "deviceType"u8;
    private static ReadOnlySpan<byte> _deviceModel => "deviceModel"u8;
    /// <summary>
    /// userType
    /// </summary>
    public string UserType => NativeValue.ToString(GetPropertyRaw(_userType)) ?? string.Empty;

    /// <summary>
    /// deviceType
    /// </summary>
    public string DeviceType => NativeValue.ToString(GetPropertyRaw(_deviceType)) ?? string.Empty;

    /// <summary>
    /// deviceModel
    /// </summary>
    public string DeviceModel => NativeValue.ToString(GetPropertyRaw(_deviceModel)) ?? string.Empty;

}
