// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// InputMethodEngine 绑定（@ohos.inputMethodEngine）。
/// 所需权限：ohos.permission.PRIVACY_WINDOW
/// </summary>
public static unsafe partial class InputMethodEngine
{
    private const string ModuleName = "@ohos.inputMethodEngine";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[inputMethodEngine] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _ENTER_KEY_TYPE_UNSPECIFIED => "ENTER_KEY_TYPE_UNSPECIFIED"u8;
    private static ReadOnlySpan<byte> _ENTER_KEY_TYPE_GO => "ENTER_KEY_TYPE_GO"u8;
    private static ReadOnlySpan<byte> _ENTER_KEY_TYPE_SEARCH => "ENTER_KEY_TYPE_SEARCH"u8;
    private static ReadOnlySpan<byte> _ENTER_KEY_TYPE_SEND => "ENTER_KEY_TYPE_SEND"u8;
    private static ReadOnlySpan<byte> _ENTER_KEY_TYPE_NEXT => "ENTER_KEY_TYPE_NEXT"u8;
    private static ReadOnlySpan<byte> _ENTER_KEY_TYPE_DONE => "ENTER_KEY_TYPE_DONE"u8;
    private static ReadOnlySpan<byte> _ENTER_KEY_TYPE_PREVIOUS => "ENTER_KEY_TYPE_PREVIOUS"u8;
    private static ReadOnlySpan<byte> _ENTER_KEY_TYPE_NEWLINE => "ENTER_KEY_TYPE_NEWLINE"u8;
    private static ReadOnlySpan<byte> _PATTERN_NULL => "PATTERN_NULL"u8;
    private static ReadOnlySpan<byte> _PATTERN_TEXT => "PATTERN_TEXT"u8;
    private static ReadOnlySpan<byte> _PATTERN_NUMBER => "PATTERN_NUMBER"u8;
    private static ReadOnlySpan<byte> _PATTERN_PHONE => "PATTERN_PHONE"u8;
    private static ReadOnlySpan<byte> _PATTERN_DATETIME => "PATTERN_DATETIME"u8;
    private static ReadOnlySpan<byte> _PATTERN_EMAIL => "PATTERN_EMAIL"u8;
    private static ReadOnlySpan<byte> _PATTERN_URI => "PATTERN_URI"u8;
    private static ReadOnlySpan<byte> _PATTERN_PASSWORD => "PATTERN_PASSWORD"u8;
    private static ReadOnlySpan<byte> _PATTERN_PASSWORD_SCREEN_LOCK => "PATTERN_PASSWORD_SCREEN_LOCK"u8;
    private static ReadOnlySpan<byte> _PATTERN_PASSWORD_NUMBER => "PATTERN_PASSWORD_NUMBER"u8;
    private static ReadOnlySpan<byte> _PATTERN_USER_NAME => "PATTERN_USER_NAME"u8;
    private static ReadOnlySpan<byte> _PATTERN_NEW_PASSWORD => "PATTERN_NEW_PASSWORD"u8;
    private static ReadOnlySpan<byte> _PATTERN_NUMBER_DECIMAL => "PATTERN_NUMBER_DECIMAL"u8;
    private static ReadOnlySpan<byte> _PATTERN_ONE_TIME_CODE => "PATTERN_ONE_TIME_CODE"u8;
    private static ReadOnlySpan<byte> _FLAG_SELECTING => "FLAG_SELECTING"u8;
    private static ReadOnlySpan<byte> _FLAG_SINGLE_LINE => "FLAG_SINGLE_LINE"u8;
    private static ReadOnlySpan<byte> _DISPLAY_MODE_PART => "DISPLAY_MODE_PART"u8;
    private static ReadOnlySpan<byte> _DISPLAY_MODE_FULL => "DISPLAY_MODE_FULL"u8;
    private static ReadOnlySpan<byte> _OPTION_ASCII => "OPTION_ASCII"u8;
    private static ReadOnlySpan<byte> _OPTION_NONE => "OPTION_NONE"u8;
    private static ReadOnlySpan<byte> _OPTION_AUTO_CAP_CHARACTERS => "OPTION_AUTO_CAP_CHARACTERS"u8;
    private static ReadOnlySpan<byte> _OPTION_AUTO_CAP_SENTENCES => "OPTION_AUTO_CAP_SENTENCES"u8;
    private static ReadOnlySpan<byte> _OPTION_AUTO_WORDS => "OPTION_AUTO_WORDS"u8;
    private static ReadOnlySpan<byte> _OPTION_MULTI_LINE => "OPTION_MULTI_LINE"u8;
    private static ReadOnlySpan<byte> _OPTION_NO_FULLSCREEN => "OPTION_NO_FULLSCREEN"u8;
    private static ReadOnlySpan<byte> _CURSOR_UP => "CURSOR_UP"u8;
    private static ReadOnlySpan<byte> _CURSOR_DOWN => "CURSOR_DOWN"u8;
    private static ReadOnlySpan<byte> _CURSOR_LEFT => "CURSOR_LEFT"u8;
    private static ReadOnlySpan<byte> _CURSOR_RIGHT => "CURSOR_RIGHT"u8;
    private static ReadOnlySpan<byte> _WINDOW_TYPE_INPUT_METHOD_FLOAT => "WINDOW_TYPE_INPUT_METHOD_FLOAT"u8;
    private static ReadOnlySpan<byte> _getInputMethodAbility => "getInputMethodAbility"u8;
    private static ReadOnlySpan<byte> _getInputMethodEngine => "getInputMethodEngine"u8;
    private static ReadOnlySpan<byte> _getKeyboardDelegate => "getKeyboardDelegate"u8;
    private static ReadOnlySpan<byte> _createKeyboardDelegate => "createKeyboardDelegate"u8;

    /// <summary>
    /// ENTER_KEY_TYPE_UNSPECIFIED
    /// </summary>
    public static double EnterKeyTypeUnspecified => NativeValue.ToDouble(NodeApi.GetProperty(Module, _ENTER_KEY_TYPE_UNSPECIFIED));

    /// <summary>
    /// ENTER_KEY_TYPE_GO
    /// </summary>
    public static double EnterKeyTypeGo => NativeValue.ToDouble(NodeApi.GetProperty(Module, _ENTER_KEY_TYPE_GO));

    /// <summary>
    /// ENTER_KEY_TYPE_SEARCH
    /// </summary>
    public static double EnterKeyTypeSearch => NativeValue.ToDouble(NodeApi.GetProperty(Module, _ENTER_KEY_TYPE_SEARCH));

    /// <summary>
    /// ENTER_KEY_TYPE_SEND
    /// </summary>
    public static double EnterKeyTypeSend => NativeValue.ToDouble(NodeApi.GetProperty(Module, _ENTER_KEY_TYPE_SEND));

    /// <summary>
    /// ENTER_KEY_TYPE_NEXT
    /// </summary>
    public static double EnterKeyTypeNext => NativeValue.ToDouble(NodeApi.GetProperty(Module, _ENTER_KEY_TYPE_NEXT));

    /// <summary>
    /// ENTER_KEY_TYPE_DONE
    /// </summary>
    public static double EnterKeyTypeDone => NativeValue.ToDouble(NodeApi.GetProperty(Module, _ENTER_KEY_TYPE_DONE));

    /// <summary>
    /// ENTER_KEY_TYPE_PREVIOUS
    /// </summary>
    public static double EnterKeyTypePrevious => NativeValue.ToDouble(NodeApi.GetProperty(Module, _ENTER_KEY_TYPE_PREVIOUS));

    /// <summary>
    /// ENTER_KEY_TYPE_NEWLINE
    /// </summary>
    public static double EnterKeyTypeNewline => NativeValue.ToDouble(NodeApi.GetProperty(Module, _ENTER_KEY_TYPE_NEWLINE));

    /// <summary>
    /// PATTERN_NULL
    /// </summary>
    public static double PatternNull => NativeValue.ToDouble(NodeApi.GetProperty(Module, _PATTERN_NULL));

    /// <summary>
    /// PATTERN_TEXT
    /// </summary>
    public static double PatternText => NativeValue.ToDouble(NodeApi.GetProperty(Module, _PATTERN_TEXT));

    /// <summary>
    /// PATTERN_NUMBER
    /// </summary>
    public static double PatternNumber => NativeValue.ToDouble(NodeApi.GetProperty(Module, _PATTERN_NUMBER));

    /// <summary>
    /// PATTERN_PHONE
    /// </summary>
    public static double PatternPhone => NativeValue.ToDouble(NodeApi.GetProperty(Module, _PATTERN_PHONE));

    /// <summary>
    /// PATTERN_DATETIME
    /// </summary>
    public static double PatternDatetime => NativeValue.ToDouble(NodeApi.GetProperty(Module, _PATTERN_DATETIME));

    /// <summary>
    /// PATTERN_EMAIL
    /// </summary>
    public static double PatternEmail => NativeValue.ToDouble(NodeApi.GetProperty(Module, _PATTERN_EMAIL));

    /// <summary>
    /// PATTERN_URI
    /// </summary>
    public static double PatternUri => NativeValue.ToDouble(NodeApi.GetProperty(Module, _PATTERN_URI));

    /// <summary>
    /// PATTERN_PASSWORD
    /// </summary>
    public static double PatternPassword => NativeValue.ToDouble(NodeApi.GetProperty(Module, _PATTERN_PASSWORD));

    /// <summary>
    /// PATTERN_PASSWORD_SCREEN_LOCK
    /// </summary>
    public static double PatternPasswordScreenLock => NativeValue.ToDouble(NodeApi.GetProperty(Module, _PATTERN_PASSWORD_SCREEN_LOCK));

    /// <summary>
    /// PATTERN_PASSWORD_NUMBER
    /// </summary>
    public static double PatternPasswordNumber => NativeValue.ToDouble(NodeApi.GetProperty(Module, _PATTERN_PASSWORD_NUMBER));

    /// <summary>
    /// PATTERN_USER_NAME
    /// </summary>
    public static double PatternUserName => NativeValue.ToDouble(NodeApi.GetProperty(Module, _PATTERN_USER_NAME));

    /// <summary>
    /// PATTERN_NEW_PASSWORD
    /// </summary>
    public static double PatternNewPassword => NativeValue.ToDouble(NodeApi.GetProperty(Module, _PATTERN_NEW_PASSWORD));

    /// <summary>
    /// PATTERN_NUMBER_DECIMAL
    /// </summary>
    public static double PatternNumberDecimal => NativeValue.ToDouble(NodeApi.GetProperty(Module, _PATTERN_NUMBER_DECIMAL));

    /// <summary>
    /// PATTERN_ONE_TIME_CODE
    /// </summary>
    public static double PatternOneTimeCode => NativeValue.ToDouble(NodeApi.GetProperty(Module, _PATTERN_ONE_TIME_CODE));

    /// <summary>
    /// FLAG_SELECTING
    /// </summary>
    public static double FlagSelecting => NativeValue.ToDouble(NodeApi.GetProperty(Module, _FLAG_SELECTING));

    /// <summary>
    /// FLAG_SINGLE_LINE
    /// </summary>
    public static double FlagSingleLine => NativeValue.ToDouble(NodeApi.GetProperty(Module, _FLAG_SINGLE_LINE));

    /// <summary>
    /// DISPLAY_MODE_PART
    /// </summary>
    public static double DisplayModePart => NativeValue.ToDouble(NodeApi.GetProperty(Module, _DISPLAY_MODE_PART));

    /// <summary>
    /// DISPLAY_MODE_FULL
    /// </summary>
    public static double DisplayModeFull => NativeValue.ToDouble(NodeApi.GetProperty(Module, _DISPLAY_MODE_FULL));

    /// <summary>
    /// OPTION_ASCII
    /// </summary>
    public static double OptionAscii => NativeValue.ToDouble(NodeApi.GetProperty(Module, _OPTION_ASCII));

    /// <summary>
    /// OPTION_NONE
    /// </summary>
    public static double OptionNone => NativeValue.ToDouble(NodeApi.GetProperty(Module, _OPTION_NONE));

    /// <summary>
    /// OPTION_AUTO_CAP_CHARACTERS
    /// </summary>
    public static double OptionAutoCapCharacters => NativeValue.ToDouble(NodeApi.GetProperty(Module, _OPTION_AUTO_CAP_CHARACTERS));

    /// <summary>
    /// OPTION_AUTO_CAP_SENTENCES
    /// </summary>
    public static double OptionAutoCapSentences => NativeValue.ToDouble(NodeApi.GetProperty(Module, _OPTION_AUTO_CAP_SENTENCES));

    /// <summary>
    /// OPTION_AUTO_WORDS
    /// </summary>
    public static double OptionAutoWords => NativeValue.ToDouble(NodeApi.GetProperty(Module, _OPTION_AUTO_WORDS));

    /// <summary>
    /// OPTION_MULTI_LINE
    /// </summary>
    public static double OptionMultiLine => NativeValue.ToDouble(NodeApi.GetProperty(Module, _OPTION_MULTI_LINE));

    /// <summary>
    /// OPTION_NO_FULLSCREEN
    /// </summary>
    public static double OptionNoFullscreen => NativeValue.ToDouble(NodeApi.GetProperty(Module, _OPTION_NO_FULLSCREEN));

    /// <summary>
    /// CURSOR_UP
    /// </summary>
    public static double CursorUp => NativeValue.ToDouble(NodeApi.GetProperty(Module, _CURSOR_UP));

    /// <summary>
    /// CURSOR_DOWN
    /// </summary>
    public static double CursorDown => NativeValue.ToDouble(NodeApi.GetProperty(Module, _CURSOR_DOWN));

    /// <summary>
    /// CURSOR_LEFT
    /// </summary>
    public static double CursorLeft => NativeValue.ToDouble(NodeApi.GetProperty(Module, _CURSOR_LEFT));

    /// <summary>
    /// CURSOR_RIGHT
    /// </summary>
    public static double CursorRight => NativeValue.ToDouble(NodeApi.GetProperty(Module, _CURSOR_RIGHT));

    /// <summary>
    /// WINDOW_TYPE_INPUT_METHOD_FLOAT
    /// </summary>
    public static double WindowTypeInputMethodFloat => NativeValue.ToDouble(NodeApi.GetProperty(Module, _WINDOW_TYPE_INPUT_METHOD_FLOAT));

    /// <summary>
    /// getInputMethodAbility
    /// </summary>
    public static InputMethodAbility GetInputMethodAbility()
    {
        return NodeApi.CallMethod(Module, _getInputMethodAbility, static h => new InputMethodAbility(h));
    }

    /// <summary>
    /// getInputMethodEngine
    /// </summary>
    public static InputMethodEngineObject GetInputMethodEngine()
    {
        return NodeApi.CallMethod(Module, _getInputMethodEngine, static h => new InputMethodEngineObject(h));
    }

    /// <summary>
    /// getKeyboardDelegate
    /// </summary>
    public static KeyboardDelegate GetKeyboardDelegate()
    {
        return NodeApi.CallMethod(Module, _getKeyboardDelegate, static h => new KeyboardDelegate(h));
    }

    /// <summary>
    /// createKeyboardDelegate
    /// </summary>
    public static KeyboardDelegate CreateKeyboardDelegate()
    {
        return NodeApi.CallMethod(Module, _createKeyboardDelegate, static h => new KeyboardDelegate(h));
    }

}

/// <summary>
/// InputMethodAbility 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class InputMethodAbility : JsObject
{
    public InputMethodAbility(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    private static ReadOnlySpan<byte> _getSecurityMode => "getSecurityMode"u8;
    private static ReadOnlySpan<byte> _createPanel => "createPanel"u8;
    private static ReadOnlySpan<byte> _destroyPanel => "destroyPanel"u8;
    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    /// <summary>
    /// getSecurityMode
    /// </summary>
    public global::HarmonyOS.ArkUI.SecurityMode GetSecurityMode()
    {
        return CallMethod<global::HarmonyOS.ArkUI.SecurityMode>(_getSecurityMode);
    }

    /// <summary>
    /// createPanel
    /// </summary>
    public Task<PanelObject> CreatePanelAsync(IntPtr ctx, IntPtr info)
    {
        return CallMethodAsync(_createPanel, static h => new PanelObject(h), ctx, info);
    }

    /// <summary>
    /// destroyPanel
    /// </summary>
    public Task DestroyPanelAsync(PanelObject panel)
    {
        return CallMethodAsyncVoid(_destroyPanel, panel);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action<global::HarmonyOS.ArkUI.SecurityMode> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback((global::HarmonyOS.ArkUI.SecurityMode)NativeValue.ToInt(args[0])),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action<global::HarmonyOS.ArkUI.SecurityMode> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action<IntPtr> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(args[0]),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action<IntPtr> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action<double> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(NativeValue.ToDouble(args[0])),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action<double> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 inputStart 事件（对应 on/off）
    /// </summary>
    public event System.Action InputStart
    {
        add
        {
            _eventListeners.Add(("inputStart", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "inputStart", js));
        }
        remove
        {
            _eventListeners.Remove(("inputStart", value), js => NodeApi.CallMethodVoid(Handle, _off, "inputStart", js));
        }
    }

    /// <summary>
    /// 监听 inputStop 事件（对应 on/off）
    /// </summary>
    public event System.Action InputStop
    {
        add
        {
            _eventListeners.Add(("inputStop", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "inputStop", js));
        }
        remove
        {
            _eventListeners.Remove(("inputStop", value), js => NodeApi.CallMethodVoid(Handle, _off, "inputStop", js));
        }
    }

    /// <summary>
    /// 监听 setCallingWindow 事件（对应 on/off）
    /// </summary>
    public event System.Action SetCallingWindow
    {
        add
        {
            _eventListeners.Add(("setCallingWindow", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "setCallingWindow", js));
        }
        remove
        {
            _eventListeners.Remove(("setCallingWindow", value), js => NodeApi.CallMethodVoid(Handle, _off, "setCallingWindow", js));
        }
    }

    /// <summary>
    /// 监听 keyboardShow 事件（对应 on/off）
    /// </summary>
    public event System.Action KeyboardShow
    {
        add
        {
            _eventListeners.Add(("keyboardShow", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "keyboardShow", js));
        }
        remove
        {
            _eventListeners.Remove(("keyboardShow", value), js => NodeApi.CallMethodVoid(Handle, _off, "keyboardShow", js));
        }
    }

    /// <summary>
    /// 监听 keyboardHide 事件（对应 on/off）
    /// </summary>
    public event System.Action KeyboardHide
    {
        add
        {
            _eventListeners.Add(("keyboardHide", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "keyboardHide", js));
        }
        remove
        {
            _eventListeners.Remove(("keyboardHide", value), js => NodeApi.CallMethodVoid(Handle, _off, "keyboardHide", js));
        }
    }

    /// <summary>
    /// 监听 setSubtype 事件（对应 on/off）
    /// </summary>
    public event System.Action SetSubtype
    {
        add
        {
            _eventListeners.Add(("setSubtype", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "setSubtype", js));
        }
        remove
        {
            _eventListeners.Remove(("setSubtype", value), js => NodeApi.CallMethodVoid(Handle, _off, "setSubtype", js));
        }
    }

    /// <summary>
    /// 监听 securityModeChange 事件（对应 on/off）
    /// </summary>
    public event System.Action<global::HarmonyOS.ArkUI.SecurityMode> SecurityModeChange
    {
        add
        {
            _eventListeners.Add(("securityModeChange", value),
                args => value((global::HarmonyOS.ArkUI.SecurityMode)NativeValue.ToInt(args[0])),
                js => NodeApi.CallMethodVoid(Handle, _on, "securityModeChange", js));
        }
        remove
        {
            _eventListeners.Remove(("securityModeChange", value), js => NodeApi.CallMethodVoid(Handle, _off, "securityModeChange", js));
        }
    }

    /// <summary>
    /// 监听 privateCommand 事件（对应 on/off）
    /// </summary>
    public event System.Action<IntPtr> PrivateCommand
    {
        add
        {
            _eventListeners.Add(("privateCommand", value),
                args => value(args[0]),
                js => NodeApi.CallMethodVoid(Handle, _on, "privateCommand", js));
        }
        remove
        {
            _eventListeners.Remove(("privateCommand", value), js => NodeApi.CallMethodVoid(Handle, _off, "privateCommand", js));
        }
    }

    /// <summary>
    /// 监听 callingDisplayDidChange 事件（对应 on/off）
    /// </summary>
    public event System.Action<double> CallingDisplayDidChange
    {
        add
        {
            _eventListeners.Add(("callingDisplayDidChange", value),
                args => value(NativeValue.ToDouble(args[0])),
                js => NodeApi.CallMethodVoid(Handle, _on, "callingDisplayDidChange", js));
        }
        remove
        {
            _eventListeners.Remove(("callingDisplayDidChange", value), js => NodeApi.CallMethodVoid(Handle, _off, "callingDisplayDidChange", js));
        }
    }

    /// <summary>
    /// 监听 discardTypingText 事件（对应 on/off）
    /// </summary>
    public event System.Action DiscardTypingText
    {
        add
        {
            _eventListeners.Add(("discardTypingText", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "discardTypingText", js));
        }
        remove
        {
            _eventListeners.Remove(("discardTypingText", value), js => NodeApi.CallMethodVoid(Handle, _off, "discardTypingText", js));
        }
    }

}

/// <summary>
/// InputMethodEngine 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class InputMethodEngineObject : JsObject
{
    public InputMethodEngineObject(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 inputStart 事件（对应 on/off）
    /// </summary>
    public event System.Action InputStart
    {
        add
        {
            _eventListeners.Add(("inputStart", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "inputStart", js));
        }
        remove
        {
            _eventListeners.Remove(("inputStart", value), js => NodeApi.CallMethodVoid(Handle, _off, "inputStart", js));
        }
    }

    /// <summary>
    /// 监听 keyboardShow 事件（对应 on/off）
    /// </summary>
    public event System.Action KeyboardShow
    {
        add
        {
            _eventListeners.Add(("keyboardShow", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "keyboardShow", js));
        }
        remove
        {
            _eventListeners.Remove(("keyboardShow", value), js => NodeApi.CallMethodVoid(Handle, _off, "keyboardShow", js));
        }
    }

    /// <summary>
    /// 监听 keyboardHide 事件（对应 on/off）
    /// </summary>
    public event System.Action KeyboardHide
    {
        add
        {
            _eventListeners.Add(("keyboardHide", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "keyboardHide", js));
        }
        remove
        {
            _eventListeners.Remove(("keyboardHide", value), js => NodeApi.CallMethodVoid(Handle, _off, "keyboardHide", js));
        }
    }

}

/// <summary>
/// KeyboardDelegate 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class KeyboardDelegate : JsObject
{
    public KeyboardDelegate(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 keyDown 事件（对应 on/off）
    /// </summary>
    public event System.Action KeyDown
    {
        add
        {
            _eventListeners.Add(("keyDown", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "keyDown", js));
        }
        remove
        {
            _eventListeners.Remove(("keyDown", value), js => NodeApi.CallMethodVoid(Handle, _off, "keyDown", js));
        }
    }

    /// <summary>
    /// 监听 keyUp 事件（对应 on/off）
    /// </summary>
    public event System.Action KeyUp
    {
        add
        {
            _eventListeners.Add(("keyUp", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "keyUp", js));
        }
        remove
        {
            _eventListeners.Remove(("keyUp", value), js => NodeApi.CallMethodVoid(Handle, _off, "keyUp", js));
        }
    }

    /// <summary>
    /// 监听 keyEvent 事件（对应 on/off）
    /// </summary>
    public event System.Action KeyEvent
    {
        add
        {
            _eventListeners.Add(("keyEvent", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "keyEvent", js));
        }
        remove
        {
            _eventListeners.Remove(("keyEvent", value), js => NodeApi.CallMethodVoid(Handle, _off, "keyEvent", js));
        }
    }

    /// <summary>
    /// 监听 cursorContextChange 事件（对应 on/off）
    /// </summary>
    public event System.Action CursorContextChange
    {
        add
        {
            _eventListeners.Add(("cursorContextChange", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "cursorContextChange", js));
        }
        remove
        {
            _eventListeners.Remove(("cursorContextChange", value), js => NodeApi.CallMethodVoid(Handle, _off, "cursorContextChange", js));
        }
    }

    /// <summary>
    /// 监听 selectionChange 事件（对应 on/off）
    /// </summary>
    public event System.Action SelectionChange
    {
        add
        {
            _eventListeners.Add(("selectionChange", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "selectionChange", js));
        }
        remove
        {
            _eventListeners.Remove(("selectionChange", value), js => NodeApi.CallMethodVoid(Handle, _off, "selectionChange", js));
        }
    }

    /// <summary>
    /// 监听 textChange 事件（对应 on/off）
    /// </summary>
    public event System.Action TextChange
    {
        add
        {
            _eventListeners.Add(("textChange", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "textChange", js));
        }
        remove
        {
            _eventListeners.Remove(("textChange", value), js => NodeApi.CallMethodVoid(Handle, _off, "textChange", js));
        }
    }

    /// <summary>
    /// 监听 editorAttributeChanged 事件（对应 on/off）
    /// </summary>
    public event System.Action EditorAttributeChanged
    {
        add
        {
            _eventListeners.Add(("editorAttributeChanged", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "editorAttributeChanged", js));
        }
        remove
        {
            _eventListeners.Remove(("editorAttributeChanged", value), js => NodeApi.CallMethodVoid(Handle, _off, "editorAttributeChanged", js));
        }
    }

}

/// <summary>
/// KeyboardController 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class KeyboardController : JsObject
{
    public KeyboardController(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _hide => "hide"u8;
    private static ReadOnlySpan<byte> _hideKeyboard => "hideKeyboard"u8;
    private static ReadOnlySpan<byte> _exitCurrentInputType => "exitCurrentInputType"u8;
    /// <summary>
    /// hide
    /// </summary>
    public Task HideAsync()
    {
        return CallMethodAsyncVoid(_hide);
    }

    /// <summary>
    /// hideKeyboard
    /// </summary>
    public Task HideKeyboardAsync()
    {
        return CallMethodAsyncVoid(_hideKeyboard);
    }

    /// <summary>
    /// exitCurrentInputType
    /// </summary>
    public Task ExitCurrentInputTypeAsync()
    {
        return CallMethodAsyncVoid(_exitCurrentInputType);
    }

}

/// <summary>
/// InputClient 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class InputClient : JsObject
{
    public InputClient(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _sendKeyFunction => "sendKeyFunction"u8;
    private static ReadOnlySpan<byte> _deleteForward => "deleteForward"u8;
    private static ReadOnlySpan<byte> _deleteForwardSync => "deleteForwardSync"u8;
    private static ReadOnlySpan<byte> _deleteBackward => "deleteBackward"u8;
    private static ReadOnlySpan<byte> _deleteBackwardSync => "deleteBackwardSync"u8;
    private static ReadOnlySpan<byte> _insertText => "insertText"u8;
    private static ReadOnlySpan<byte> _insertTextSync => "insertTextSync"u8;
    private static ReadOnlySpan<byte> _getForward => "getForward"u8;
    private static ReadOnlySpan<byte> _getForwardSync => "getForwardSync"u8;
    private static ReadOnlySpan<byte> _getBackward => "getBackward"u8;
    private static ReadOnlySpan<byte> _getBackwardSync => "getBackwardSync"u8;
    private static ReadOnlySpan<byte> _getEditorAttribute => "getEditorAttribute"u8;
    private static ReadOnlySpan<byte> _getEditorAttributeSync => "getEditorAttributeSync"u8;
    private static ReadOnlySpan<byte> _moveCursor => "moveCursor"u8;
    private static ReadOnlySpan<byte> _moveCursorSync => "moveCursorSync"u8;
    private static ReadOnlySpan<byte> _selectByRange => "selectByRange"u8;
    private static ReadOnlySpan<byte> _selectByRangeSync => "selectByRangeSync"u8;
    private static ReadOnlySpan<byte> _selectByMovement => "selectByMovement"u8;
    private static ReadOnlySpan<byte> _selectByMovementSync => "selectByMovementSync"u8;
    private static ReadOnlySpan<byte> _getTextIndexAtCursor => "getTextIndexAtCursor"u8;
    private static ReadOnlySpan<byte> _getTextIndexAtCursorSync => "getTextIndexAtCursorSync"u8;
    private static ReadOnlySpan<byte> _sendExtendAction => "sendExtendAction"u8;
    private static ReadOnlySpan<byte> _sendPrivateCommand => "sendPrivateCommand"u8;
    private static ReadOnlySpan<byte> _getCallingWindowInfo => "getCallingWindowInfo"u8;
    private static ReadOnlySpan<byte> _setPreviewText => "setPreviewText"u8;
    private static ReadOnlySpan<byte> _setPreviewTextSync => "setPreviewTextSync"u8;
    private static ReadOnlySpan<byte> _finishTextPreview => "finishTextPreview"u8;
    private static ReadOnlySpan<byte> _finishTextPreviewSync => "finishTextPreviewSync"u8;
    private static ReadOnlySpan<byte> _sendMessage => "sendMessage"u8;
    private static ReadOnlySpan<byte> _recvMessage => "recvMessage"u8;
    private static ReadOnlySpan<byte> _getAttachOptions => "getAttachOptions"u8;
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    /// <summary>
    /// sendKeyFunction
    /// </summary>
    public Task<bool> SendKeyFunctionAsync(double action)
    {
        return CallMethodAsync<bool>(_sendKeyFunction, action);
    }

    /// <summary>
    /// deleteForward
    /// </summary>
    public Task<bool> DeleteForwardAsync(double length)
    {
        return CallMethodAsync<bool>(_deleteForward, length);
    }

    /// <summary>
    /// deleteForwardSync
    /// </summary>
    public void DeleteForwardSync(double length)
    {
        CallMethodVoid(_deleteForwardSync, length);
    }

    /// <summary>
    /// deleteBackward
    /// </summary>
    public Task<bool> DeleteBackwardAsync(double length)
    {
        return CallMethodAsync<bool>(_deleteBackward, length);
    }

    /// <summary>
    /// deleteBackwardSync
    /// </summary>
    public void DeleteBackwardSync(double length)
    {
        CallMethodVoid(_deleteBackwardSync, length);
    }

    /// <summary>
    /// insertText
    /// </summary>
    public Task<bool> InsertTextAsync(string text)
    {
        return CallMethodAsync<bool>(_insertText, text);
    }

    /// <summary>
    /// insertTextSync
    /// </summary>
    public void InsertTextSync(string text)
    {
        CallMethodVoid(_insertTextSync, text);
    }

    /// <summary>
    /// getForward
    /// </summary>
    public Task<string> GetForwardAsync(double length)
    {
        return CallMethodAsync<string>(_getForward, length);
    }

    /// <summary>
    /// getForwardSync
    /// </summary>
    public string GetForwardSync(double length)
    {
        return CallMethod<string>(_getForwardSync, length);
    }

    /// <summary>
    /// getBackward
    /// </summary>
    public Task<string> GetBackwardAsync(double length)
    {
        return CallMethodAsync<string>(_getBackward, length);
    }

    /// <summary>
    /// getBackwardSync
    /// </summary>
    public string GetBackwardSync(double length)
    {
        return CallMethod<string>(_getBackwardSync, length);
    }

    /// <summary>
    /// getEditorAttribute
    /// </summary>
    public Task<IntPtr> GetEditorAttributeAsync()
    {
        return CallMethodAsync<IntPtr>(_getEditorAttribute);
    }

    /// <summary>
    /// getEditorAttributeSync
    /// </summary>
    public IntPtr GetEditorAttributeSync()
    {
        return CallMethod<IntPtr>(_getEditorAttributeSync);
    }

    /// <summary>
    /// moveCursor
    /// </summary>
    public Task MoveCursorAsync(double direction)
    {
        return CallMethodAsyncVoid(_moveCursor, direction);
    }

    /// <summary>
    /// moveCursorSync
    /// </summary>
    public void MoveCursorSync(double direction)
    {
        CallMethodVoid(_moveCursorSync, direction);
    }

    /// <summary>
    /// selectByRange
    /// </summary>
    public Task SelectByRangeAsync(InputMethodEngineRange range)
    {
        return CallMethodAsyncVoid(_selectByRange, range);
    }

    /// <summary>
    /// selectByRangeSync
    /// </summary>
    public void SelectByRangeSync(InputMethodEngineRange range)
    {
        CallMethodVoid(_selectByRangeSync, range);
    }

    /// <summary>
    /// selectByMovement
    /// </summary>
    public Task SelectByMovementAsync(IntPtr movement)
    {
        return CallMethodAsyncVoid(_selectByMovement, movement);
    }

    /// <summary>
    /// selectByMovementSync
    /// </summary>
    public void SelectByMovementSync(IntPtr movement)
    {
        CallMethodVoid(_selectByMovementSync, movement);
    }

    /// <summary>
    /// getTextIndexAtCursor
    /// </summary>
    public Task<double> GetTextIndexAtCursorAsync()
    {
        return CallMethodAsync<double>(_getTextIndexAtCursor);
    }

    /// <summary>
    /// getTextIndexAtCursorSync
    /// </summary>
    public double GetTextIndexAtCursorSync()
    {
        return CallMethod<double>(_getTextIndexAtCursorSync);
    }

    /// <summary>
    /// sendExtendAction
    /// </summary>
    public Task SendExtendActionAsync(global::HarmonyOS.ArkUI.ExtendAction action)
    {
        return CallMethodAsyncVoid(_sendExtendAction, action);
    }

    /// <summary>
    /// sendPrivateCommand
    /// </summary>
    public Task SendPrivateCommandAsync(IntPtr commandData)
    {
        return CallMethodAsyncVoid(_sendPrivateCommand, commandData);
    }

    /// <summary>
    /// getCallingWindowInfo
    /// </summary>
    public Task<IntPtr> GetCallingWindowInfoAsync()
    {
        return CallMethodAsync<IntPtr>(_getCallingWindowInfo);
    }

    /// <summary>
    /// setPreviewText
    /// </summary>
    public Task SetPreviewTextAsync(string text, InputMethodEngineRange range)
    {
        return CallMethodAsyncVoid(_setPreviewText, text, range);
    }

    /// <summary>
    /// setPreviewTextSync
    /// </summary>
    public void SetPreviewTextSync(string text, InputMethodEngineRange range)
    {
        CallMethodVoid(_setPreviewTextSync, text, range);
    }

    /// <summary>
    /// finishTextPreview
    /// </summary>
    public Task FinishTextPreviewAsync()
    {
        return CallMethodAsyncVoid(_finishTextPreview);
    }

    /// <summary>
    /// finishTextPreviewSync
    /// </summary>
    public void FinishTextPreviewSync()
    {
        CallMethodVoid(_finishTextPreviewSync);
    }

    /// <summary>
    /// sendMessage
    /// </summary>
    public Task SendMessageAsync(string msgId, byte[]? msgParam = null)
    {
        return CallMethodAsyncVoid(_sendMessage, msgId, msgParam);
    }

    /// <summary>
    /// recvMessage
    /// </summary>
    public void RecvMessage(InputMethodEngineMessageHandler? msgHandler = null)
    {
        CallMethodVoid(_recvMessage, msgHandler);
    }

    /// <summary>
    /// getAttachOptions
    /// </summary>
    public IntPtr GetAttachOptions()
    {
        return CallMethod<IntPtr>(_getAttachOptions);
    }

    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action<IntPtr> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(args[0]),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action<IntPtr> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 attachOptionsDidChange 事件（对应 on/off）
    /// </summary>
    public event System.Action<IntPtr> AttachOptionsDidChange
    {
        add
        {
            _eventListeners.Add(("attachOptionsDidChange", value),
                args => value(args[0]),
                js => NodeApi.CallMethodVoid(Handle, _on, "attachOptionsDidChange", js));
        }
        remove
        {
            _eventListeners.Remove(("attachOptionsDidChange", value), js => NodeApi.CallMethodVoid(Handle, _off, "attachOptionsDidChange", js));
        }
    }

}

/// <summary>
/// Panel 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class PanelObject : JsObject
{
    public PanelObject(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _setUiContent => "setUiContent"u8;
    private static ReadOnlySpan<byte> _resize => "resize"u8;
    private static ReadOnlySpan<byte> _moveTo => "moveTo"u8;
    private static ReadOnlySpan<byte> _startMoving => "startMoving"u8;
    private static ReadOnlySpan<byte> _getDisplayId => "getDisplayId"u8;
    private static ReadOnlySpan<byte> _show => "show"u8;
    private static ReadOnlySpan<byte> _hide => "hide"u8;
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    private static ReadOnlySpan<byte> _changeFlag => "changeFlag"u8;
    private static ReadOnlySpan<byte> _setPrivacyMode => "setPrivacyMode"u8;
    private static ReadOnlySpan<byte> _adjustPanelRect => "adjustPanelRect"u8;
    private static ReadOnlySpan<byte> _updatePanelRect => "updatePanelRect"u8;
    private static ReadOnlySpan<byte> _updatePanelRectSync => "updatePanelRectSync"u8;
    private static ReadOnlySpan<byte> _updateRegion => "updateRegion"u8;
    private static ReadOnlySpan<byte> _setImmersiveMode => "setImmersiveMode"u8;
    private static ReadOnlySpan<byte> _getImmersiveMode => "getImmersiveMode"u8;
    private static ReadOnlySpan<byte> _setImmersiveEffect => "setImmersiveEffect"u8;
    private static ReadOnlySpan<byte> _setKeepScreenOn => "setKeepScreenOn"u8;
    private static ReadOnlySpan<byte> _getSystemPanelCurrentInsets => "getSystemPanelCurrentInsets"u8;
    private static ReadOnlySpan<byte> _setSystemPanelButtonColor => "setSystemPanelButtonColor"u8;
    /// <summary>
    /// setUiContent
    /// </summary>
    public Task SetUiContentAsync(string path)
    {
        return CallMethodAsyncVoid(_setUiContent, path);
    }

    /// <summary>
    /// setUiContent
    /// </summary>
    public Task SetUiContentAsync(string path, IntPtr storage)
    {
        return CallMethodAsyncVoid(_setUiContent, path, storage);
    }

    /// <summary>
    /// resize
    /// </summary>
    public Task ResizeAsync(double width, double height)
    {
        return CallMethodAsyncVoid(_resize, width, height);
    }

    /// <summary>
    /// moveTo
    /// </summary>
    public Task MoveToAsync(double x, double y)
    {
        return CallMethodAsyncVoid(_moveTo, x, y);
    }

    /// <summary>
    /// startMoving
    /// </summary>
    public void StartMoving()
    {
        CallMethodVoid(_startMoving);
    }

    /// <summary>
    /// getDisplayId
    /// </summary>
    public Task<double> GetDisplayIdAsync()
    {
        return CallMethodAsync<double>(_getDisplayId);
    }

    /// <summary>
    /// show
    /// </summary>
    public Task ShowAsync()
    {
        return CallMethodAsyncVoid(_show);
    }

    /// <summary>
    /// hide
    /// </summary>
    public Task HideAsync()
    {
        return CallMethodAsyncVoid(_hide);
    }

    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    /// <summary>
    /// changeFlag
    /// </summary>
    public void ChangeFlag(global::HarmonyOS.ArkUI.PanelFlag flag)
    {
        CallMethodVoid(_changeFlag, flag);
    }

    /// <summary>
    /// setPrivacyMode
    /// </summary>
    public void SetPrivacyMode(bool isPrivacyMode)
    {
        CallMethodVoid(_setPrivacyMode, isPrivacyMode);
    }

    /// <summary>
    /// adjustPanelRect
    /// </summary>
    public void AdjustPanelRect(global::HarmonyOS.ArkUI.PanelFlag flag, IntPtr rect)
    {
        CallMethodVoid(_adjustPanelRect, flag, rect);
    }

    /// <summary>
    /// updatePanelRect
    /// </summary>
    public Task UpdatePanelRectAsync(global::HarmonyOS.ArkUI.PanelFlag flag, IntPtr rect)
    {
        return CallMethodAsyncVoid(_updatePanelRect, flag, rect);
    }

    /// <summary>
    /// updatePanelRectSync
    /// </summary>
    public void UpdatePanelRectSync(global::HarmonyOS.ArkUI.PanelFlag flag, IntPtr rect)
    {
        CallMethodVoid(_updatePanelRectSync, flag, rect);
    }

    /// <summary>
    /// updateRegion
    /// </summary>
    public void UpdateRegion(IntPtr[] inputRegion)
    {
        CallMethodVoid(_updateRegion, inputRegion);
    }

    /// <summary>
    /// setImmersiveMode
    /// </summary>
    public void SetImmersiveMode(global::HarmonyOS.ArkUI.ImmersiveMode mode)
    {
        CallMethodVoid(_setImmersiveMode, mode);
    }

    /// <summary>
    /// getImmersiveMode
    /// </summary>
    public global::HarmonyOS.ArkUI.ImmersiveMode GetImmersiveMode()
    {
        return CallMethod<global::HarmonyOS.ArkUI.ImmersiveMode>(_getImmersiveMode);
    }

    /// <summary>
    /// setImmersiveEffect
    /// </summary>
    public void SetImmersiveEffect(ImmersiveEffect effect)
    {
        CallMethodVoid(_setImmersiveEffect, effect);
    }

    /// <summary>
    /// setKeepScreenOn
    /// </summary>
    public Task SetKeepScreenOnAsync(bool isKeepScreenOn)
    {
        return CallMethodAsyncVoid(_setKeepScreenOn, isKeepScreenOn);
    }

    /// <summary>
    /// getSystemPanelCurrentInsets
    /// </summary>
    public Task<SystemPanelInsets> GetSystemPanelCurrentInsetsAsync(double displayId)
    {
        return CallMethodAsync(_getSystemPanelCurrentInsets, static h => new SystemPanelInsets(h), displayId);
    }

    /// <summary>
    /// setSystemPanelButtonColor
    /// </summary>
    public Task SetSystemPanelButtonColorAsync(string fillColor, string backgroundColor)
    {
        return CallMethodAsyncVoid(_setSystemPanelButtonColor, fillColor, backgroundColor);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 show 事件（对应 on/off）
    /// </summary>
    public event System.Action ShowEvent
    {
        add
        {
            _eventListeners.Add(("show", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "show", js));
        }
        remove
        {
            _eventListeners.Remove(("show", value), js => NodeApi.CallMethodVoid(Handle, _off, "show", js));
        }
    }

    /// <summary>
    /// 监听 hide 事件（对应 on/off）
    /// </summary>
    public event System.Action HideEvent
    {
        add
        {
            _eventListeners.Add(("hide", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "hide", js));
        }
        remove
        {
            _eventListeners.Remove(("hide", value), js => NodeApi.CallMethodVoid(Handle, _off, "hide", js));
        }
    }

    /// <summary>
    /// 监听 sizeChange 事件（对应 on/off）
    /// </summary>
    public event System.Action SizeChange
    {
        add
        {
            _eventListeners.Add(("sizeChange", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "sizeChange", js));
        }
        remove
        {
            _eventListeners.Remove(("sizeChange", value), js => NodeApi.CallMethodVoid(Handle, _off, "sizeChange", js));
        }
    }

}

/// <summary>
/// TextInputClient 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class TextInputClient : JsObject
{
    public TextInputClient(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _sendKeyFunction => "sendKeyFunction"u8;
    private static ReadOnlySpan<byte> _deleteForward => "deleteForward"u8;
    private static ReadOnlySpan<byte> _deleteBackward => "deleteBackward"u8;
    private static ReadOnlySpan<byte> _insertText => "insertText"u8;
    private static ReadOnlySpan<byte> _getForward => "getForward"u8;
    private static ReadOnlySpan<byte> _getBackward => "getBackward"u8;
    private static ReadOnlySpan<byte> _getEditorAttribute => "getEditorAttribute"u8;
    /// <summary>
    /// sendKeyFunction
    /// </summary>
    public Task<bool> SendKeyFunctionAsync(double action)
    {
        return CallMethodAsync<bool>(_sendKeyFunction, action);
    }

    /// <summary>
    /// deleteForward
    /// </summary>
    public Task<bool> DeleteForwardAsync(double length)
    {
        return CallMethodAsync<bool>(_deleteForward, length);
    }

    /// <summary>
    /// deleteBackward
    /// </summary>
    public Task<bool> DeleteBackwardAsync(double length)
    {
        return CallMethodAsync<bool>(_deleteBackward, length);
    }

    /// <summary>
    /// insertText
    /// </summary>
    public Task<bool> InsertTextAsync(string text)
    {
        return CallMethodAsync<bool>(_insertText, text);
    }

    /// <summary>
    /// getForward
    /// </summary>
    public Task<string> GetForwardAsync(double length)
    {
        return CallMethodAsync<string>(_getForward, length);
    }

    /// <summary>
    /// getBackward
    /// </summary>
    public Task<string> GetBackwardAsync(double length)
    {
        return CallMethodAsync<string>(_getBackward, length);
    }

    /// <summary>
    /// getEditorAttribute
    /// </summary>
    public Task<IntPtr> GetEditorAttributeAsync()
    {
        return CallMethodAsync<IntPtr>(_getEditorAttribute);
    }

}

/// <summary>
/// KeyEvent（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record InputMethodEngineKeyEvent(
    double KeyCode,
    double KeyAction
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _keyCode = System.Text.Encoding.UTF8.GetBytes("keyCode");
        var _keyCodeV = NativeValue.From(KeyCode);
        if (_keyCodeV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _keyCode, _keyCodeV);
        var _keyAction = System.Text.Encoding.UTF8.GetBytes("keyAction");
        var _keyActionV = NativeValue.From(KeyAction);
        if (_keyActionV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _keyAction, _keyActionV);
    }
}

/// <summary>
/// Range（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record InputMethodEngineRange(
    double Start,
    double End
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _start = System.Text.Encoding.UTF8.GetBytes("start");
        var _startV = NativeValue.From(Start);
        if (_startV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _start, _startV);
        var _end = System.Text.Encoding.UTF8.GetBytes("end");
        var _endV = NativeValue.From(End);
        if (_endV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _end, _endV);
    }
}

/// <summary>
/// MessageHandler 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class InputMethodEngineMessageHandler : JsObject
{
    public InputMethodEngineMessageHandler(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _onMessage => "onMessage"u8;
    private static ReadOnlySpan<byte> _onTerminated => "onTerminated"u8;
    /// <summary>
    /// onMessage
    /// </summary>
    public void OnMessage(string msgId, byte[]? msgParam = null)
    {
        CallMethodVoid(_onMessage, msgId, msgParam);
    }

    /// <summary>
    /// onTerminated
    /// </summary>
    public void OnTerminated()
    {
        CallMethodVoid(_onTerminated);
    }

}

/// <summary>
/// ImmersiveEffect（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record ImmersiveEffect(
    double GradientHeight,
    global::HarmonyOS.ArkUI.GradientMode GradientMode
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _gradientHeight = System.Text.Encoding.UTF8.GetBytes("gradientHeight");
        var _gradientHeightV = NativeValue.From(GradientHeight);
        if (_gradientHeightV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _gradientHeight, _gradientHeightV);
        var _gradientMode = System.Text.Encoding.UTF8.GetBytes("gradientMode");
        var _gradientModeV = NativeValue.From(GradientMode);
        if (_gradientModeV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _gradientMode, _gradientModeV);
    }
}

/// <summary>
/// SystemPanelInsets 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class SystemPanelInsets : JsObject
{
    public SystemPanelInsets(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _left => "left"u8;
    private static ReadOnlySpan<byte> _right => "right"u8;
    private static ReadOnlySpan<byte> _bottom => "bottom"u8;
    /// <summary>
    /// left
    /// </summary>
    public double Left => NativeValue.ToDouble(GetPropertyRaw(_left));

    /// <summary>
    /// right
    /// </summary>
    public double Right => NativeValue.ToDouble(GetPropertyRaw(_right));

    /// <summary>
    /// bottom
    /// </summary>
    public double Bottom => NativeValue.ToDouble(GetPropertyRaw(_bottom));

}
