// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// InputEventClient 绑定（@ohos.multimodalInput.inputEventClient）。
/// 所需权限：ohos.permission.CONTROL_DEVICE
/// </summary>
public static unsafe partial class InputEventClient
{
    private const string ModuleName = "@ohos.multimodalInput.inputEventClient";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[multimodalInput.inputEventClient] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _createKeyboardController => "createKeyboardController"u8;
    private static ReadOnlySpan<byte> _createMouseController => "createMouseController"u8;
    private static ReadOnlySpan<byte> _createTouchController => "createTouchController"u8;

    /// <summary>
    /// createKeyboardController
    /// </summary>
    public static Task<InputEventClientKeyboardController> CreateKeyboardControllerAsync()
    {
        return NodeApi.CallMethodAsync(Module, _createKeyboardController, static h => new InputEventClientKeyboardController(h));
    }

    /// <summary>
    /// createMouseController
    /// </summary>
    public static Task<MouseController> CreateMouseControllerAsync()
    {
        return NodeApi.CallMethodAsync(Module, _createMouseController, static h => new MouseController(h));
    }

    /// <summary>
    /// createTouchController
    /// </summary>
    public static Task<TouchController> CreateTouchControllerAsync()
    {
        return NodeApi.CallMethodAsync(Module, _createTouchController, static h => new TouchController(h));
    }

}

/// <summary>
/// KeyboardController 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class InputEventClientKeyboardController : JsObject
{
    public InputEventClientKeyboardController(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _pressKey => "pressKey"u8;
    private static ReadOnlySpan<byte> _releaseKey => "releaseKey"u8;
    /// <summary>
    /// pressKey
    /// </summary>
    public Task PressKeyAsync(IntPtr keyCode)
    {
        return CallMethodAsyncVoid(_pressKey, keyCode);
    }

    /// <summary>
    /// releaseKey
    /// </summary>
    public Task ReleaseKeyAsync(IntPtr keyCode)
    {
        return CallMethodAsyncVoid(_releaseKey, keyCode);
    }

}

/// <summary>
/// MouseController 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class MouseController : JsObject
{
    public MouseController(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _moveTo => "moveTo"u8;
    private static ReadOnlySpan<byte> _pressButton => "pressButton"u8;
    private static ReadOnlySpan<byte> _releaseButton => "releaseButton"u8;
    private static ReadOnlySpan<byte> _beginAxis => "beginAxis"u8;
    private static ReadOnlySpan<byte> _updateAxis => "updateAxis"u8;
    private static ReadOnlySpan<byte> _endAxis => "endAxis"u8;
    /// <summary>
    /// moveTo
    /// </summary>
    public Task MoveToAsync(double displayId, double displayX, double displayY)
    {
        return CallMethodAsyncVoid(_moveTo, displayId, displayX, displayY);
    }

    /// <summary>
    /// pressButton
    /// </summary>
    public Task PressButtonAsync(global::HarmonyOS.ArkUI.MouseEventButton button)
    {
        return CallMethodAsyncVoid(_pressButton, button);
    }

    /// <summary>
    /// releaseButton
    /// </summary>
    public Task ReleaseButtonAsync(global::HarmonyOS.ArkUI.MouseEventButton button)
    {
        return CallMethodAsyncVoid(_releaseButton, button);
    }

    /// <summary>
    /// beginAxis
    /// </summary>
    public Task BeginAxisAsync(global::HarmonyOS.ArkUI.Axis axis, double value)
    {
        return CallMethodAsyncVoid(_beginAxis, axis, value);
    }

    /// <summary>
    /// updateAxis
    /// </summary>
    public Task UpdateAxisAsync(global::HarmonyOS.ArkUI.Axis axis, double value)
    {
        return CallMethodAsyncVoid(_updateAxis, axis, value);
    }

    /// <summary>
    /// endAxis
    /// </summary>
    public Task EndAxisAsync(global::HarmonyOS.ArkUI.Axis axis)
    {
        return CallMethodAsyncVoid(_endAxis, axis);
    }

}

/// <summary>
/// TouchController 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class TouchController : JsObject
{
    public TouchController(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _touchDown => "touchDown"u8;
    private static ReadOnlySpan<byte> _touchMove => "touchMove"u8;
    private static ReadOnlySpan<byte> _touchUp => "touchUp"u8;
    /// <summary>
    /// touchDown
    /// </summary>
    public Task TouchDownAsync(TouchPoint touch)
    {
        return CallMethodAsyncVoid(_touchDown, NapiArg.Of(touch));
    }

    /// <summary>
    /// touchMove
    /// </summary>
    public Task TouchMoveAsync(TouchPoint touch)
    {
        return CallMethodAsyncVoid(_touchMove, NapiArg.Of(touch));
    }

    /// <summary>
    /// touchUp
    /// </summary>
    public Task TouchUpAsync(TouchPoint touch)
    {
        return CallMethodAsyncVoid(_touchUp, NapiArg.Of(touch));
    }

}

/// <summary>
/// TouchPoint 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class TouchPoint : JsObject
{
    public TouchPoint(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _id => "id"u8;
    private static ReadOnlySpan<byte> _displayId => "displayId"u8;
    private static ReadOnlySpan<byte> _displayX => "displayX"u8;
    private static ReadOnlySpan<byte> _displayY => "displayY"u8;
    /// <summary>
    /// id
    /// </summary>
    public double Id => NativeValue.ToDouble(GetPropertyRaw(_id));

    /// <summary>
    /// displayId
    /// </summary>
    public double DisplayId => NativeValue.ToDouble(GetPropertyRaw(_displayId));

    /// <summary>
    /// displayX
    /// </summary>
    public double DisplayX => NativeValue.ToDouble(GetPropertyRaw(_displayX));

    /// <summary>
    /// displayY
    /// </summary>
    public double DisplayY => NativeValue.ToDouble(GetPropertyRaw(_displayY));

}
