// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// InputEvent 绑定（@ohos.multimodalInput.inputEvent）。
/// </summary>
public static unsafe partial class InputEvent
{
    private const string ModuleName = "@ohos.multimodalInput.inputEvent";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[multimodalInput.inputEvent] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

}

/// <summary>
/// InputEvent（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record InputEventObject(
    double Id,
    double DeviceId,
    double ActionTime,
    double ScreenId,
    double WindowId
) : INapiRecord
{
    private static ReadOnlySpan<byte> _idName => "id"u8;
    private static ReadOnlySpan<byte> _deviceIdName => "deviceId"u8;
    private static ReadOnlySpan<byte> _actionTimeName => "actionTime"u8;
    private static ReadOnlySpan<byte> _screenIdName => "screenId"u8;
    private static ReadOnlySpan<byte> _windowIdName => "windowId"u8;
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _idV = NativeValue.From(Id);
        if (_idV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _idName, _idV);
        var _deviceIdV = NativeValue.From(DeviceId);
        if (_deviceIdV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _deviceIdName, _deviceIdV);
        var _actionTimeV = NativeValue.From(ActionTime);
        if (_actionTimeV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _actionTimeName, _actionTimeV);
        var _screenIdV = NativeValue.From(ScreenId);
        if (_screenIdV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _screenIdName, _screenIdV);
        var _windowIdV = NativeValue.From(WindowId);
        if (_windowIdV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _windowIdName, _windowIdV);
    }
}
