// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// Measure 绑定（@ohos.measure）。
/// </summary>
public static unsafe partial class Measure
{
    private const string ModuleName = "@ohos.measure";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[measure] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _measureText => "measureText"u8;
    private static ReadOnlySpan<byte> _measureTextSize => "measureTextSize"u8;

    /// <summary>
    /// measureText
    /// </summary>
    public static double MeasureText(IntPtr options)
    {
        return NodeApi.CallMethod<double>(Module, _measureText, options);
    }

    /// <summary>
    /// measureTextSize
    /// </summary>
    public static IntPtr MeasureTextSize(IntPtr options)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _measureTextSize, options);
    }

}

/// <summary>
/// MeasureOptions 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class MeasureOptions : JsObject
{
    public MeasureOptions(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _textContent => "textContent"u8;
    private static ReadOnlySpan<byte> _constraintWidth => "constraintWidth"u8;
    private static ReadOnlySpan<byte> _fontSize => "fontSize"u8;
    private static ReadOnlySpan<byte> _fontStyle => "fontStyle"u8;
    private static ReadOnlySpan<byte> _fontWeight => "fontWeight"u8;
    private static ReadOnlySpan<byte> _fontFamily => "fontFamily"u8;
    private static ReadOnlySpan<byte> _letterSpacing => "letterSpacing"u8;
    private static ReadOnlySpan<byte> _textAlign => "textAlign"u8;
    private static ReadOnlySpan<byte> _overflow => "overflow"u8;
    private static ReadOnlySpan<byte> _maxLines => "maxLines"u8;
    private static ReadOnlySpan<byte> _lineHeight => "lineHeight"u8;
    private static ReadOnlySpan<byte> _baselineOffset => "baselineOffset"u8;
    private static ReadOnlySpan<byte> _textCase => "textCase"u8;
    private static ReadOnlySpan<byte> _textIndent => "textIndent"u8;
    private static ReadOnlySpan<byte> _wordBreak => "wordBreak"u8;
    /// <summary>
    /// textContent
    /// </summary>
    public string TextContent => NativeValue.ToString(GetPropertyRaw(_textContent)) ?? string.Empty;

    /// <summary>
    /// constraintWidth
    /// </summary>
    public double? ConstraintWidth => (double?)NativeValue.ToDouble(GetPropertyRaw(_constraintWidth));

    /// <summary>
    /// fontSize
    /// </summary>
    public double? FontSize => (double?)NativeValue.ToDouble(GetPropertyRaw(_fontSize));

    /// <summary>
    /// fontStyle
    /// </summary>
    public double? FontStyle => (double?)NativeValue.ToDouble(GetPropertyRaw(_fontStyle));

    /// <summary>
    /// fontWeight
    /// </summary>
    public double? FontWeight => (double?)NativeValue.ToDouble(GetPropertyRaw(_fontWeight));

    /// <summary>
    /// fontFamily
    /// </summary>
    public string? FontFamily => (string?)NativeValue.ToString(GetPropertyRaw(_fontFamily)) ?? string.Empty;

    /// <summary>
    /// letterSpacing
    /// </summary>
    public double? LetterSpacing => (double?)NativeValue.ToDouble(GetPropertyRaw(_letterSpacing));

    /// <summary>
    /// textAlign
    /// </summary>
    public double? TextAlign => (double?)NativeValue.ToDouble(GetPropertyRaw(_textAlign));

    /// <summary>
    /// overflow
    /// </summary>
    public double? Overflow => (double?)NativeValue.ToDouble(GetPropertyRaw(_overflow));

    /// <summary>
    /// maxLines
    /// </summary>
    public double? MaxLines => (double?)NativeValue.ToDouble(GetPropertyRaw(_maxLines));

    /// <summary>
    /// lineHeight
    /// </summary>
    public double? LineHeight => (double?)NativeValue.ToDouble(GetPropertyRaw(_lineHeight));

    /// <summary>
    /// baselineOffset
    /// </summary>
    public double? BaselineOffset => (double?)NativeValue.ToDouble(GetPropertyRaw(_baselineOffset));

    /// <summary>
    /// textCase
    /// </summary>
    public double? TextCase => (double?)NativeValue.ToDouble(GetPropertyRaw(_textCase));

    /// <summary>
    /// textIndent
    /// </summary>
    public double? TextIndent => (double?)NativeValue.ToDouble(GetPropertyRaw(_textIndent));

    /// <summary>
    /// wordBreak
    /// </summary>
    public IntPtr WordBreak => GetPropertyRaw(_wordBreak);

}
