// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// Movingphotoview 绑定（@ohos.multimedia.movingphotoview）。
/// </summary>
public static unsafe partial class Movingphotoview
{
    private const string ModuleName = "@ohos.multimedia.movingphotoview";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[multimedia.movingphotoview] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _muted => "muted"u8;
    private static ReadOnlySpan<byte> _objectFit => "objectFit"u8;
    private static ReadOnlySpan<byte> _onComplete => "onComplete"u8;
    private static ReadOnlySpan<byte> _onStart => "onStart"u8;
    private static ReadOnlySpan<byte> _onStop => "onStop"u8;
    private static ReadOnlySpan<byte> _onPause => "onPause"u8;
    private static ReadOnlySpan<byte> _onFinish => "onFinish"u8;
    private static ReadOnlySpan<byte> _onError => "onError"u8;
    private static ReadOnlySpan<byte> _onPrepared => "onPrepared"u8;
    private static ReadOnlySpan<byte> _autoPlayPeriod => "autoPlayPeriod"u8;
    private static ReadOnlySpan<byte> _autoPlay => "autoPlay"u8;
    private static ReadOnlySpan<byte> _repeatPlay => "repeatPlay"u8;
    private static ReadOnlySpan<byte> _enableAnalyzer => "enableAnalyzer"u8;
    private static ReadOnlySpan<byte> _startPlayback => "startPlayback"u8;
    private static ReadOnlySpan<byte> _stopPlayback => "stopPlayback"u8;
    private static ReadOnlySpan<byte> _refreshMovingPhoto => "refreshMovingPhoto"u8;

    /// <summary>
    /// muted
    /// </summary>
    public static IntPtr Muted(bool isMuted)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _muted, isMuted);
    }

    /// <summary>
    /// objectFit
    /// </summary>
    public static IntPtr ObjectFit(IntPtr value)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _objectFit, value);
    }

    /// <summary>
    /// onComplete
    /// </summary>
    public static IntPtr OnComplete(IntPtr callback)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onComplete, callback);
    }

    /// <summary>
    /// onStart
    /// </summary>
    public static IntPtr OnStart(IntPtr callback)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onStart, callback);
    }

    /// <summary>
    /// onStop
    /// </summary>
    public static IntPtr OnStop(IntPtr callback)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onStop, callback);
    }

    /// <summary>
    /// onPause
    /// </summary>
    public static IntPtr OnPause(IntPtr callback)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onPause, callback);
    }

    /// <summary>
    /// onFinish
    /// </summary>
    public static IntPtr OnFinish(IntPtr callback)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onFinish, callback);
    }

    /// <summary>
    /// onError
    /// </summary>
    public static IntPtr OnError(IntPtr callback)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onError, callback);
    }

    /// <summary>
    /// onPrepared
    /// </summary>
    public static IntPtr OnPrepared(IntPtr callback)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onPrepared, callback);
    }

    /// <summary>
    /// autoPlayPeriod
    /// </summary>
    public static IntPtr AutoPlayPeriod(double startTime, double endTime)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _autoPlayPeriod, startTime, endTime);
    }

    /// <summary>
    /// autoPlay
    /// </summary>
    public static IntPtr AutoPlay(bool isAutoPlay)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _autoPlay, isAutoPlay);
    }

    /// <summary>
    /// repeatPlay
    /// </summary>
    public static IntPtr RepeatPlay(bool isRepeatPlay)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _repeatPlay, isRepeatPlay);
    }

    /// <summary>
    /// enableAnalyzer
    /// </summary>
    public static IntPtr EnableAnalyzer(bool enabled)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _enableAnalyzer, enabled);
    }

    /// <summary>
    /// startPlayback
    /// </summary>
    public static void StartPlayback()
    {
        NodeApi.CallMethodVoid(Module, _startPlayback);
    }

    /// <summary>
    /// stopPlayback
    /// </summary>
    public static void StopPlayback()
    {
        NodeApi.CallMethodVoid(Module, _stopPlayback);
    }

    /// <summary>
    /// refreshMovingPhoto
    /// </summary>
    public static void RefreshMovingPhoto()
    {
        NodeApi.CallMethodVoid(Module, _refreshMovingPhoto);
    }

}

/// <summary>
/// MovingPhotoViewController 实例包装（@ohos 命名空间内嵌套类）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class MovingPhotoViewController : JsObject
{
    public MovingPhotoViewController(IntPtr handle) : base(handle) { }

    private static ReadOnlySpan<byte> _MovingPhotoViewController => "MovingPhotoViewController"u8;

    public MovingPhotoViewController()
        : this(NodeApi.CreateInstance(Movingphotoview.Module, _MovingPhotoViewController)) { }
    private static ReadOnlySpan<byte> _startPlayback => "startPlayback"u8;
    private static ReadOnlySpan<byte> _stopPlayback => "stopPlayback"u8;
    private static ReadOnlySpan<byte> _refreshMovingPhoto => "refreshMovingPhoto"u8;
    /// <summary>
    /// startPlayback
    /// </summary>
    public void StartPlayback()
    {
        CallMethodVoid(_startPlayback);
    }

    /// <summary>
    /// stopPlayback
    /// </summary>
    public void StopPlayback()
    {
        CallMethodVoid(_stopPlayback);
    }

    /// <summary>
    /// refreshMovingPhoto
    /// </summary>
    public void RefreshMovingPhoto()
    {
        CallMethodVoid(_refreshMovingPhoto);
    }

}
