// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// NetSocket 绑定（@ohos.net.socket）。
/// 所需权限：ohos.permission.INTERNET
/// </summary>
public static unsafe partial class NetSocket
{
    private const string ModuleName = "@ohos.net.socket";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[net.socket] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _constructUDPSocketInstance => "constructUDPSocketInstance"u8;
    private static ReadOnlySpan<byte> _constructMulticastSocketInstance => "constructMulticastSocketInstance"u8;
    private static ReadOnlySpan<byte> _constructTCPSocketInstance => "constructTCPSocketInstance"u8;
    private static ReadOnlySpan<byte> _constructTLSSocketInstance => "constructTLSSocketInstance"u8;
    private static ReadOnlySpan<byte> _constructTCPSocketServerInstance => "constructTCPSocketServerInstance"u8;
    private static ReadOnlySpan<byte> _constructTLSSocketServerInstance => "constructTLSSocketServerInstance"u8;
    private static ReadOnlySpan<byte> _constructLocalSocketInstance => "constructLocalSocketInstance"u8;
    private static ReadOnlySpan<byte> _constructLocalSocketServerInstance => "constructLocalSocketServerInstance"u8;

    /// <summary>
    /// constructUDPSocketInstance
    /// </summary>
    public static UDPSocket ConstructUdpSocketInstance()
    {
        return NodeApi.CallMethod(Module, _constructUDPSocketInstance, static h => new UDPSocket(h));
    }

    /// <summary>
    /// constructMulticastSocketInstance
    /// </summary>
    public static MulticastSocket ConstructMulticastSocketInstance()
    {
        return NodeApi.CallMethod(Module, _constructMulticastSocketInstance, static h => new MulticastSocket(h));
    }

    /// <summary>
    /// constructTCPSocketInstance
    /// </summary>
    public static TCPSocket ConstructTcpSocketInstance()
    {
        return NodeApi.CallMethod(Module, _constructTCPSocketInstance, static h => new TCPSocket(h));
    }

    /// <summary>
    /// constructTLSSocketInstance
    /// </summary>
    public static TLSSocket ConstructTlsSocketInstance()
    {
        return NodeApi.CallMethod(Module, _constructTLSSocketInstance, static h => new TLSSocket(h));
    }

    /// <summary>
    /// constructTLSSocketInstance
    /// </summary>
    public static TLSSocket ConstructTlsSocketInstance(TCPSocket tcpSocket)
    {
        return NodeApi.CallMethod(Module, _constructTLSSocketInstance, static h => new TLSSocket(h), tcpSocket);
    }

    /// <summary>
    /// constructTCPSocketServerInstance
    /// </summary>
    public static TCPSocketServer ConstructTcpSocketServerInstance()
    {
        return NodeApi.CallMethod(Module, _constructTCPSocketServerInstance, static h => new TCPSocketServer(h));
    }

    /// <summary>
    /// constructTLSSocketServerInstance
    /// </summary>
    public static TLSSocketServer ConstructTlsSocketServerInstance()
    {
        return NodeApi.CallMethod(Module, _constructTLSSocketServerInstance, static h => new TLSSocketServer(h));
    }

    /// <summary>
    /// constructLocalSocketInstance
    /// </summary>
    public static LocalSocket ConstructLocalSocketInstance()
    {
        return NodeApi.CallMethod(Module, _constructLocalSocketInstance, static h => new LocalSocket(h));
    }

    /// <summary>
    /// constructLocalSocketServerInstance
    /// </summary>
    public static LocalSocketServer ConstructLocalSocketServerInstance()
    {
        return NodeApi.CallMethod(Module, _constructLocalSocketServerInstance, static h => new LocalSocketServer(h));
    }

}

/// <summary>
/// UDPSocket 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class UDPSocket : JsObject
{
    public UDPSocket(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _bind => "bind"u8;
    private static ReadOnlySpan<byte> _getLocalAddress => "getLocalAddress"u8;
    private static ReadOnlySpan<byte> _send => "send"u8;
    private static ReadOnlySpan<byte> _close => "close"u8;
    private static ReadOnlySpan<byte> _getState => "getState"u8;
    private static ReadOnlySpan<byte> _setExtraOptions => "setExtraOptions"u8;
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    private static ReadOnlySpan<byte> _getSocketFd => "getSocketFd"u8;
    /// <summary>
    /// bind
    /// </summary>
    public Task BindAsync(NetAddress address)
    {
        return CallMethodAsyncVoid(_bind, address);
    }

    /// <summary>
    /// getLocalAddress
    /// </summary>
    public Task<NetAddress> GetLocalAddressAsync()
    {
        return CallMethodAsync<NetAddress>(_getLocalAddress);
    }

    /// <summary>
    /// send
    /// </summary>
    public Task SendAsync(IntPtr options)
    {
        return CallMethodAsyncVoid(_send, options);
    }

    /// <summary>
    /// close
    /// </summary>
    public Task CloseAsync()
    {
        return CallMethodAsyncVoid(_close);
    }

    /// <summary>
    /// getState
    /// </summary>
    public Task<SocketStateBase> GetStateAsync()
    {
        return CallMethodAsync(_getState, static h => new SocketStateBase(h));
    }

    /// <summary>
    /// setExtraOptions
    /// </summary>
    public Task SetExtraOptionsAsync(UDPExtraOptions options)
    {
        return CallMethodAsyncVoid(_setExtraOptions, options);
    }

    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    /// <summary>
    /// getSocketFd
    /// </summary>
    public Task<double> GetSocketFdAsync()
    {
        return CallMethodAsync<double>(_getSocketFd);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action<SocketMessageInfo> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(new SocketMessageInfo(args[0])),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action<SocketMessageInfo> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 message 事件（对应 on/off）
    /// </summary>
    public event System.Action<SocketMessageInfo> Message
    {
        add
        {
            _eventListeners.Add(("message", value),
                args => value(new SocketMessageInfo(args[0])),
                js => NodeApi.CallMethodVoid(Handle, _on, "message", js));
        }
        remove
        {
            _eventListeners.Remove(("message", value), js => NodeApi.CallMethodVoid(Handle, _off, "message", js));
        }
    }

    /// <summary>
    /// 监听 listening 事件（对应 on/off）
    /// </summary>
    public event System.Action Listening
    {
        add
        {
            _eventListeners.Add(("listening", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "listening", js));
        }
        remove
        {
            _eventListeners.Remove(("listening", value), js => NodeApi.CallMethodVoid(Handle, _off, "listening", js));
        }
    }

    /// <summary>
    /// 监听 close 事件（对应 on/off）
    /// </summary>
    public event System.Action CloseEvent
    {
        add
        {
            _eventListeners.Add(("close", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "close", js));
        }
        remove
        {
            _eventListeners.Remove(("close", value), js => NodeApi.CallMethodVoid(Handle, _off, "close", js));
        }
    }

    /// <summary>
    /// 监听 error 事件（对应 on/off）
    /// </summary>
    public event System.Action Error
    {
        add
        {
            _eventListeners.Add(("error", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "error", js));
        }
        remove
        {
            _eventListeners.Remove(("error", value), js => NodeApi.CallMethodVoid(Handle, _off, "error", js));
        }
    }

}

/// <summary>
/// MulticastSocket 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class MulticastSocket : JsObject
{
    public MulticastSocket(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _bind => "bind"u8;
    private static ReadOnlySpan<byte> _getLocalAddress => "getLocalAddress"u8;
    private static ReadOnlySpan<byte> _send => "send"u8;
    private static ReadOnlySpan<byte> _close => "close"u8;
    private static ReadOnlySpan<byte> _getState => "getState"u8;
    private static ReadOnlySpan<byte> _setExtraOptions => "setExtraOptions"u8;
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    private static ReadOnlySpan<byte> _getSocketFd => "getSocketFd"u8;
    private static ReadOnlySpan<byte> _addMembership => "addMembership"u8;
    private static ReadOnlySpan<byte> _dropMembership => "dropMembership"u8;
    private static ReadOnlySpan<byte> _setMulticastTTL => "setMulticastTTL"u8;
    private static ReadOnlySpan<byte> _getMulticastTTL => "getMulticastTTL"u8;
    private static ReadOnlySpan<byte> _setLoopbackMode => "setLoopbackMode"u8;
    private static ReadOnlySpan<byte> _getLoopbackMode => "getLoopbackMode"u8;
    private static ReadOnlySpan<byte> _setReuseAddress => "setReuseAddress"u8;
    /// <summary>
    /// bind
    /// </summary>
    public Task BindAsync(NetAddress address)
    {
        return CallMethodAsyncVoid(_bind, address);
    }

    /// <summary>
    /// getLocalAddress
    /// </summary>
    public Task<NetAddress> GetLocalAddressAsync()
    {
        return CallMethodAsync<NetAddress>(_getLocalAddress);
    }

    /// <summary>
    /// send
    /// </summary>
    public Task SendAsync(IntPtr options)
    {
        return CallMethodAsyncVoid(_send, options);
    }

    /// <summary>
    /// close
    /// </summary>
    public Task CloseAsync()
    {
        return CallMethodAsyncVoid(_close);
    }

    /// <summary>
    /// getState
    /// </summary>
    public Task<SocketStateBase> GetStateAsync()
    {
        return CallMethodAsync(_getState, static h => new SocketStateBase(h));
    }

    /// <summary>
    /// setExtraOptions
    /// </summary>
    public Task SetExtraOptionsAsync(UDPExtraOptions options)
    {
        return CallMethodAsyncVoid(_setExtraOptions, options);
    }

    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    /// <summary>
    /// getSocketFd
    /// </summary>
    public Task<double> GetSocketFdAsync()
    {
        return CallMethodAsync<double>(_getSocketFd);
    }

    /// <summary>
    /// addMembership
    /// </summary>
    public Task AddMembershipAsync(NetAddress multicastAddress)
    {
        return CallMethodAsyncVoid(_addMembership, multicastAddress);
    }

    /// <summary>
    /// dropMembership
    /// </summary>
    public Task DropMembershipAsync(NetAddress multicastAddress)
    {
        return CallMethodAsyncVoid(_dropMembership, multicastAddress);
    }

    /// <summary>
    /// setMulticastTTL
    /// </summary>
    public Task SetMulticastTtlAsync(double ttl)
    {
        return CallMethodAsyncVoid(_setMulticastTTL, ttl);
    }

    /// <summary>
    /// getMulticastTTL
    /// </summary>
    public Task<double> GetMulticastTtlAsync()
    {
        return CallMethodAsync<double>(_getMulticastTTL);
    }

    /// <summary>
    /// setLoopbackMode
    /// </summary>
    public Task SetLoopbackModeAsync(bool flag)
    {
        return CallMethodAsyncVoid(_setLoopbackMode, flag);
    }

    /// <summary>
    /// getLoopbackMode
    /// </summary>
    public Task<bool> GetLoopbackModeAsync()
    {
        return CallMethodAsync<bool>(_getLoopbackMode);
    }

    /// <summary>
    /// setReuseAddress
    /// </summary>
    public void SetReuseAddress(bool reuse)
    {
        CallMethodVoid(_setReuseAddress, reuse);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action<SocketMessageInfo> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(new SocketMessageInfo(args[0])),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action<SocketMessageInfo> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 message 事件（对应 on/off）
    /// </summary>
    public event System.Action<SocketMessageInfo> Message
    {
        add
        {
            _eventListeners.Add(("message", value),
                args => value(new SocketMessageInfo(args[0])),
                js => NodeApi.CallMethodVoid(Handle, _on, "message", js));
        }
        remove
        {
            _eventListeners.Remove(("message", value), js => NodeApi.CallMethodVoid(Handle, _off, "message", js));
        }
    }

    /// <summary>
    /// 监听 listening 事件（对应 on/off）
    /// </summary>
    public event System.Action Listening
    {
        add
        {
            _eventListeners.Add(("listening", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "listening", js));
        }
        remove
        {
            _eventListeners.Remove(("listening", value), js => NodeApi.CallMethodVoid(Handle, _off, "listening", js));
        }
    }

    /// <summary>
    /// 监听 close 事件（对应 on/off）
    /// </summary>
    public event System.Action CloseEvent
    {
        add
        {
            _eventListeners.Add(("close", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "close", js));
        }
        remove
        {
            _eventListeners.Remove(("close", value), js => NodeApi.CallMethodVoid(Handle, _off, "close", js));
        }
    }

    /// <summary>
    /// 监听 error 事件（对应 on/off）
    /// </summary>
    public event System.Action Error
    {
        add
        {
            _eventListeners.Add(("error", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "error", js));
        }
        remove
        {
            _eventListeners.Remove(("error", value), js => NodeApi.CallMethodVoid(Handle, _off, "error", js));
        }
    }

}

/// <summary>
/// TCPSocket 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class TCPSocket : JsObject
{
    public TCPSocket(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _bind => "bind"u8;
    private static ReadOnlySpan<byte> _connect => "connect"u8;
    private static ReadOnlySpan<byte> _send => "send"u8;
    private static ReadOnlySpan<byte> _close => "close"u8;
    private static ReadOnlySpan<byte> _getRemoteAddress => "getRemoteAddress"u8;
    private static ReadOnlySpan<byte> _getState => "getState"u8;
    private static ReadOnlySpan<byte> _getSocketFd => "getSocketFd"u8;
    private static ReadOnlySpan<byte> _setExtraOptions => "setExtraOptions"u8;
    private static ReadOnlySpan<byte> _getLocalAddress => "getLocalAddress"u8;
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    /// <summary>
    /// bind
    /// </summary>
    public Task BindAsync(NetAddress address)
    {
        return CallMethodAsyncVoid(_bind, address);
    }

    /// <summary>
    /// connect
    /// </summary>
    public Task ConnectAsync(IntPtr options)
    {
        return CallMethodAsyncVoid(_connect, options);
    }

    /// <summary>
    /// send
    /// </summary>
    public Task SendAsync(TCPSendOptions options)
    {
        return CallMethodAsyncVoid(_send, options);
    }

    /// <summary>
    /// close
    /// </summary>
    public Task CloseAsync()
    {
        return CallMethodAsyncVoid(_close);
    }

    /// <summary>
    /// getRemoteAddress
    /// </summary>
    public Task<NetAddress> GetRemoteAddressAsync()
    {
        return CallMethodAsync<NetAddress>(_getRemoteAddress);
    }

    /// <summary>
    /// getState
    /// </summary>
    public Task<SocketStateBase> GetStateAsync()
    {
        return CallMethodAsync(_getState, static h => new SocketStateBase(h));
    }

    /// <summary>
    /// getSocketFd
    /// </summary>
    public Task<double> GetSocketFdAsync()
    {
        return CallMethodAsync<double>(_getSocketFd);
    }

    /// <summary>
    /// setExtraOptions
    /// </summary>
    public Task SetExtraOptionsAsync(IntPtr options)
    {
        return CallMethodAsyncVoid(_setExtraOptions, options);
    }

    /// <summary>
    /// getLocalAddress
    /// </summary>
    public Task<NetAddress> GetLocalAddressAsync()
    {
        return CallMethodAsync<NetAddress>(_getLocalAddress);
    }

    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action<SocketMessageInfo> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(new SocketMessageInfo(args[0])),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action<SocketMessageInfo> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 message 事件（对应 on/off）
    /// </summary>
    public event System.Action<SocketMessageInfo> Message
    {
        add
        {
            _eventListeners.Add(("message", value),
                args => value(new SocketMessageInfo(args[0])),
                js => NodeApi.CallMethodVoid(Handle, _on, "message", js));
        }
        remove
        {
            _eventListeners.Remove(("message", value), js => NodeApi.CallMethodVoid(Handle, _off, "message", js));
        }
    }

    /// <summary>
    /// 监听 connect 事件（对应 on/off）
    /// </summary>
    public event System.Action ConnectEvent
    {
        add
        {
            _eventListeners.Add(("connect", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "connect", js));
        }
        remove
        {
            _eventListeners.Remove(("connect", value), js => NodeApi.CallMethodVoid(Handle, _off, "connect", js));
        }
    }

    /// <summary>
    /// 监听 close 事件（对应 on/off）
    /// </summary>
    public event System.Action CloseEvent
    {
        add
        {
            _eventListeners.Add(("close", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "close", js));
        }
        remove
        {
            _eventListeners.Remove(("close", value), js => NodeApi.CallMethodVoid(Handle, _off, "close", js));
        }
    }

    /// <summary>
    /// 监听 error 事件（对应 on/off）
    /// </summary>
    public event System.Action Error
    {
        add
        {
            _eventListeners.Add(("error", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "error", js));
        }
        remove
        {
            _eventListeners.Remove(("error", value), js => NodeApi.CallMethodVoid(Handle, _off, "error", js));
        }
    }

}

/// <summary>
/// TLSSocket 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class TLSSocket : JsObject
{
    public TLSSocket(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _bind => "bind"u8;
    private static ReadOnlySpan<byte> _getRemoteAddress => "getRemoteAddress"u8;
    private static ReadOnlySpan<byte> _getState => "getState"u8;
    private static ReadOnlySpan<byte> _setExtraOptions => "setExtraOptions"u8;
    private static ReadOnlySpan<byte> _getLocalAddress => "getLocalAddress"u8;
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    private static ReadOnlySpan<byte> _getCertificate => "getCertificate"u8;
    private static ReadOnlySpan<byte> _getRemoteCertificate => "getRemoteCertificate"u8;
    private static ReadOnlySpan<byte> _getProtocol => "getProtocol"u8;
    private static ReadOnlySpan<byte> _getCipherSuite => "getCipherSuite"u8;
    private static ReadOnlySpan<byte> _getSignatureAlgorithms => "getSignatureAlgorithms"u8;
    private static ReadOnlySpan<byte> _getSocketFd => "getSocketFd"u8;
    private static ReadOnlySpan<byte> _connect => "connect"u8;
    private static ReadOnlySpan<byte> _send => "send"u8;
    private static ReadOnlySpan<byte> _close => "close"u8;
    /// <summary>
    /// bind
    /// </summary>
    public Task BindAsync(NetAddress address)
    {
        return CallMethodAsyncVoid(_bind, address);
    }

    /// <summary>
    /// getRemoteAddress
    /// </summary>
    public Task<NetAddress> GetRemoteAddressAsync()
    {
        return CallMethodAsync<NetAddress>(_getRemoteAddress);
    }

    /// <summary>
    /// getState
    /// </summary>
    public Task<SocketStateBase> GetStateAsync()
    {
        return CallMethodAsync(_getState, static h => new SocketStateBase(h));
    }

    /// <summary>
    /// setExtraOptions
    /// </summary>
    public Task SetExtraOptionsAsync(IntPtr options)
    {
        return CallMethodAsyncVoid(_setExtraOptions, options);
    }

    /// <summary>
    /// getLocalAddress
    /// </summary>
    public Task<NetAddress> GetLocalAddressAsync()
    {
        return CallMethodAsync<NetAddress>(_getLocalAddress);
    }

    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    /// <summary>
    /// getCertificate
    /// </summary>
    public Task<IntPtr> GetCertificateAsync()
    {
        return CallMethodAsync<IntPtr>(_getCertificate);
    }

    /// <summary>
    /// getRemoteCertificate
    /// </summary>
    public Task<IntPtr> GetRemoteCertificateAsync()
    {
        return CallMethodAsync<IntPtr>(_getRemoteCertificate);
    }

    /// <summary>
    /// getProtocol
    /// </summary>
    public Task<string> GetProtocolAsync()
    {
        return CallMethodAsync<string>(_getProtocol);
    }

    /// <summary>
    /// getCipherSuite
    /// </summary>
    public Task<string[]> GetCipherSuiteAsync()
    {
        return CallMethodAsync(_getCipherSuite, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<string>(e)));
    }

    /// <summary>
    /// getSignatureAlgorithms
    /// </summary>
    public Task<string[]> GetSignatureAlgorithmsAsync()
    {
        return CallMethodAsync(_getSignatureAlgorithms, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<string>(e)));
    }

    /// <summary>
    /// getSocketFd
    /// </summary>
    public Task<double> GetSocketFdAsync()
    {
        return CallMethodAsync<double>(_getSocketFd);
    }

    /// <summary>
    /// connect
    /// </summary>
    public Task ConnectAsync(IntPtr options)
    {
        return CallMethodAsyncVoid(_connect, options);
    }

    /// <summary>
    /// send
    /// </summary>
    public Task SendAsync(string data)
    {
        return CallMethodAsyncVoid(_send, data);
    }

    /// <summary>
    /// close
    /// </summary>
    public Task CloseAsync()
    {
        return CallMethodAsyncVoid(_close);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action<SocketMessageInfo> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(new SocketMessageInfo(args[0])),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action<SocketMessageInfo> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 message 事件（对应 on/off）
    /// </summary>
    public event System.Action<SocketMessageInfo> Message
    {
        add
        {
            _eventListeners.Add(("message", value),
                args => value(new SocketMessageInfo(args[0])),
                js => NodeApi.CallMethodVoid(Handle, _on, "message", js));
        }
        remove
        {
            _eventListeners.Remove(("message", value), js => NodeApi.CallMethodVoid(Handle, _off, "message", js));
        }
    }

    /// <summary>
    /// 监听 connect 事件（对应 on/off）
    /// </summary>
    public event System.Action ConnectEvent
    {
        add
        {
            _eventListeners.Add(("connect", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "connect", js));
        }
        remove
        {
            _eventListeners.Remove(("connect", value), js => NodeApi.CallMethodVoid(Handle, _off, "connect", js));
        }
    }

    /// <summary>
    /// 监听 close 事件（对应 on/off）
    /// </summary>
    public event System.Action CloseEvent
    {
        add
        {
            _eventListeners.Add(("close", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "close", js));
        }
        remove
        {
            _eventListeners.Remove(("close", value), js => NodeApi.CallMethodVoid(Handle, _off, "close", js));
        }
    }

    /// <summary>
    /// 监听 error 事件（对应 on/off）
    /// </summary>
    public event System.Action Error
    {
        add
        {
            _eventListeners.Add(("error", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "error", js));
        }
        remove
        {
            _eventListeners.Remove(("error", value), js => NodeApi.CallMethodVoid(Handle, _off, "error", js));
        }
    }

}

/// <summary>
/// TCPSocketServer 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class TCPSocketServer : JsObject
{
    public TCPSocketServer(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _listen => "listen"u8;
    private static ReadOnlySpan<byte> _close => "close"u8;
    private static ReadOnlySpan<byte> _getState => "getState"u8;
    private static ReadOnlySpan<byte> _setExtraOptions => "setExtraOptions"u8;
    private static ReadOnlySpan<byte> _getLocalAddress => "getLocalAddress"u8;
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    private static ReadOnlySpan<byte> _getSocketFd => "getSocketFd"u8;
    /// <summary>
    /// listen
    /// </summary>
    public Task ListenAsync(NetAddress address)
    {
        return CallMethodAsyncVoid(_listen, address);
    }

    /// <summary>
    /// close
    /// </summary>
    public Task CloseAsync()
    {
        return CallMethodAsyncVoid(_close);
    }

    /// <summary>
    /// getState
    /// </summary>
    public Task<SocketStateBase> GetStateAsync()
    {
        return CallMethodAsync(_getState, static h => new SocketStateBase(h));
    }

    /// <summary>
    /// setExtraOptions
    /// </summary>
    public Task SetExtraOptionsAsync(IntPtr options)
    {
        return CallMethodAsyncVoid(_setExtraOptions, options);
    }

    /// <summary>
    /// getLocalAddress
    /// </summary>
    public Task<NetAddress> GetLocalAddressAsync()
    {
        return CallMethodAsync<NetAddress>(_getLocalAddress);
    }

    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    /// <summary>
    /// getSocketFd
    /// </summary>
    public Task<double> GetSocketFdAsync()
    {
        return CallMethodAsync<double>(_getSocketFd);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action<TCPSocketConnection> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(new TCPSocketConnection(args[0])),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action<TCPSocketConnection> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 connect 事件（对应 on/off）
    /// </summary>
    public event System.Action<TCPSocketConnection> Connect
    {
        add
        {
            _eventListeners.Add(("connect", value),
                args => value(new TCPSocketConnection(args[0])),
                js => NodeApi.CallMethodVoid(Handle, _on, "connect", js));
        }
        remove
        {
            _eventListeners.Remove(("connect", value), js => NodeApi.CallMethodVoid(Handle, _off, "connect", js));
        }
    }

    /// <summary>
    /// 监听 error 事件（对应 on/off）
    /// </summary>
    public event System.Action Error
    {
        add
        {
            _eventListeners.Add(("error", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "error", js));
        }
        remove
        {
            _eventListeners.Remove(("error", value), js => NodeApi.CallMethodVoid(Handle, _off, "error", js));
        }
    }

}

/// <summary>
/// TLSSocketServer 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class TLSSocketServer : JsObject
{
    public TLSSocketServer(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _listen => "listen"u8;
    private static ReadOnlySpan<byte> _close => "close"u8;
    private static ReadOnlySpan<byte> _getState => "getState"u8;
    private static ReadOnlySpan<byte> _setExtraOptions => "setExtraOptions"u8;
    private static ReadOnlySpan<byte> _getCertificate => "getCertificate"u8;
    private static ReadOnlySpan<byte> _getProtocol => "getProtocol"u8;
    private static ReadOnlySpan<byte> _getLocalAddress => "getLocalAddress"u8;
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    private static ReadOnlySpan<byte> _getSocketFd => "getSocketFd"u8;
    /// <summary>
    /// listen
    /// </summary>
    public Task ListenAsync(IntPtr options)
    {
        return CallMethodAsyncVoid(_listen, options);
    }

    /// <summary>
    /// close
    /// </summary>
    public Task CloseAsync()
    {
        return CallMethodAsyncVoid(_close);
    }

    /// <summary>
    /// getState
    /// </summary>
    public Task<SocketStateBase> GetStateAsync()
    {
        return CallMethodAsync(_getState, static h => new SocketStateBase(h));
    }

    /// <summary>
    /// setExtraOptions
    /// </summary>
    public Task SetExtraOptionsAsync(IntPtr options)
    {
        return CallMethodAsyncVoid(_setExtraOptions, options);
    }

    /// <summary>
    /// getCertificate
    /// </summary>
    public Task<IntPtr> GetCertificateAsync()
    {
        return CallMethodAsync<IntPtr>(_getCertificate);
    }

    /// <summary>
    /// getProtocol
    /// </summary>
    public Task<string> GetProtocolAsync()
    {
        return CallMethodAsync<string>(_getProtocol);
    }

    /// <summary>
    /// getLocalAddress
    /// </summary>
    public Task<NetAddress> GetLocalAddressAsync()
    {
        return CallMethodAsync<NetAddress>(_getLocalAddress);
    }

    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    /// <summary>
    /// getSocketFd
    /// </summary>
    public Task<double> GetSocketFdAsync()
    {
        return CallMethodAsync<double>(_getSocketFd);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action<TLSSocketConnection> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(new TLSSocketConnection(args[0])),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action<TLSSocketConnection> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 connect 事件（对应 on/off）
    /// </summary>
    public event System.Action<TLSSocketConnection> Connect
    {
        add
        {
            _eventListeners.Add(("connect", value),
                args => value(new TLSSocketConnection(args[0])),
                js => NodeApi.CallMethodVoid(Handle, _on, "connect", js));
        }
        remove
        {
            _eventListeners.Remove(("connect", value), js => NodeApi.CallMethodVoid(Handle, _off, "connect", js));
        }
    }

    /// <summary>
    /// 监听 error 事件（对应 on/off）
    /// </summary>
    public event System.Action Error
    {
        add
        {
            _eventListeners.Add(("error", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "error", js));
        }
        remove
        {
            _eventListeners.Remove(("error", value), js => NodeApi.CallMethodVoid(Handle, _off, "error", js));
        }
    }

}

/// <summary>
/// LocalSocket 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class LocalSocket : JsObject
{
    public LocalSocket(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _bind => "bind"u8;
    private static ReadOnlySpan<byte> _connect => "connect"u8;
    private static ReadOnlySpan<byte> _send => "send"u8;
    private static ReadOnlySpan<byte> _close => "close"u8;
    private static ReadOnlySpan<byte> _getState => "getState"u8;
    private static ReadOnlySpan<byte> _getSocketFd => "getSocketFd"u8;
    private static ReadOnlySpan<byte> _setExtraOptions => "setExtraOptions"u8;
    private static ReadOnlySpan<byte> _getExtraOptions => "getExtraOptions"u8;
    private static ReadOnlySpan<byte> _getLocalAddress => "getLocalAddress"u8;
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    /// <summary>
    /// bind
    /// </summary>
    public Task BindAsync(LocalAddress address)
    {
        return CallMethodAsyncVoid(_bind, address);
    }

    /// <summary>
    /// connect
    /// </summary>
    public Task ConnectAsync(LocalConnectOptions options)
    {
        return CallMethodAsyncVoid(_connect, options);
    }

    /// <summary>
    /// send
    /// </summary>
    public Task SendAsync(LocalSendOptions options)
    {
        return CallMethodAsyncVoid(_send, options);
    }

    /// <summary>
    /// close
    /// </summary>
    public Task CloseAsync()
    {
        return CallMethodAsyncVoid(_close);
    }

    /// <summary>
    /// getState
    /// </summary>
    public Task<SocketStateBase> GetStateAsync()
    {
        return CallMethodAsync(_getState, static h => new SocketStateBase(h));
    }

    /// <summary>
    /// getSocketFd
    /// </summary>
    public Task<double> GetSocketFdAsync()
    {
        return CallMethodAsync<double>(_getSocketFd);
    }

    /// <summary>
    /// setExtraOptions
    /// </summary>
    public Task SetExtraOptionsAsync(ExtraOptionsBase options)
    {
        return CallMethodAsyncVoid(_setExtraOptions, options);
    }

    /// <summary>
    /// getExtraOptions
    /// </summary>
    public Task<ExtraOptionsBase> GetExtraOptionsAsync()
    {
        return CallMethodAsync(_getExtraOptions, static h => new ExtraOptionsBase(h));
    }

    /// <summary>
    /// getLocalAddress
    /// </summary>
    public Task<string> GetLocalAddressAsync()
    {
        return CallMethodAsync<string>(_getLocalAddress);
    }

    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action<LocalSocketMessageInfo> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(new LocalSocketMessageInfo(args[0])),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action<LocalSocketMessageInfo> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 message 事件（对应 on/off）
    /// </summary>
    public event System.Action<LocalSocketMessageInfo> Message
    {
        add
        {
            _eventListeners.Add(("message", value),
                args => value(new LocalSocketMessageInfo(args[0])),
                js => NodeApi.CallMethodVoid(Handle, _on, "message", js));
        }
        remove
        {
            _eventListeners.Remove(("message", value), js => NodeApi.CallMethodVoid(Handle, _off, "message", js));
        }
    }

    /// <summary>
    /// 监听 connect 事件（对应 on/off）
    /// </summary>
    public event System.Action ConnectEvent
    {
        add
        {
            _eventListeners.Add(("connect", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "connect", js));
        }
        remove
        {
            _eventListeners.Remove(("connect", value), js => NodeApi.CallMethodVoid(Handle, _off, "connect", js));
        }
    }

    /// <summary>
    /// 监听 close 事件（对应 on/off）
    /// </summary>
    public event System.Action CloseEvent
    {
        add
        {
            _eventListeners.Add(("close", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "close", js));
        }
        remove
        {
            _eventListeners.Remove(("close", value), js => NodeApi.CallMethodVoid(Handle, _off, "close", js));
        }
    }

    /// <summary>
    /// 监听 error 事件（对应 on/off）
    /// </summary>
    public event System.Action Error
    {
        add
        {
            _eventListeners.Add(("error", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "error", js));
        }
        remove
        {
            _eventListeners.Remove(("error", value), js => NodeApi.CallMethodVoid(Handle, _off, "error", js));
        }
    }

}

/// <summary>
/// LocalSocketServer 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class LocalSocketServer : JsObject
{
    public LocalSocketServer(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _listen => "listen"u8;
    private static ReadOnlySpan<byte> _getState => "getState"u8;
    private static ReadOnlySpan<byte> _setExtraOptions => "setExtraOptions"u8;
    private static ReadOnlySpan<byte> _getExtraOptions => "getExtraOptions"u8;
    private static ReadOnlySpan<byte> _getLocalAddress => "getLocalAddress"u8;
    private static ReadOnlySpan<byte> _close => "close"u8;
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    private static ReadOnlySpan<byte> _getSocketFd => "getSocketFd"u8;
    /// <summary>
    /// listen
    /// </summary>
    public Task ListenAsync(LocalAddress address)
    {
        return CallMethodAsyncVoid(_listen, address);
    }

    /// <summary>
    /// getState
    /// </summary>
    public Task<SocketStateBase> GetStateAsync()
    {
        return CallMethodAsync(_getState, static h => new SocketStateBase(h));
    }

    /// <summary>
    /// setExtraOptions
    /// </summary>
    public Task SetExtraOptionsAsync(ExtraOptionsBase options)
    {
        return CallMethodAsyncVoid(_setExtraOptions, options);
    }

    /// <summary>
    /// getExtraOptions
    /// </summary>
    public Task<ExtraOptionsBase> GetExtraOptionsAsync()
    {
        return CallMethodAsync(_getExtraOptions, static h => new ExtraOptionsBase(h));
    }

    /// <summary>
    /// getLocalAddress
    /// </summary>
    public Task<string> GetLocalAddressAsync()
    {
        return CallMethodAsync<string>(_getLocalAddress);
    }

    /// <summary>
    /// close
    /// </summary>
    public Task CloseAsync()
    {
        return CallMethodAsyncVoid(_close);
    }

    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    /// <summary>
    /// getSocketFd
    /// </summary>
    public Task<double> GetSocketFdAsync()
    {
        return CallMethodAsync<double>(_getSocketFd);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action<LocalSocketConnection> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(new LocalSocketConnection(args[0])),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action<LocalSocketConnection> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 connect 事件（对应 on/off）
    /// </summary>
    public event System.Action<LocalSocketConnection> Connect
    {
        add
        {
            _eventListeners.Add(("connect", value),
                args => value(new LocalSocketConnection(args[0])),
                js => NodeApi.CallMethodVoid(Handle, _on, "connect", js));
        }
        remove
        {
            _eventListeners.Remove(("connect", value), js => NodeApi.CallMethodVoid(Handle, _off, "connect", js));
        }
    }

    /// <summary>
    /// 监听 error 事件（对应 on/off）
    /// </summary>
    public event System.Action Error
    {
        add
        {
            _eventListeners.Add(("error", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "error", js));
        }
        remove
        {
            _eventListeners.Remove(("error", value), js => NodeApi.CallMethodVoid(Handle, _off, "error", js));
        }
    }

}

/// <summary>
/// SocketMessageInfo 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class SocketMessageInfo : JsObject
{
    public SocketMessageInfo(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _message => "message"u8;
    private static ReadOnlySpan<byte> _remoteInfo => "remoteInfo"u8;
    /// <summary>
    /// message
    /// </summary>
    public byte[] Message => ValueConverter.ConvertArray(GetPropertyRaw(_message), static e => ValueConverter.Convert<byte>(e));

    /// <summary>
    /// remoteInfo
    /// </summary>
    public SocketRemoteInfo RemoteInfo => new SocketRemoteInfo(GetPropertyRaw(_remoteInfo));

}

/// <summary>
/// LocalSocketMessageInfo 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class LocalSocketMessageInfo : JsObject
{
    public LocalSocketMessageInfo(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _message => "message"u8;
    private static ReadOnlySpan<byte> _address => "address"u8;
    private static ReadOnlySpan<byte> _size => "size"u8;
    /// <summary>
    /// message
    /// </summary>
    public byte[] Message => ValueConverter.ConvertArray(GetPropertyRaw(_message), static e => ValueConverter.Convert<byte>(e));

    /// <summary>
    /// address
    /// </summary>
    public string Address => NativeValue.ToString(GetPropertyRaw(_address)) ?? string.Empty;

    /// <summary>
    /// size
    /// </summary>
    public double Size => NativeValue.ToDouble(GetPropertyRaw(_size));

}

/// <summary>
/// LocalSocketConnection 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class LocalSocketConnection : JsObject
{
    public LocalSocketConnection(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _clientId => "clientId"u8;
    private static ReadOnlySpan<byte> _send => "send"u8;
    private static ReadOnlySpan<byte> _close => "close"u8;
    private static ReadOnlySpan<byte> _getLocalAddress => "getLocalAddress"u8;
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    private static ReadOnlySpan<byte> _getSocketFd => "getSocketFd"u8;
    /// <summary>
    /// clientId
    /// </summary>
    public double ClientId => NativeValue.ToDouble(GetPropertyRaw(_clientId));

    /// <summary>
    /// send
    /// </summary>
    public Task SendAsync(LocalSendOptions options)
    {
        return CallMethodAsyncVoid(_send, options);
    }

    /// <summary>
    /// close
    /// </summary>
    public Task CloseAsync()
    {
        return CallMethodAsyncVoid(_close);
    }

    /// <summary>
    /// getLocalAddress
    /// </summary>
    public Task<string> GetLocalAddressAsync()
    {
        return CallMethodAsync<string>(_getLocalAddress);
    }

    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    /// <summary>
    /// getSocketFd
    /// </summary>
    public Task<double> GetSocketFdAsync()
    {
        return CallMethodAsync<double>(_getSocketFd);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action<LocalSocketMessageInfo> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(new LocalSocketMessageInfo(args[0])),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action<LocalSocketMessageInfo> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 message 事件（对应 on/off）
    /// </summary>
    public event System.Action<LocalSocketMessageInfo> Message
    {
        add
        {
            _eventListeners.Add(("message", value),
                args => value(new LocalSocketMessageInfo(args[0])),
                js => NodeApi.CallMethodVoid(Handle, _on, "message", js));
        }
        remove
        {
            _eventListeners.Remove(("message", value), js => NodeApi.CallMethodVoid(Handle, _off, "message", js));
        }
    }

    /// <summary>
    /// 监听 close 事件（对应 on/off）
    /// </summary>
    public event System.Action CloseEvent
    {
        add
        {
            _eventListeners.Add(("close", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "close", js));
        }
        remove
        {
            _eventListeners.Remove(("close", value), js => NodeApi.CallMethodVoid(Handle, _off, "close", js));
        }
    }

    /// <summary>
    /// 监听 error 事件（对应 on/off）
    /// </summary>
    public event System.Action Error
    {
        add
        {
            _eventListeners.Add(("error", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "error", js));
        }
        remove
        {
            _eventListeners.Remove(("error", value), js => NodeApi.CallMethodVoid(Handle, _off, "error", js));
        }
    }

}

/// <summary>
/// TCPSocketConnection 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class TCPSocketConnection : JsObject
{
    public TCPSocketConnection(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _clientId => "clientId"u8;
    private static ReadOnlySpan<byte> _send => "send"u8;
    private static ReadOnlySpan<byte> _close => "close"u8;
    private static ReadOnlySpan<byte> _getRemoteAddress => "getRemoteAddress"u8;
    private static ReadOnlySpan<byte> _getLocalAddress => "getLocalAddress"u8;
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    private static ReadOnlySpan<byte> _getSocketFd => "getSocketFd"u8;
    /// <summary>
    /// clientId
    /// </summary>
    public double ClientId => NativeValue.ToDouble(GetPropertyRaw(_clientId));

    /// <summary>
    /// send
    /// </summary>
    public Task SendAsync(TCPSendOptions options)
    {
        return CallMethodAsyncVoid(_send, options);
    }

    /// <summary>
    /// close
    /// </summary>
    public Task CloseAsync()
    {
        return CallMethodAsyncVoid(_close);
    }

    /// <summary>
    /// getRemoteAddress
    /// </summary>
    public Task<NetAddress> GetRemoteAddressAsync()
    {
        return CallMethodAsync<NetAddress>(_getRemoteAddress);
    }

    /// <summary>
    /// getLocalAddress
    /// </summary>
    public Task<NetAddress> GetLocalAddressAsync()
    {
        return CallMethodAsync<NetAddress>(_getLocalAddress);
    }

    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    /// <summary>
    /// getSocketFd
    /// </summary>
    public Task<double> GetSocketFdAsync()
    {
        return CallMethodAsync<double>(_getSocketFd);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action<SocketMessageInfo> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(new SocketMessageInfo(args[0])),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action<SocketMessageInfo> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 message 事件（对应 on/off）
    /// </summary>
    public event System.Action<SocketMessageInfo> Message
    {
        add
        {
            _eventListeners.Add(("message", value),
                args => value(new SocketMessageInfo(args[0])),
                js => NodeApi.CallMethodVoid(Handle, _on, "message", js));
        }
        remove
        {
            _eventListeners.Remove(("message", value), js => NodeApi.CallMethodVoid(Handle, _off, "message", js));
        }
    }

    /// <summary>
    /// 监听 close 事件（对应 on/off）
    /// </summary>
    public event System.Action CloseEvent
    {
        add
        {
            _eventListeners.Add(("close", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "close", js));
        }
        remove
        {
            _eventListeners.Remove(("close", value), js => NodeApi.CallMethodVoid(Handle, _off, "close", js));
        }
    }

    /// <summary>
    /// 监听 error 事件（对应 on/off）
    /// </summary>
    public event System.Action Error
    {
        add
        {
            _eventListeners.Add(("error", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "error", js));
        }
        remove
        {
            _eventListeners.Remove(("error", value), js => NodeApi.CallMethodVoid(Handle, _off, "error", js));
        }
    }

}

/// <summary>
/// TLSSocketConnection 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class TLSSocketConnection : JsObject
{
    public TLSSocketConnection(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _clientId => "clientId"u8;
    private static ReadOnlySpan<byte> _send => "send"u8;
    private static ReadOnlySpan<byte> _close => "close"u8;
    private static ReadOnlySpan<byte> _getRemoteAddress => "getRemoteAddress"u8;
    private static ReadOnlySpan<byte> _getRemoteCertificate => "getRemoteCertificate"u8;
    private static ReadOnlySpan<byte> _getCipherSuite => "getCipherSuite"u8;
    private static ReadOnlySpan<byte> _getSignatureAlgorithms => "getSignatureAlgorithms"u8;
    private static ReadOnlySpan<byte> _getLocalAddress => "getLocalAddress"u8;
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;
    private static ReadOnlySpan<byte> _getSocketFd => "getSocketFd"u8;
    /// <summary>
    /// clientId
    /// </summary>
    public double ClientId => NativeValue.ToDouble(GetPropertyRaw(_clientId));

    /// <summary>
    /// send
    /// </summary>
    public Task SendAsync(string data)
    {
        return CallMethodAsyncVoid(_send, data);
    }

    /// <summary>
    /// close
    /// </summary>
    public Task CloseAsync()
    {
        return CallMethodAsyncVoid(_close);
    }

    /// <summary>
    /// getRemoteAddress
    /// </summary>
    public Task<NetAddress> GetRemoteAddressAsync()
    {
        return CallMethodAsync<NetAddress>(_getRemoteAddress);
    }

    /// <summary>
    /// getRemoteCertificate
    /// </summary>
    public Task<IntPtr> GetRemoteCertificateAsync()
    {
        return CallMethodAsync<IntPtr>(_getRemoteCertificate);
    }

    /// <summary>
    /// getCipherSuite
    /// </summary>
    public Task<string[]> GetCipherSuiteAsync()
    {
        return CallMethodAsync(_getCipherSuite, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<string>(e)));
    }

    /// <summary>
    /// getSignatureAlgorithms
    /// </summary>
    public Task<string[]> GetSignatureAlgorithmsAsync()
    {
        return CallMethodAsync(_getSignatureAlgorithms, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<string>(e)));
    }

    /// <summary>
    /// getLocalAddress
    /// </summary>
    public Task<NetAddress> GetLocalAddressAsync()
    {
        return CallMethodAsync<NetAddress>(_getLocalAddress);
    }

    /// <summary>
    /// on
    /// </summary>
    public void On(string type, IntPtr callback)
    {
        CallMethodVoid(_on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public void Off(string type, IntPtr callback)
    {
        CallMethodVoid(_off, type, callback);
    }

    /// <summary>
    /// getSocketFd
    /// </summary>
    public Task<double> GetSocketFdAsync()
    {
        return CallMethodAsync<double>(_getSocketFd);
    }

    private readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action<SocketMessageInfo> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(new SocketMessageInfo(args[0])),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public void Off(string type)
    {
        NodeApi.CallMethodVoid(Handle, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action<SocketMessageInfo> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public void On(string type, System.Action callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(),
            js => NodeApi.CallMethodVoid(Handle, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public void Off(string type, System.Action callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Handle, _off, type, js));
    }

    /// <summary>
    /// 监听 message 事件（对应 on/off）
    /// </summary>
    public event System.Action<SocketMessageInfo> Message
    {
        add
        {
            _eventListeners.Add(("message", value),
                args => value(new SocketMessageInfo(args[0])),
                js => NodeApi.CallMethodVoid(Handle, _on, "message", js));
        }
        remove
        {
            _eventListeners.Remove(("message", value), js => NodeApi.CallMethodVoid(Handle, _off, "message", js));
        }
    }

    /// <summary>
    /// 监听 close 事件（对应 on/off）
    /// </summary>
    public event System.Action CloseEvent
    {
        add
        {
            _eventListeners.Add(("close", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "close", js));
        }
        remove
        {
            _eventListeners.Remove(("close", value), js => NodeApi.CallMethodVoid(Handle, _off, "close", js));
        }
    }

    /// <summary>
    /// 监听 error 事件（对应 on/off）
    /// </summary>
    public event System.Action Error
    {
        add
        {
            _eventListeners.Add(("error", value),
                args => value(),
                js => NodeApi.CallMethodVoid(Handle, _on, "error", js));
        }
        remove
        {
            _eventListeners.Remove(("error", value), js => NodeApi.CallMethodVoid(Handle, _off, "error", js));
        }
    }

}

/// <summary>
/// SocketStateBase 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class SocketStateBase : JsObject
{
    public SocketStateBase(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _isBound => "isBound"u8;
    private static ReadOnlySpan<byte> _isClose => "isClose"u8;
    private static ReadOnlySpan<byte> _isConnected => "isConnected"u8;
    /// <summary>
    /// isBound
    /// </summary>
    public bool IsBound => NativeValue.ToBool(GetPropertyRaw(_isBound));

    /// <summary>
    /// isClose
    /// </summary>
    public bool IsClose => NativeValue.ToBool(GetPropertyRaw(_isClose));

    /// <summary>
    /// isConnected
    /// </summary>
    public bool IsConnected => NativeValue.ToBool(GetPropertyRaw(_isConnected));

}

/// <summary>
/// UDPExtraOptions（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record UDPExtraOptions(
    double? ReceiveBufferSize = null,
    double? SendBufferSize = null,
    bool? ReuseAddress = null,
    double? SocketTimeout = null,
    bool? Broadcast = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _receiveBufferSize = System.Text.Encoding.UTF8.GetBytes("receiveBufferSize");
        var _receiveBufferSizeV = NativeValue.From(ReceiveBufferSize);
        if (_receiveBufferSizeV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _receiveBufferSize, _receiveBufferSizeV);
        var _sendBufferSize = System.Text.Encoding.UTF8.GetBytes("sendBufferSize");
        var _sendBufferSizeV = NativeValue.From(SendBufferSize);
        if (_sendBufferSizeV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _sendBufferSize, _sendBufferSizeV);
        var _reuseAddress = System.Text.Encoding.UTF8.GetBytes("reuseAddress");
        var _reuseAddressV = NativeValue.From(ReuseAddress);
        if (_reuseAddressV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _reuseAddress, _reuseAddressV);
        var _socketTimeout = System.Text.Encoding.UTF8.GetBytes("socketTimeout");
        var _socketTimeoutV = NativeValue.From(SocketTimeout);
        if (_socketTimeoutV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _socketTimeout, _socketTimeoutV);
        var _broadcast = System.Text.Encoding.UTF8.GetBytes("broadcast");
        var _broadcastV = NativeValue.From(Broadcast);
        if (_broadcastV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _broadcast, _broadcastV);
    }
}

/// <summary>
/// TCPSendOptions（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record TCPSendOptions(
    string Data,
    string? Encoding = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _data = System.Text.Encoding.UTF8.GetBytes("data");
        var _dataV = NativeValue.From(Data);
        if (_dataV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _data, _dataV);
        var _encoding = System.Text.Encoding.UTF8.GetBytes("encoding");
        var _encodingV = NativeValue.From(Encoding);
        if (_encodingV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _encoding, _encodingV);
    }
}

/// <summary>
/// LocalAddress（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record LocalAddress(
    string Address
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _address = System.Text.Encoding.UTF8.GetBytes("address");
        var _addressV = NativeValue.From(Address);
        if (_addressV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _address, _addressV);
    }
}

/// <summary>
/// LocalConnectOptions（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record LocalConnectOptions(
    LocalAddress Address,
    double? Timeout = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _address = System.Text.Encoding.UTF8.GetBytes("address");
        var _addressV = NativeValue.From(Address);
        if (_addressV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _address, _addressV);
        var _timeout = System.Text.Encoding.UTF8.GetBytes("timeout");
        var _timeoutV = NativeValue.From(Timeout);
        if (_timeoutV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _timeout, _timeoutV);
    }
}

/// <summary>
/// LocalSendOptions（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record LocalSendOptions(
    string Data,
    string? Encoding = null
) : INapiRecord
{
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _data = System.Text.Encoding.UTF8.GetBytes("data");
        var _dataV = NativeValue.From(Data);
        if (_dataV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _data, _dataV);
        var _encoding = System.Text.Encoding.UTF8.GetBytes("encoding");
        var _encodingV = NativeValue.From(Encoding);
        if (_encodingV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _encoding, _encodingV);
    }
}

/// <summary>
/// ExtraOptionsBase 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class ExtraOptionsBase : JsObject
{
    public ExtraOptionsBase(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _receiveBufferSize => "receiveBufferSize"u8;
    private static ReadOnlySpan<byte> _sendBufferSize => "sendBufferSize"u8;
    private static ReadOnlySpan<byte> _reuseAddress => "reuseAddress"u8;
    private static ReadOnlySpan<byte> _socketTimeout => "socketTimeout"u8;
    /// <summary>
    /// receiveBufferSize
    /// </summary>
    public double? ReceiveBufferSize => (double?)NativeValue.ToDouble(GetPropertyRaw(_receiveBufferSize));

    /// <summary>
    /// sendBufferSize
    /// </summary>
    public double? SendBufferSize => (double?)NativeValue.ToDouble(GetPropertyRaw(_sendBufferSize));

    /// <summary>
    /// reuseAddress
    /// </summary>
    public bool? ReuseAddress => (bool?)NativeValue.ToBool(GetPropertyRaw(_reuseAddress));

    /// <summary>
    /// socketTimeout
    /// </summary>
    public double? SocketTimeout => (double?)NativeValue.ToDouble(GetPropertyRaw(_socketTimeout));

}

/// <summary>
/// SocketRemoteInfo 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class SocketRemoteInfo : JsObject
{
    public SocketRemoteInfo(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _address => "address"u8;
    private static ReadOnlySpan<byte> _family => "family"u8;
    private static ReadOnlySpan<byte> _port => "port"u8;
    private static ReadOnlySpan<byte> _size => "size"u8;
    /// <summary>
    /// address
    /// </summary>
    public string Address => NativeValue.ToString(GetPropertyRaw(_address)) ?? string.Empty;

    /// <summary>
    /// family
    /// </summary>
    public string Family => NativeValue.ToString(GetPropertyRaw(_family)) ?? string.Empty;

    /// <summary>
    /// port
    /// </summary>
    public double Port => NativeValue.ToDouble(GetPropertyRaw(_port));

    /// <summary>
    /// size
    /// </summary>
    public double Size => NativeValue.ToDouble(GetPropertyRaw(_size));

}
