// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// PartnerAgent 绑定（@ohos.FusionConnectivity.partnerAgent）。
/// 所需权限：ohos.permission.ACCESS_BLUETOOTH
/// </summary>
public static unsafe partial class PartnerAgent
{
    private const string ModuleName = "@ohos.FusionConnectivity.partnerAgent";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[FusionConnectivity.partnerAgent] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _isPartnerAgentSupported => "isPartnerAgentSupported"u8;
    private static ReadOnlySpan<byte> _bindDevice => "bindDevice"u8;
    private static ReadOnlySpan<byte> _unbindDevice => "unbindDevice"u8;
    private static ReadOnlySpan<byte> _isDeviceBound => "isDeviceBound"u8;
    private static ReadOnlySpan<byte> _getBoundDevices => "getBoundDevices"u8;
    private static ReadOnlySpan<byte> _isDeviceControlEnabled => "isDeviceControlEnabled"u8;

    /// <summary>
    /// isPartnerAgentSupported
    /// </summary>
    public static bool IsPartnerAgentSupported()
    {
        return NodeApi.CallMethod<bool>(Module, _isPartnerAgentSupported);
    }

    /// <summary>
    /// bindDevice
    /// </summary>
    public static Task BindDeviceAsync(IntPtr deviceAddress, DeviceCapability deviceCapability, BusinessCapability businessCapability, string partnerAgentExtensionAbilityName)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _bindDevice, deviceAddress, deviceCapability, businessCapability, partnerAgentExtensionAbilityName);
    }

    /// <summary>
    /// unbindDevice
    /// </summary>
    public static Task UnbindDeviceAsync(IntPtr deviceAddress)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _unbindDevice, deviceAddress);
    }

    /// <summary>
    /// isDeviceBound
    /// </summary>
    public static bool IsDeviceBound(IntPtr deviceAddress)
    {
        return NodeApi.CallMethod<bool>(Module, _isDeviceBound, deviceAddress);
    }

    /// <summary>
    /// getBoundDevices
    /// </summary>
    public static IntPtr[] GetBoundDevices()
    {
        return NodeApi.CallMethod(Module, _getBoundDevices, h => ValueConverter.ConvertArray(h, static e => ValueConverter.Convert<IntPtr>(e)));
    }

    /// <summary>
    /// isDeviceControlEnabled
    /// </summary>
    public static bool IsDeviceControlEnabled(IntPtr deviceAddress)
    {
        return NodeApi.CallMethod<bool>(Module, _isDeviceControlEnabled, deviceAddress);
    }

}

/// <summary>
/// DeviceCapability（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record DeviceCapability(
    bool? SupportBr = null,
    bool? SupportBleAdvertiser = null
) : INapiRecord
{
    private static ReadOnlySpan<byte> _supportBrName => "supportBR"u8;
    private static ReadOnlySpan<byte> _supportBleAdvertiserName => "supportBleAdvertiser"u8;
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _supportBrV = NativeValue.From(SupportBr);
        if (_supportBrV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _supportBrName, _supportBrV);
        var _supportBleAdvertiserV = NativeValue.From(SupportBleAdvertiser);
        if (_supportBleAdvertiserV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _supportBleAdvertiserName, _supportBleAdvertiserV);
    }
}

/// <summary>
/// BusinessCapability（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record BusinessCapability(
    bool? SupportMediaControl = null,
    bool? SupportTelephonyControl = null
) : INapiRecord
{
    private static ReadOnlySpan<byte> _supportMediaControlName => "supportMediaControl"u8;
    private static ReadOnlySpan<byte> _supportTelephonyControlName => "supportTelephonyControl"u8;
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _supportMediaControlV = NativeValue.From(SupportMediaControl);
        if (_supportMediaControlV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _supportMediaControlName, _supportMediaControlV);
        var _supportTelephonyControlV = NativeValue.From(SupportTelephonyControl);
        if (_supportTelephonyControlV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _supportTelephonyControlName, _supportTelephonyControlV);
    }
}
