// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// ResourcescheduleBackgroundTaskManager 绑定（@ohos.resourceschedule.backgroundTaskManager）。
/// 所需权限：ohos.permission.KEEP_BACKGROUND_RUNNING
/// </summary>
public static unsafe partial class ResourcescheduleBackgroundTaskManager
{
    private const string ModuleName = "@ohos.resourceschedule.backgroundTaskManager";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[resourceschedule.backgroundTaskManager] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _cancelSuspendDelay => "cancelSuspendDelay"u8;
    private static ReadOnlySpan<byte> _getRemainingDelayTime => "getRemainingDelayTime"u8;
    private static ReadOnlySpan<byte> _requestSuspendDelay => "requestSuspendDelay"u8;
    private static ReadOnlySpan<byte> _getTransientTaskInfo => "getTransientTaskInfo"u8;
    private static ReadOnlySpan<byte> _startBackgroundRunning => "startBackgroundRunning"u8;
    private static ReadOnlySpan<byte> _updateBackgroundRunning => "updateBackgroundRunning"u8;
    private static ReadOnlySpan<byte> _stopBackgroundRunning => "stopBackgroundRunning"u8;
    private static ReadOnlySpan<byte> _getAllContinuousTasks => "getAllContinuousTasks"u8;
    private static ReadOnlySpan<byte> _on => "on"u8;
    private static ReadOnlySpan<byte> _off => "off"u8;

    /// <summary>
    /// cancelSuspendDelay
    /// </summary>
    public static void CancelSuspendDelay(double requestId)
    {
        NodeApi.CallMethodVoid(Module, _cancelSuspendDelay, requestId);
    }

    /// <summary>
    /// getRemainingDelayTime
    /// </summary>
    public static Task<double> GetRemainingDelayTimeAsync(double requestId)
    {
        return NodeApi.CallMethodAsync<double>(Module, _getRemainingDelayTime, requestId);
    }

    /// <summary>
    /// requestSuspendDelay
    /// </summary>
    public static ResourcescheduleBackgroundTaskManagerDelaySuspendInfo RequestSuspendDelay(string reason, IntPtr callback)
    {
        return NodeApi.CallMethod(Module, _requestSuspendDelay, static h => new ResourcescheduleBackgroundTaskManagerDelaySuspendInfo(h), reason, callback);
    }

    /// <summary>
    /// getTransientTaskInfo
    /// </summary>
    public static Task<IntPtr> GetTransientTaskInfoAsync()
    {
        return NodeApi.CallMethodAsync<IntPtr>(Module, _getTransientTaskInfo);
    }

    /// <summary>
    /// startBackgroundRunning
    /// </summary>
    public static Task StartBackgroundRunningAsync(IntPtr context, global::HarmonyOS.ArkUI.BackgroundMode bgMode, IntPtr wantAgent)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _startBackgroundRunning, context, bgMode, wantAgent);
    }

    /// <summary>
    /// startBackgroundRunning
    /// </summary>
    public static Task<IntPtr> StartBackgroundRunningAsync(IntPtr context, string[] bgModes, IntPtr wantAgent)
    {
        return NodeApi.CallMethodAsync<IntPtr>(Module, _startBackgroundRunning, context, bgModes, wantAgent);
    }

    /// <summary>
    /// startBackgroundRunning
    /// </summary>
    public static Task<IntPtr> StartBackgroundRunningAsync(IntPtr context, ContinuousTaskRequest request)
    {
        return NodeApi.CallMethodAsync<IntPtr>(Module, _startBackgroundRunning, context, request);
    }

    /// <summary>
    /// updateBackgroundRunning
    /// </summary>
    public static Task<IntPtr> UpdateBackgroundRunningAsync(IntPtr context, string[] bgModes)
    {
        return NodeApi.CallMethodAsync<IntPtr>(Module, _updateBackgroundRunning, context, bgModes);
    }

    /// <summary>
    /// updateBackgroundRunning
    /// </summary>
    public static Task<IntPtr> UpdateBackgroundRunningAsync(IntPtr context, ContinuousTaskRequest request)
    {
        return NodeApi.CallMethodAsync<IntPtr>(Module, _updateBackgroundRunning, context, request);
    }

    /// <summary>
    /// stopBackgroundRunning
    /// </summary>
    public static Task StopBackgroundRunningAsync(IntPtr context)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _stopBackgroundRunning, context);
    }

    /// <summary>
    /// stopBackgroundRunning
    /// </summary>
    public static Task StopBackgroundRunningAsync(IntPtr context, double continuousTaskId)
    {
        return NodeApi.CallMethodAsyncVoid(Module, _stopBackgroundRunning, context, continuousTaskId);
    }

    /// <summary>
    /// getAllContinuousTasks
    /// </summary>
    public static Task<ContinuousTaskInfo[]> GetAllContinuousTasksAsync(IntPtr context)
    {
        return NodeApi.CallMethodAsync(Module, _getAllContinuousTasks, h => ValueConverter.ConvertArray(h, static e => new ContinuousTaskInfo(e)), context);
    }

    /// <summary>
    /// getAllContinuousTasks
    /// </summary>
    public static Task<ContinuousTaskInfo[]> GetAllContinuousTasksAsync(IntPtr context, bool includeSuspended)
    {
        return NodeApi.CallMethodAsync(Module, _getAllContinuousTasks, h => ValueConverter.ConvertArray(h, static e => new ContinuousTaskInfo(e)), context, includeSuspended);
    }

    /// <summary>
    /// on
    /// </summary>
    public static void On(string type, IntPtr callback)
    {
        NodeApi.CallMethodVoid(Module, _on, type, callback);
    }

    /// <summary>
    /// off
    /// </summary>
    public static void Off(string type, IntPtr callback)
    {
        NodeApi.CallMethodVoid(Module, _off, type, callback);
    }

    private static readonly EventListenerRegistry _eventListeners = new();

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public static void On(string type, System.Action<ContinuousTaskCancelInfo> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(new ContinuousTaskCancelInfo(args[0])),
            js => NodeApi.CallMethodVoid(Module, _on, type, js));
    }

    /// <summary>
    /// off(type)：移除该事件类型的全部回调
    /// </summary>
    public static void Off(string type)
    {
        NodeApi.CallMethodVoid(Module, _off, type);
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public static void Off(string type, System.Action<ContinuousTaskCancelInfo> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Module, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public static void On(string type, System.Action<ContinuousTaskSuspendInfo> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(new ContinuousTaskSuspendInfo(args[0])),
            js => NodeApi.CallMethodVoid(Module, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public static void Off(string type, System.Action<ContinuousTaskSuspendInfo> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Module, _off, type, js));
    }

    /// <summary>
    /// on(type, callback) 的类型化重载（回调经共享跳板进入 C#，任意参数类型自动转换）
    /// </summary>
    public static void On(string type, System.Action<ContinuousTaskActiveInfo> callback)
    {
        _eventListeners.Add((type, callback),
            args => callback(new ContinuousTaskActiveInfo(args[0])),
            js => NodeApi.CallMethodVoid(Module, _on, type, js));
    }

    /// <summary>
    /// off(type, callback)：解除订阅（按 handler 匹配）
    /// </summary>
    public static void Off(string type, System.Action<ContinuousTaskActiveInfo> callback)
    {
        _eventListeners.Remove((type, callback), js => NodeApi.CallMethodVoid(Module, _off, type, js));
    }

    /// <summary>
    /// 监听 continuousTaskCancel 事件（对应 on/off）
    /// </summary>
    public static event System.Action<ContinuousTaskCancelInfo> ContinuousTaskCancel
    {
        add
        {
            _eventListeners.Add(("continuousTaskCancel", value),
                args => value(new ContinuousTaskCancelInfo(args[0])),
                js => NodeApi.CallMethodVoid(Module, _on, "continuousTaskCancel", js));
        }
        remove
        {
            _eventListeners.Remove(("continuousTaskCancel", value), js => NodeApi.CallMethodVoid(Module, _off, "continuousTaskCancel", js));
        }
    }

    /// <summary>
    /// 监听 continuousTaskSuspend 事件（对应 on/off）
    /// </summary>
    public static event System.Action<ContinuousTaskSuspendInfo> ContinuousTaskSuspend
    {
        add
        {
            _eventListeners.Add(("continuousTaskSuspend", value),
                args => value(new ContinuousTaskSuspendInfo(args[0])),
                js => NodeApi.CallMethodVoid(Module, _on, "continuousTaskSuspend", js));
        }
        remove
        {
            _eventListeners.Remove(("continuousTaskSuspend", value), js => NodeApi.CallMethodVoid(Module, _off, "continuousTaskSuspend", js));
        }
    }

    /// <summary>
    /// 监听 continuousTaskActive 事件（对应 on/off）
    /// </summary>
    public static event System.Action<ContinuousTaskActiveInfo> ContinuousTaskActive
    {
        add
        {
            _eventListeners.Add(("continuousTaskActive", value),
                args => value(new ContinuousTaskActiveInfo(args[0])),
                js => NodeApi.CallMethodVoid(Module, _on, "continuousTaskActive", js));
        }
        remove
        {
            _eventListeners.Remove(("continuousTaskActive", value), js => NodeApi.CallMethodVoid(Module, _off, "continuousTaskActive", js));
        }
    }

}

/// <summary>
/// DelaySuspendInfo 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class ResourcescheduleBackgroundTaskManagerDelaySuspendInfo : JsObject
{
    public ResourcescheduleBackgroundTaskManagerDelaySuspendInfo(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _requestId => "requestId"u8;
    private static ReadOnlySpan<byte> _actualDelayTime => "actualDelayTime"u8;
    /// <summary>
    /// requestId
    /// </summary>
    public double RequestId => NativeValue.ToDouble(GetPropertyRaw(_requestId));

    /// <summary>
    /// actualDelayTime
    /// </summary>
    public double ActualDelayTime => NativeValue.ToDouble(GetPropertyRaw(_actualDelayTime));

}

/// <summary>
/// ContinuousTaskRequest 实例包装（@ohos 命名空间内嵌套类）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class ContinuousTaskRequest : JsObject
{
    public ContinuousTaskRequest(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _combinedTaskNotification => "combinedTaskNotification"u8;
    private static ReadOnlySpan<byte> _continuousTaskId => "continuousTaskId"u8;
    private static ReadOnlySpan<byte> _isModeSupported => "isModeSupported"u8;
    private static ReadOnlySpan<byte> _requestAuthFromUser => "requestAuthFromUser"u8;
    private static ReadOnlySpan<byte> _requestAuthFromUserByDialog => "requestAuthFromUserByDialog"u8;
    private static ReadOnlySpan<byte> _checkSpecialScenarioAuth => "checkSpecialScenarioAuth"u8;
    private static ReadOnlySpan<byte> _checkSpecialScenarioAuthResult => "checkSpecialScenarioAuthResult"u8;
    /// <summary>
    /// combinedTaskNotification
    /// </summary>
    public bool? CombinedTaskNotification => (bool?)NativeValue.ToBool(GetPropertyRaw(_combinedTaskNotification));

    /// <summary>
    /// continuousTaskId
    /// </summary>
    public double? ContinuousTaskId => (double?)NativeValue.ToDouble(GetPropertyRaw(_continuousTaskId));

    /// <summary>
    /// isModeSupported
    /// </summary>
    public bool IsModeSupported()
    {
        return CallMethod<bool>(_isModeSupported);
    }

    /// <summary>
    /// requestAuthFromUser
    /// </summary>
    public void RequestAuthFromUser(IntPtr context, IntPtr callback)
    {
        CallMethodVoid(_requestAuthFromUser, context, callback);
    }

    /// <summary>
    /// requestAuthFromUserByDialog
    /// </summary>
    public void RequestAuthFromUserByDialog(IntPtr context, IntPtr callback)
    {
        CallMethodVoid(_requestAuthFromUserByDialog, context, callback);
    }

    /// <summary>
    /// checkSpecialScenarioAuth
    /// </summary>
    public Task<global::HarmonyOS.ArkUI.UserAuthResult> CheckSpecialScenarioAuthAsync(IntPtr context)
    {
        return CallMethodAsync<global::HarmonyOS.ArkUI.UserAuthResult>(_checkSpecialScenarioAuth, context);
    }

    /// <summary>
    /// checkSpecialScenarioAuthResult
    /// </summary>
    public Task<global::HarmonyOS.ArkUI.UserAuthResult> CheckSpecialScenarioAuthResultAsync(IntPtr context)
    {
        return CallMethodAsync<global::HarmonyOS.ArkUI.UserAuthResult>(_checkSpecialScenarioAuthResult, context);
    }

}

/// <summary>
/// ContinuousTaskInfo 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class ContinuousTaskInfo : JsObject
{
    public ContinuousTaskInfo(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _abilityName => "abilityName"u8;
    private static ReadOnlySpan<byte> _uid => "uid"u8;
    private static ReadOnlySpan<byte> _pid => "pid"u8;
    private static ReadOnlySpan<byte> _isFromWebView => "isFromWebView"u8;
    private static ReadOnlySpan<byte> _backgroundModes => "backgroundModes"u8;
    private static ReadOnlySpan<byte> _backgroundSubModes => "backgroundSubModes"u8;
    private static ReadOnlySpan<byte> _notificationId => "notificationId"u8;
    private static ReadOnlySpan<byte> _continuousTaskId => "continuousTaskId"u8;
    private static ReadOnlySpan<byte> _abilityId => "abilityId"u8;
    private static ReadOnlySpan<byte> _wantAgentBundleName => "wantAgentBundleName"u8;
    private static ReadOnlySpan<byte> _wantAgentAbilityName => "wantAgentAbilityName"u8;
    private static ReadOnlySpan<byte> _suspendState => "suspendState"u8;
    private static ReadOnlySpan<byte> _bundleName => "bundleName"u8;
    private static ReadOnlySpan<byte> _appIndex => "appIndex"u8;
    /// <summary>
    /// abilityName
    /// </summary>
    public string AbilityName => NativeValue.ToString(GetPropertyRaw(_abilityName)) ?? string.Empty;

    /// <summary>
    /// uid
    /// </summary>
    public double Uid => NativeValue.ToDouble(GetPropertyRaw(_uid));

    /// <summary>
    /// pid
    /// </summary>
    public double Pid => NativeValue.ToDouble(GetPropertyRaw(_pid));

    /// <summary>
    /// isFromWebView
    /// </summary>
    public bool IsFromWebView => NativeValue.ToBool(GetPropertyRaw(_isFromWebView));

    /// <summary>
    /// backgroundModes
    /// </summary>
    public string[] BackgroundModes => ValueConverter.ConvertArray(GetPropertyRaw(_backgroundModes), static e => ValueConverter.Convert<string>(e));

    /// <summary>
    /// backgroundSubModes
    /// </summary>
    public string[] BackgroundSubModes => ValueConverter.ConvertArray(GetPropertyRaw(_backgroundSubModes), static e => ValueConverter.Convert<string>(e));

    /// <summary>
    /// notificationId
    /// </summary>
    public double NotificationId => NativeValue.ToDouble(GetPropertyRaw(_notificationId));

    /// <summary>
    /// continuousTaskId
    /// </summary>
    public double ContinuousTaskId => NativeValue.ToDouble(GetPropertyRaw(_continuousTaskId));

    /// <summary>
    /// abilityId
    /// </summary>
    public double AbilityId => NativeValue.ToDouble(GetPropertyRaw(_abilityId));

    /// <summary>
    /// wantAgentBundleName
    /// </summary>
    public string WantAgentBundleName => NativeValue.ToString(GetPropertyRaw(_wantAgentBundleName)) ?? string.Empty;

    /// <summary>
    /// wantAgentAbilityName
    /// </summary>
    public string WantAgentAbilityName => NativeValue.ToString(GetPropertyRaw(_wantAgentAbilityName)) ?? string.Empty;

    /// <summary>
    /// suspendState
    /// </summary>
    public bool SuspendState => NativeValue.ToBool(GetPropertyRaw(_suspendState));

    /// <summary>
    /// bundleName
    /// </summary>
    public string? BundleName => (string?)NativeValue.ToString(GetPropertyRaw(_bundleName)) ?? string.Empty;

    /// <summary>
    /// appIndex
    /// </summary>
    public double? AppIndex => (double?)NativeValue.ToDouble(GetPropertyRaw(_appIndex));

}

/// <summary>
/// ContinuousTaskCancelInfo 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class ContinuousTaskCancelInfo : JsObject
{
    public ContinuousTaskCancelInfo(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _reason => "reason"u8;
    private static ReadOnlySpan<byte> _id => "id"u8;
    private static ReadOnlySpan<byte> _detailedReason => "detailedReason"u8;
    /// <summary>
    /// reason
    /// </summary>
    public global::HarmonyOS.ArkUI.ContinuousTaskCancelReason Reason => (global::HarmonyOS.ArkUI.ContinuousTaskCancelReason)NativeValue.ToInt(GetPropertyRaw(_reason));

    /// <summary>
    /// id
    /// </summary>
    public double Id => NativeValue.ToDouble(GetPropertyRaw(_id));

    /// <summary>
    /// detailedReason
    /// </summary>
    public global::HarmonyOS.ArkUI.ContinuousTaskDetailedCancelReason? DetailedReason => (global::HarmonyOS.ArkUI.ContinuousTaskDetailedCancelReason?)(global::HarmonyOS.ArkUI.ContinuousTaskDetailedCancelReason)NativeValue.ToInt(GetPropertyRaw(_detailedReason));

}

/// <summary>
/// ContinuousTaskSuspendInfo 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class ContinuousTaskSuspendInfo : JsObject
{
    public ContinuousTaskSuspendInfo(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _continuousTaskId => "continuousTaskId"u8;
    private static ReadOnlySpan<byte> _suspendState => "suspendState"u8;
    private static ReadOnlySpan<byte> _suspendReason => "suspendReason"u8;
    private static ReadOnlySpan<byte> _suspendMessage => "suspendMessage"u8;
    /// <summary>
    /// continuousTaskId
    /// </summary>
    public double ContinuousTaskId => NativeValue.ToDouble(GetPropertyRaw(_continuousTaskId));

    /// <summary>
    /// suspendState
    /// </summary>
    public bool SuspendState => NativeValue.ToBool(GetPropertyRaw(_suspendState));

    /// <summary>
    /// suspendReason
    /// </summary>
    public global::HarmonyOS.ArkUI.ContinuousTaskSuspendReason SuspendReason => (global::HarmonyOS.ArkUI.ContinuousTaskSuspendReason)NativeValue.ToInt(GetPropertyRaw(_suspendReason));

    /// <summary>
    /// suspendMessage
    /// </summary>
    public SuspendMessage? SuspendMessage => GetPropertyRaw(_suspendMessage) == IntPtr.Zero ? null : new SuspendMessage(GetPropertyRaw(_suspendMessage));

}

/// <summary>
/// ContinuousTaskActiveInfo 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class ContinuousTaskActiveInfo : JsObject
{
    public ContinuousTaskActiveInfo(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _id => "id"u8;
    /// <summary>
    /// id
    /// </summary>
    public double Id => NativeValue.ToDouble(GetPropertyRaw(_id));

}

/// <summary>
/// SuspendMessage 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class SuspendMessage : JsObject
{
    public SuspendMessage(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _message => "message"u8;
    private static ReadOnlySpan<byte> _reason => "reason"u8;
    /// <summary>
    /// message
    /// </summary>
    public string Message => NativeValue.ToString(GetPropertyRaw(_message)) ?? string.Empty;

    /// <summary>
    /// reason
    /// </summary>
    public global::HarmonyOS.ArkUI.ContinuousTaskSuspendReason Reason => (global::HarmonyOS.ArkUI.ContinuousTaskSuspendReason)NativeValue.ToInt(GetPropertyRaw(_reason));

}
