// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// SelectionContainer 绑定（@ohos.arkui.components.SelectionContainer）。
/// </summary>
public static unsafe partial class SelectionContainer
{
    private const string ModuleName = "@ohos.arkui.components.SelectionContainer";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[arkui.components.SelectionContainer] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _closeSelectionMenu => "closeSelectionMenu"u8;
    private static ReadOnlySpan<byte> _clearTextSelection => "clearTextSelection"u8;
    private static ReadOnlySpan<byte> _copyOption => "copyOption"u8;
    private static ReadOnlySpan<byte> _caretColor => "caretColor"u8;
    private static ReadOnlySpan<byte> _selectedBackgroundColor => "selectedBackgroundColor"u8;
    private static ReadOnlySpan<byte> _enableHapticFeedback => "enableHapticFeedback"u8;
    private static ReadOnlySpan<byte> _textJoinStyle => "textJoinStyle"u8;
    private static ReadOnlySpan<byte> _bindSelectionMenu => "bindSelectionMenu"u8;
    private static ReadOnlySpan<byte> _editMenuOptions => "editMenuOptions"u8;
    private static ReadOnlySpan<byte> _onTextSelectionChange => "onTextSelectionChange"u8;
    private static ReadOnlySpan<byte> _onWillCopy => "onWillCopy"u8;
    private static ReadOnlySpan<byte> _onCopy => "onCopy"u8;

    /// <summary>
    /// closeSelectionMenu
    /// </summary>
    public static void CloseSelectionMenu()
    {
        NodeApi.CallMethodVoid(Module, _closeSelectionMenu);
    }

    /// <summary>
    /// clearTextSelection
    /// </summary>
    public static void ClearTextSelection()
    {
        NodeApi.CallMethodVoid(Module, _clearTextSelection);
    }

    /// <summary>
    /// copyOption
    /// </summary>
    public static IntPtr CopyOption(IntPtr value)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _copyOption, value);
    }

    /// <summary>
    /// caretColor
    /// </summary>
    public static IntPtr CaretColor(IntPtr color)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _caretColor, color);
    }

    /// <summary>
    /// selectedBackgroundColor
    /// </summary>
    public static IntPtr SelectedBackgroundColor(IntPtr color)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _selectedBackgroundColor, color);
    }

    /// <summary>
    /// enableHapticFeedback
    /// </summary>
    public static IntPtr EnableHapticFeedback(bool isEnabled)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _enableHapticFeedback, isEnabled);
    }

    /// <summary>
    /// textJoinStyle
    /// </summary>
    public static IntPtr TextJoinStyle(IntPtr style)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _textJoinStyle, style);
    }

    /// <summary>
    /// bindSelectionMenu
    /// </summary>
    public static IntPtr BindSelectionMenu(IntPtr spanType, IntPtr content, IntPtr responseType, IntPtr? options = null)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _bindSelectionMenu, spanType, content, responseType, options);
    }

    /// <summary>
    /// editMenuOptions
    /// </summary>
    public static IntPtr EditMenuOptions(IntPtr editMenu)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _editMenuOptions, editMenu);
    }

    /// <summary>
    /// onTextSelectionChange
    /// </summary>
    public static IntPtr OnTextSelectionChange(IntPtr callback)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onTextSelectionChange, callback);
    }

    /// <summary>
    /// onWillCopy
    /// </summary>
    public static IntPtr OnWillCopy(IntPtr callback)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onWillCopy, callback);
    }

    /// <summary>
    /// onCopy
    /// </summary>
    public static IntPtr OnCopy(IntPtr callback)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _onCopy, callback);
    }

}
