using System;

namespace HarmonyOS.ArkUI;

/// <summary>
/// SensorId 枚举
/// </summary>
public enum SensorId
{
    ACCELEROMETER = 1,
    GYROSCOPE = 2,
    AMBIENT_LIGHT = 5,
    MAGNETIC_FIELD = 6,
    BAROMETER = 8,
    HALL = 10,
    PROXIMITY = 12,
    HUMIDITY = 13,
    ORIENTATION = 256,
    GRAVITY = 257,
    LINEAR_ACCELEROMETER = 258,
    ROTATION_VECTOR = 259,
    AMBIENT_TEMPERATURE = 260,
    MAGNETIC_FIELD_UNCALIBRATED = 261,
    GYROSCOPE_UNCALIBRATED = 263,
    SIGNIFICANT_MOTION = 264,
    PEDOMETER_DETECTION = 265,
    PEDOMETER = 266,
    HEART_RATE = 278,
    WEAR_DETECTION = 280,
    ACCELEROMETER_UNCALIBRATED = 281,
    FUSION_PRESSURE = 283
}

/// <summary>
/// SensorType 枚举
/// </summary>
public enum SensorType
{
    SENSOR_TYPE_ID_ACCELEROMETER = 1,
    SENSOR_TYPE_ID_GYROSCOPE = 2,
    SENSOR_TYPE_ID_AMBIENT_LIGHT = 5,
    SENSOR_TYPE_ID_MAGNETIC_FIELD = 6,
    SENSOR_TYPE_ID_BAROMETER = 8,
    SENSOR_TYPE_ID_HALL = 10,
    SENSOR_TYPE_ID_PROXIMITY = 12,
    SENSOR_TYPE_ID_HUMIDITY = 13,
    SENSOR_TYPE_ID_ORIENTATION = 256,
    SENSOR_TYPE_ID_GRAVITY = 257,
    SENSOR_TYPE_ID_LINEAR_ACCELERATION = 258,
    SENSOR_TYPE_ID_ROTATION_VECTOR = 259,
    SENSOR_TYPE_ID_AMBIENT_TEMPERATURE = 260,
    SENSOR_TYPE_ID_MAGNETIC_FIELD_UNCALIBRATED = 261,
    SENSOR_TYPE_ID_GYROSCOPE_UNCALIBRATED = 263,
    SENSOR_TYPE_ID_SIGNIFICANT_MOTION = 264,
    SENSOR_TYPE_ID_PEDOMETER_DETECTION = 265,
    SENSOR_TYPE_ID_PEDOMETER = 266,
    SENSOR_TYPE_ID_HEART_RATE = 278,
    SENSOR_TYPE_ID_WEAR_DETECTION = 280,
    SENSOR_TYPE_ID_ACCELEROMETER_UNCALIBRATED = 281
}

/// <summary>
/// SensorAccuracy 枚举
/// </summary>
public enum SensorAccuracy
{
    ACCURACY_UNRELIABLE = 0,
    ACCURACY_LOW = 1,
    ACCURACY_MEDIUM = 2,
    ACCURACY_HIGH = 3
}