// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// TreeMap 绑定（@ohos.util.TreeMap）。
/// </summary>
public static unsafe partial class TreeMap
{
    private const string ModuleName = "@ohos.util.TreeMap";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[util.TreeMap] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _isEmpty => "isEmpty"u8;
    private static ReadOnlySpan<byte> _hasKey => "hasKey"u8;
    private static ReadOnlySpan<byte> _hasValue => "hasValue"u8;
    private static ReadOnlySpan<byte> _get => "get"u8;
    private static ReadOnlySpan<byte> _getFirstKey => "getFirstKey"u8;
    private static ReadOnlySpan<byte> _getLastKey => "getLastKey"u8;
    private static ReadOnlySpan<byte> _setAll => "setAll"u8;
    private static ReadOnlySpan<byte> _set => "set"u8;
    private static ReadOnlySpan<byte> _remove => "remove"u8;
    private static ReadOnlySpan<byte> _clear => "clear"u8;
    private static ReadOnlySpan<byte> _getLowerKey => "getLowerKey"u8;
    private static ReadOnlySpan<byte> _getHigherKey => "getHigherKey"u8;
    private static ReadOnlySpan<byte> _keys => "keys"u8;
    private static ReadOnlySpan<byte> _values => "values"u8;
    private static ReadOnlySpan<byte> _replace => "replace"u8;
    private static ReadOnlySpan<byte> _forEach => "forEach"u8;
    private static ReadOnlySpan<byte> _entries => "entries"u8;

    /// <summary>
    /// isEmpty
    /// </summary>
    public static bool IsEmpty()
    {
        return NodeApi.CallMethod<bool>(Module, _isEmpty);
    }

    /// <summary>
    /// hasKey
    /// </summary>
    public static bool HasKey(IntPtr key)
    {
        return NodeApi.CallMethod<bool>(Module, _hasKey, key);
    }

    /// <summary>
    /// hasValue
    /// </summary>
    public static bool HasValue(IntPtr value)
    {
        return NodeApi.CallMethod<bool>(Module, _hasValue, value);
    }

    /// <summary>
    /// get
    /// </summary>
    public static IntPtr Get(IntPtr key)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _get, key);
    }

    /// <summary>
    /// getFirstKey
    /// </summary>
    public static IntPtr GetFirstKey()
    {
        return NodeApi.CallMethod<IntPtr>(Module, _getFirstKey);
    }

    /// <summary>
    /// getLastKey
    /// </summary>
    public static IntPtr GetLastKey()
    {
        return NodeApi.CallMethod<IntPtr>(Module, _getLastKey);
    }

    /// <summary>
    /// setAll
    /// </summary>
    public static void SetAll(IntPtr map)
    {
        NodeApi.CallMethodVoid(Module, _setAll, map);
    }

    /// <summary>
    /// set
    /// </summary>
    public static IntPtr Set(IntPtr key, IntPtr value)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _set, key, value);
    }

    /// <summary>
    /// remove
    /// </summary>
    public static IntPtr Remove(IntPtr key)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _remove, key);
    }

    /// <summary>
    /// clear
    /// </summary>
    public static void Clear()
    {
        NodeApi.CallMethodVoid(Module, _clear);
    }

    /// <summary>
    /// getLowerKey
    /// </summary>
    public static IntPtr GetLowerKey(IntPtr key)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _getLowerKey, key);
    }

    /// <summary>
    /// getHigherKey
    /// </summary>
    public static IntPtr GetHigherKey(IntPtr key)
    {
        return NodeApi.CallMethod<IntPtr>(Module, _getHigherKey, key);
    }

    /// <summary>
    /// keys
    /// </summary>
    public static IntPtr Keys()
    {
        return NodeApi.CallMethod<IntPtr>(Module, _keys);
    }

    /// <summary>
    /// values
    /// </summary>
    public static IntPtr Values()
    {
        return NodeApi.CallMethod<IntPtr>(Module, _values);
    }

    /// <summary>
    /// replace
    /// </summary>
    public static bool Replace(IntPtr key, IntPtr newValue)
    {
        return NodeApi.CallMethod<bool>(Module, _replace, key, newValue);
    }

    /// <summary>
    /// forEach
    /// </summary>
    public static void ForEach(IntPtr callbackFn, IntPtr? thisArg = null)
    {
        NodeApi.CallMethodVoid(Module, _forEach, callbackFn, thisArg);
    }

    /// <summary>
    /// entries
    /// </summary>
    public static IntPtr Entries()
    {
        return NodeApi.CallMethod<IntPtr>(Module, _entries);
    }

}
