// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// UiMaterial 绑定（@ohos.arkui.uiMaterial）。
/// </summary>
public static unsafe partial class UiMaterial
{
    private const string ModuleName = "@ohos.arkui.uiMaterial";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[arkui.uiMaterial] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _getMaterialInfo => "getMaterialInfo"u8;
    private static ReadOnlySpan<byte> _getGlobalMaterialLevel => "getGlobalMaterialLevel"u8;
    private static ReadOnlySpan<byte> _isImmersiveMaterialSupported => "isImmersiveMaterialSupported"u8;

    /// <summary>
    /// getMaterialInfo
    /// </summary>
    public static MaterialInfo GetMaterialInfo()
    {
        return NodeApi.CallMethod(Module, _getMaterialInfo, static h => new MaterialInfo(h));
    }

    /// <summary>
    /// getGlobalMaterialLevel
    /// </summary>
    public static global::HarmonyOS.ArkUI.MaterialLevel GetGlobalMaterialLevel()
    {
        return NodeApi.CallMethod<global::HarmonyOS.ArkUI.MaterialLevel>(Module, _getGlobalMaterialLevel);
    }

    /// <summary>
    /// isImmersiveMaterialSupported
    /// </summary>
    public static bool IsImmersiveMaterialSupported()
    {
        return NodeApi.CallMethod<bool>(Module, _isImmersiveMaterialSupported);
    }

}

/// <summary>
/// MaterialInfo 实例包装（@ohos 命名空间内嵌套接口）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class MaterialInfo : JsObject
{
    public MaterialInfo(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _state => "state"u8;
    private static ReadOnlySpan<byte> _type => "type"u8;
    /// <summary>
    /// state
    /// </summary>
    public global::HarmonyOS.ArkUI.MaterialState State => (global::HarmonyOS.ArkUI.MaterialState)NativeValue.ToInt(GetPropertyRaw(_state));

    /// <summary>
    /// type
    /// </summary>
    public global::HarmonyOS.ArkUI.MaterialType Type => (global::HarmonyOS.ArkUI.MaterialType)NativeValue.ToInt(GetPropertyRaw(_type));

}

/// <summary>
/// ImmersiveMaterial 实例包装（@ohos 命名空间内嵌套类）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class ImmersiveMaterial : JsObject
{
    public ImmersiveMaterial(IntPtr handle) : base(handle) { }

    private static ReadOnlySpan<byte> _ImmersiveMaterial => "ImmersiveMaterial"u8;
}
