using System;

using System.ComponentModel;

namespace HarmonyOS.ArkUI;

/// <summary>
/// UniformDataType 枚举
/// </summary>
public enum UniformDataType
{
    [Description("general.entity")]
    Entity,
    [Description("general.object")]
    Object,
    [Description("general.composite-object")]
    CompositeObject,
    [Description("general.text")]
    Text,
    [Description("general.plain-text")]
    PlainText,
    [Description("general.html")]
    Html,
    [Description("general.hyperlink")]
    Hyperlink,
    [Description("general.xml")]
    Xml,
    [Description("general.xhtml")]
    Xhtml,
    [Description("general.rss")]
    Rss,
    [Description("com.real.smil")]
    Smil,
    [Description("general.source-code")]
    SourceCode,
    [Description("general.script")]
    Script,
    [Description("general.shell-script")]
    ShellScript,
    [Description("general.csh-script")]
    CshScript,
    [Description("general.perl-script")]
    PerlScript,
    [Description("general.php-script")]
    PhpScript,
    [Description("general.python-script")]
    PythonScript,
    [Description("general.ruby-script")]
    RubyScript,
    [Description("general.type-script")]
    TypeScript,
    [Description("general.java-script")]
    JavaScript,
    [Description("general.css")]
    Css,
    [Description("general.c-header")]
    CHeader,
    [Description("general.c-source")]
    CSource,
    [Description("general.c-plus-plus-header")]
    CPlusPlusHeader,
    [Description("general.c-plus-plus-source")]
    CPlusPlusSource,
    [Description("general.java-source")]
    JavaSource,
    [Description("general.tex")]
    Tex,
    [Description("general.markdown")]
    Markdown,
    [Description("general.asc-text")]
    AscText,
    [Description("general.rich-text")]
    RichText,
    [Description("general.delimited-values-text")]
    DelimitedValuesText,
    [Description("general.comma-separated-values-text")]
    CommaSeparatedValuesText,
    [Description("general.tab-separated-values-text")]
    TabSeparatedValuesText,
    [Description("general.ebook")]
    Ebook,
    [Description("general.epub")]
    Epub,
    [Description("com.amazon.azw")]
    Azw,
    [Description("com.amazon.azw3")]
    Azw3,
    [Description("com.amazon.kfx")]
    Kfx,
    [Description("com.amazon.mobi")]
    Mobi,
    [Description("general.media")]
    Media,
    [Description("general.image")]
    Image,
    [Description("general.jpeg")]
    Jpeg,
    [Description("general.png")]
    Png,
    [Description("general.raw-image")]
    RawImage,
    [Description("general.tiff")]
    Tiff,
    [Description("com.microsoft.bmp")]
    Bmp,
    [Description("com.microsoft.ico")]
    Ico,
    [Description("com.adobe.photoshop-image")]
    PhotoshopImage,
    [Description("com.adobe.illustrator.ai-image")]
    AIImage,
    [Description("general.fax")]
    Fax,
    [Description("com.j2.jfx-fax")]
    JfxFax,
    [Description("com.js.efx-fax")]
    EfxFax,
    [Description("general.xbitmap-image")]
    XbitmapImage,
    [Description("general.gif")]
    Gif,
    [Description("com.truevision.tga-image")]
    TgaImage,
    [Description("com.sgi.sgi-image")]
    SgiImage,
    [Description("com.ilm.openexr-image")]
    OpenexrImage,
    [Description("com.kodak.flashpix.image")]
    FlashpixImage,
    [Description("com.microsoft.word.doc")]
    WordDoc,
    [Description("com.microsoft.excel.xls")]
    Excel,
    [Description("com.microsoft.powerpoint.ppt")]
    Ppt,
    [Description("com.microsoft.word.dot")]
    WordDot,
    [Description("com.microsoft.powerpoint.pps")]
    PowerpointPps,
    [Description("com.microsoft.powerpoint.pot")]
    PowerpointPot,
    [Description("com.microsoft.excel.xlt")]
    ExcelXlt,
    [Description("com.microsoft.visio.vsd")]
    VisioVsd,
    [Description("com.adobe.pdf")]
    Pdf,
    [Description("com.adobe.postscript")]
    Postscript,
    [Description("com.adobe.encapsulated-postscript")]
    EncapsulatedPostscript,
    [Description("general.video")]
    Video,
    [Description("general.avi")]
    Avi,
    [Description("general.mpeg")]
    Mpeg,
    [Description("general.mpeg-4")]
    Mpeg4,
    [Description("general.3gpp")]
    Video3Gpp,
    [Description("general.3gpp2")]
    Video3Gpp2,
    [Description("general.ts")]
    Ts,
    [Description("general.mpegurl-video")]
    MpegurlVideo,
    [Description("com.microsoft.windows-media-wm")]
    WindowsMediaWm,
    [Description("com.microsoft.windows-media-wmv")]
    WindowsMediaWmv,
    [Description("com.microsoft.windows-media-wmp")]
    WindowsMediaWmp,
    [Description("com.microsoft.windows-media-wvx")]
    WindowsMediaWvx,
    [Description("com.microsoft.windows-media-wmx")]
    WindowsMediaWmx,
    [Description("com.real.realmedia")]
    Realmedia,
    [Description("org.matroska.mkv")]
    MatroskaVideo,
    [Description("com.adobe.flash")]
    Flash,
    [Description("general.audio")]
    Audio,
    [Description("general.aac")]
    Aac,
    [Description("general.aiff")]
    Aiff,
    [Description("general.alac")]
    Alac,
    [Description("general.flac")]
    Flac,
    [Description("general.mp3")]
    Mp3,
    [Description("general.ogg")]
    Ogg,
    [Description("general.pcm")]
    Pcm,
    [Description("com.microsoft.windows-media-wma")]
    WindowsMediaWma,
    [Description("com.microsoft.waveform-audio")]
    WaveformAudio,
    [Description("com.microsoft.windows-media-wax")]
    WindowsMediaWax,
    [Description("general.au-audio")]
    AuAudio,
    [Description("general.aifc-audio")]
    AifcAudio,
    [Description("general.mpegurl-audio")]
    MpegurlAudio,
    [Description("general.mpeg-4-audio")]
    Mpeg4Audio,
    [Description("general.mp2")]
    Mp2,
    [Description("general.mpeg-audio")]
    MpegAudio,
    [Description("general.ulaw-audio")]
    UlawAudio,
    [Description("com.digidesign.sd2-audio")]
    Sd2Audio,
    [Description("com.real.realaudio")]
    Realaudio,
    [Description("org.matroska.mka")]
    MatroskaAudio,
    [Description("general.file")]
    File,
    [Description("general.directory")]
    Directory,
    [Description("general.folder")]
    Folder,
    [Description("general.symlink")]
    Symlink,
    [Description("general.archive")]
    Archive,
    [Description("general.bz2-archive")]
    Bz2Archive,
    [Description("general.opg")]
    Opg,
    [Description("general.taz-archive")]
    TazArchive,
    [Description("general.web-archive")]
    WebArchive,
    [Description("general.disk-image")]
    DiskImage,
    [Description("general.iso")]
    Iso,
    [Description("general.tar-archive")]
    TarArchive,
    [Description("general.zip-archive")]
    ZipArchive,
    [Description("com.sun.java-archive")]
    JavaArchive,
    [Description("org.gnu.gnu-tar-archive")]
    GnuTarArchive,
    [Description("org.gnu.gnu-zip-archive")]
    GnuZipArchive,
    [Description("org.gnu.gnu-zip-tar-archive")]
    GnuZipTarArchive,
    [Description("org.openxmlformats.openxml")]
    Openxml,
    [Description("org.openxmlformats.wordprocessingml.document")]
    WordprocessingmlDocument,
    [Description("org.openxmlformats.spreadsheetml.sheet")]
    SpreadsheetmlSheet,
    [Description("org.openxmlformats.presentationml.presentation")]
    PresentationmlPresentation,
    [Description("org.openxmlformats.drawingml.visio")]
    DrawingmlVisio,
    [Description("org.openxmlformats.drawingml.template")]
    DrawingmlTemplate,
    [Description("org.openxmlformats.wordprocessingml.template")]
    WordprocessingmlTemplate,
    [Description("org.openxmlformats.presentationml.template")]
    PresentationmlTemplate,
    [Description("org.openxmlformats.presentationml.slideshow")]
    PresentationmlSlideshow,
    [Description("org.openxmlformats.spreadsheetml.template")]
    SpreadsheetmlTemplate,
    [Description("org.oasis.opendocument")]
    Opendocument,
    [Description("org.oasis.opendocument.text")]
    OpendocumentText,
    [Description("org.oasis.opendocument.spreadsheet")]
    OpendocumentSpreadsheet,
    [Description("org.oasis.opendocument.presentation")]
    OpendocumentPresentation,
    [Description("org.oasis.opendocument.graphics")]
    OpendocumentGraphics,
    [Description("org.oasis.opendocument.formula")]
    OpendocumentFormula,
    [Description("com.allume.stuffit-archive")]
    StuffitArchive,
    [Description("com.rarlab.rar-archive")]
    RarArchive,
    [Description("org.7-zip.7-zip-archive")]
    SevenZipArchive,
    [Description("general.calendar")]
    Calendar,
    [Description("general.vcs")]
    Vcs,
    [Description("general.ics")]
    Ics,
    [Description("general.contact")]
    Contact,
    [Description("general.database")]
    Database,
    [Description("general.message")]
    Message,
    [Description("general.executable")]
    Executable,
    [Description("com.microsoft.portable-executable")]
    PortableExecutable,
    [Description("com.sun.java-class")]
    SunJavaClass,
    [Description("general.vcard")]
    Vcard,
    [Description("general.navigation")]
    Navigation,
    [Description("general.location")]
    Location,
    [Description("general.font")]
    Font,
    [Description("general.truetype-font")]
    TruetypeFont,
    [Description("general.truetype-collection-font")]
    TruetypeCollectionFont,
    [Description("general.opentype-font")]
    OpentypeFont,
    [Description("com.adobe.postscript-font")]
    PostscriptFont,
    [Description("com.adobe.postscript-pfb-font")]
    PostscriptPfbFont,
    [Description("com.adobe.postscript-pfa-font")]
    PostscriptPfaFont,
    [Description("openharmony.form")]
    OpenharmonyForm,
    [Description("openharmony.app-item")]
    OpenharmonyAppItem,
    [Description("openharmony.pixel-map")]
    OpenharmonyPixelMap,
    [Description("openharmony.atomic-service")]
    OpenharmonyAtomicService,
    [Description("openharmony.package")]
    OpenharmonyPackage,
    [Description("openharmony.hap")]
    OpenharmonyHap,
    [Description("openharmony.hdoc")]
    OpenharmonyHdoc,
    [Description("openharmony.hinote")]
    OpenharmonyHinote,
    [Description("openharmony.styled-string")]
    OpenharmonyStyledString,
    [Description("openharmony.want")]
    OpenharmonyWant,
    [Description("general.ofd")]
    Ofd,
    [Description("general.cad")]
    Cad,
    [Description("general.octet-stream")]
    OctetStream,
    [Description("general.file-uri")]
    FileUri,
    [Description("general.content-form")]
    ContentForm
}