// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api;

/// <summary>
/// Want 绑定（@ohos.app.ability.Want）。
/// </summary>
public static unsafe partial class Want
{
    private const string ModuleName = "@ohos.app.ability.Want";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[app.ability.Want] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

}

/// <summary>
/// Want 实例包装（@ohos 命名空间内嵌套类）。
/// 由 JsObject 持有 napi 强引用；Dispose 仅释放引用，JS 对象由 ArkTS GC 管理。
/// </summary>
public sealed partial class WantObject : JsObject
{
    public WantObject(IntPtr handle) : base(handle) { }
    private static ReadOnlySpan<byte> _bundleName => "bundleName"u8;
    private static ReadOnlySpan<byte> _abilityName => "abilityName"u8;
    private static ReadOnlySpan<byte> _deviceId => "deviceId"u8;
    private static ReadOnlySpan<byte> _uri => "uri"u8;
    private static ReadOnlySpan<byte> _type => "type"u8;
    private static ReadOnlySpan<byte> _flags => "flags"u8;
    private static ReadOnlySpan<byte> _action => "action"u8;
    private static ReadOnlySpan<byte> _parameters => "parameters"u8;
    private static ReadOnlySpan<byte> _entities => "entities"u8;
    private static ReadOnlySpan<byte> _moduleName => "moduleName"u8;
    private static ReadOnlySpan<byte> _fds => "fds"u8;
    /// <summary>
    /// bundleName
    /// </summary>
    public string? BundleName => (string?)NativeValue.ToString(GetPropertyRaw(_bundleName)) ?? string.Empty;

    /// <summary>
    /// abilityName
    /// </summary>
    public string? AbilityName => (string?)NativeValue.ToString(GetPropertyRaw(_abilityName)) ?? string.Empty;

    /// <summary>
    /// deviceId
    /// </summary>
    public string? DeviceId => (string?)NativeValue.ToString(GetPropertyRaw(_deviceId)) ?? string.Empty;

    /// <summary>
    /// uri
    /// </summary>
    public string? Uri => (string?)NativeValue.ToString(GetPropertyRaw(_uri)) ?? string.Empty;

    /// <summary>
    /// type
    /// </summary>
    public string? Type => (string?)NativeValue.ToString(GetPropertyRaw(_type)) ?? string.Empty;

    /// <summary>
    /// flags
    /// </summary>
    public double? Flags => (double?)NativeValue.ToDouble(GetPropertyRaw(_flags));

    /// <summary>
    /// action
    /// </summary>
    public string? Action => (string?)NativeValue.ToString(GetPropertyRaw(_action)) ?? string.Empty;

    /// <summary>
    /// parameters
    /// </summary>
    public IntPtr Parameters => GetPropertyRaw(_parameters);

    /// <summary>
    /// entities
    /// </summary>
    public string[] Entities => ValueConverter.ConvertArray(GetPropertyRaw(_entities), static e => ValueConverter.Convert<string>(e));

    /// <summary>
    /// moduleName
    /// </summary>
    public string? ModuleName => (string?)NativeValue.ToString(GetPropertyRaw(_moduleName)) ?? string.Empty;

    /// <summary>
    /// fds
    /// </summary>
    public IntPtr Fds => GetPropertyRaw(_fds);

}
