// <auto-generated>
// 由 enumGenerator.ts（@ohos.* namespace 绑定路线） 生成。
// 生成器版本：1.0.0；HarmonyOS SDK：26.0.0
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>

namespace HarmonyOS.ArkUI;

/// <summary>
/// KioskFeature 枚举
/// </summary>
public enum KioskFeature
{
    AllowNotificationCenter = 1,
    AllowControlCenter = 2,
    AllowGestureControl = 3,
    AllowSideDock = 4
}

/// <summary>
/// EnterpriseApplicationManagerServiceType 枚举
/// </summary>
public enum EnterpriseApplicationManagerServiceType
{
    CollaborationService = 0
}

/// <summary>
/// WindowState 枚举
/// </summary>
public enum WindowState
{
    Disconnect = 0,
    Connect = 1,
    Foreground = 2,
    Active = 3,
    Inactive = 4,
    Background = 5
}