// <auto-generated>由 ArkTsBinding 适配：组件节点类（形状对齐 native_node.h 属性注释），请勿手工编辑
#nullable enable
using HarmonyOS.Bindings.NativeNode;

namespace HarmonyOS.ArkUI;

/// <summary>Toggle 组件（ARKUI_NODE_TOGGLE，switch 型）。NODE_TOGGLE_ON_CHANGE：data[0].i32=1 开 0 关</summary>
public unsafe class Toggle : ArkUINodeBase
{
    public Toggle() : base(ArkUI_NodeType.ARKUI_NODE_TOGGLE) { }

    /// <summary>开态（NODE_TOGGLE_VALUE，i32：1 开 0 关）</summary>
    public bool IsOn
    {
        set => SetNumericAttribute(ArkUI_NodeAttributeType.NODE_TOGGLE_VALUE, ArkUIValue.I(value ? 1 : 0));
    }

    public void SetSelectedColor(byte r, byte g, byte b, byte a = 255)
        => SetNumericAttribute(ArkUI_NodeAttributeType.NODE_TOGGLE_SELECTED_COLOR,
            ArkUIValue.U((uint)((a << 24) | (r << 16) | (g << 8) | b)));

    /// <summary>onChange 事件（NODE_TOGGLE_ON_CHANGE）</summary>
    public event Action<ArkUINodeEvent>? IsOnChange
    {
        add => On(ArkUI_NodeEventType.NODE_TOGGLE_ON_CHANGE, value!);
        remove => Off(ArkUI_NodeEventType.NODE_TOGGLE_ON_CHANGE);
    }
}
