// <auto-generated>
// 由 enumGenerator.ts（@ohos.* namespace 绑定路线） 生成。
// 生成器版本：1.0.0；HarmonyOS SDK：26.0.0
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>

namespace HarmonyOS.ArkUI;

/// <summary>
/// NfcState 枚举
/// </summary>
public enum NfcState
{
    StateOff = 1,
    StateTurningOn = 2,
    StateOn = 3,
    StateTurningOff = 4
}