// <auto-generated>
// 由 enumGenerator.ts（@ohos.* namespace 绑定路线） 生成。
// 生成器版本：1.0.0；HarmonyOS SDK：26.0.0
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>

namespace HarmonyOS.ArkUI;

/// <summary>
/// EventFlag 枚举
/// </summary>
public enum EventFlag
{
    EventPanGestureLeft = 1,
    EventPanGestureRight = 2,
    EventLongPress = 512,
    EventPanGestureUp = 4,
    EventClick = 256,
    EventNone = 0,
    EventPanGestureDown = 8
}

/// <summary>
/// RectChangeReason 枚举
/// </summary>
public enum RectChangeReason
{
    HostWindowRectChange = 1
}