/**
 * @ohos.* namespace 绑定生成器。
 *
 * 生成模式参照手写的 DeviceInfo.cs：
 * - static unsafe partial class，ModuleName 常量
 * - napi_load_module 懒加载 + NapiReference 持有
 * - const → static property (GetString / GetNumber / GetBool)
 * - function → static method (CallMethod / CallMethodAsync)
 *
 * 产物命名空间：HarmonyOS.Bindings.Api
 */
import { ComponentInfo, MethodInfo, ParameterInfo, EnumInfo } from './models';
import { TypeMapper } from './typeMapper';
import { EnumGenerator } from './enumGenerator';

export interface ApiGenResult {
    csharp: string;
    enums: string | null;
    className: string;
    moduleName: string;
    permissions: string[];
}

export class ApiGenerator {
    private enumGenerator: EnumGenerator;

    constructor() {
        this.enumGenerator = new EnumGenerator();
    }

    /**
     * 从 .d.ts 文件内容提取 @permission 声明
     */
    static extractPermissions(source: string): string[] {
        const perms = new Set<string>();
        const re = /@permission\s+(ohos\.permission\.[\w.]+)/g;
        let m: RegExpExecArray | null;
        while ((m = re.exec(source)) !== null) {
            perms.add(m[1]);
        }
        return [...perms].sort();
    }

    /**
     * @ohos.deviceInfo.d.ts → { module: "@ohos.deviceInfo", className: "DeviceInfo", local: "deviceInfo" }
     */
    static dtsToModuleInfo(dtsFileName: string): { module: string; className: string; local: string } {
        const stem = dtsFileName.replace(/\.d\.ts$/, '');
        // 去掉 @ohos. 或 @system. 前缀
        let local = stem;
        if (local.startsWith('@ohos.')) local = local.substring(6);
        else if (local.startsWith('@system.')) local = 'system.' + local.substring(8);
        else if (local.startsWith('@')) local = local.substring(1);

        // className: 取最后一段，首字母大写
        const parts = local.split('.');
        const className = parts[parts.length - 1].charAt(0).toUpperCase()
            + parts[parts.length - 1].slice(1);

        return { module: stem, className, local };
    }

    generate(
        component: ComponentInfo,
        moduleInfo: { module: string; className: string; local: string },
        permissions: string[],
        enums: EnumInfo[]
    ): ApiGenResult {
        const lines: string[] = [];
        const needsTask = component.methods.some(m => /^Task(<.+>)?$/.test(m.returnType || ''));

        // header
        lines.push('// <auto-generated>');
        lines.push(`// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。`);
        lines.push('// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器');
        lines.push('// </auto-generated>');
        lines.push('#nullable enable');
        lines.push('using System;');
        lines.push('using System.Runtime.InteropServices;');
        lines.push('using System.Text;');
        lines.push('using HarmonyOS.Bindings.Runtime;');
        lines.push('using HarmonyOS.ArkUI;');  // 枚举生成在 HarmonyOS.ArkUI 命名空间
        if (needsTask) {
            lines.push('using System.Threading.Tasks;');
        }
        lines.push('');
        lines.push('namespace HarmonyOS.Bindings.Api;');
        lines.push('');

        // permissions 注释
        if (permissions.length > 0) {
            lines.push('/// <summary>');
            lines.push(`/// ${moduleInfo.className} 绑定（@ohos.${moduleInfo.local}）。`);
            lines.push(`/// 所需权限：${permissions.join(', ')}`);
            lines.push('/// </summary>');
        } else {
            lines.push('/// <summary>');
            lines.push(`/// ${moduleInfo.className} 绑定（@ohos.${moduleInfo.local}）。`);
            lines.push('/// </summary>');
        }

        lines.push(`public static unsafe partial class ${moduleInfo.className}`);
        lines.push('{');
        lines.push(`    private const string ModuleName = "${moduleInfo.module}";`);
        lines.push('');
        lines.push('    private static NapiReference? _moduleRef;');
        lines.push('    private static bool _loadAttempted;');
        lines.push('');

        // Module lazy-load property (复用 DeviceInfo.cs 模式)
        lines.push('    private static IntPtr Module');
        lines.push('    {');
        lines.push('        get');
        lines.push('        {');
        lines.push('            if (_moduleRef != null) return _moduleRef.Value;');
        lines.push('            if (_loadAttempted)');
        lines.push('                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");');
        lines.push('            _loadAttempted = true;');
        lines.push('');
        lines.push('            var env = NapiEnv.Current;');
        lines.push('            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();');
        lines.push('            try');
        lines.push('            {');
        lines.push('                foreach (var name in new[] { "=" + ModuleName, ModuleName })');
        lines.push('                {');
        lines.push('                    var utf8 = Encoding.UTF8.GetBytes(name);');
        lines.push('                    fixed (byte* p = utf8)');
        lines.push('                    {');
        lines.push('                        var status = NativeNodeApi.napi_load_module(env, p, out var module);');
        lines.push('                        if (status == NativeNodeApi.napi_status.napi_ok && module != IntPtr.Zero)');
        lines.push('                        {');
        lines.push('                            _moduleRef = new NapiReference(module);');
        lines.push('                            break;');
        lines.push('                        }');
        lines.push('                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);');
        lines.push('                    }');
        lines.push('                }');
        lines.push('            }');
        lines.push('            finally');
        lines.push('            {');
        lines.push('                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();');
        lines.push('            }');
        lines.push('');
        lines.push('            if (_moduleRef == null)');
        lines.push('                throw new InvalidOperationException(');
        lines.push('                    $"failed to load {ModuleName} via napi_load_module (tried with and without \'=\' prefix)");');
        lines.push('');
        lines.push(`            HiLog.Info("HarmonyHost", $"[${moduleInfo.local}] module loaded via napi_load_module");`);
        lines.push('            return _moduleRef.Value;');
        lines.push('        }');
        lines.push('    }');
        lines.push('');

        // 生成 UTF8 属性名常量
        const propNames = new Set<string>();
        component.methods.forEach(m => propNames.add(m.name));
        if (propNames.size > 0) {
            for (const name of propNames) {
                lines.push(`    private static ReadOnlySpan<byte> _${name} => "${name}"u8;`);
            }
            lines.push('');
        }

        // 生成属性和方法
        const generatedSignatures = new Set<string>();
        for (const method of component.methods) {
            // 过滤 AsyncCallback 参数后计算签名 key，避免回调重载与 Promise 重载产生重复 C# 签名
            const filteredParams = method.parameters.filter(p => !/^AsyncCallback<(.+)>$/.test(p.type));
            const sigKey = `${method.name}(${filteredParams.map(p => TypeMapper.mapType(TypeMapper.cleanOptional(p.type))).join(',')})`;
            if (generatedSignatures.has(sigKey)) continue;
            generatedSignatures.add(sigKey);

            this.generateMember(method, lines);
        }

        lines.push('}');

        const csharp = lines.join('\n');

        // 生成枚举（如果有）
        let enumCode: string | null = null;
        if (enums.length > 0) {
            enumCode = this.enumGenerator.generateMultipleEnums(enums);
        }

        return {
            csharp,
            enums: enumCode,
            className: moduleInfo.className,
            moduleName: moduleInfo.module,
            permissions
        };
    }

    private generateMember(method: MethodInfo, lines: string[]): void {
        const pascalName = this.capitalizeFirst(method.name);
        const propNameVar = `_${method.name}`;

        // const 属性（无参数，isChained=true，returnType 非 void）
        if (method.isChained && method.parameters.length === 0) {
            const retType = method.returnType || 'object';
            const isVoid = retType === 'void';

            if (isVoid) return; // 跳过 void const

            lines.push('    /// <summary>');
            lines.push(`    /// ${method.name}`);
            lines.push('    /// </summary>');
            lines.push(`    public static ${retType} ${pascalName} => ${this.generateGetterExpr(retType, propNameVar)};`);
            lines.push('');
            return;
        }

        // 检测 AsyncCallback<T> 参数：移除回调参数，方法变为 Task 返回
        const asyncCbMatch = method.parameters.find(p => /^AsyncCallback<(.+)>$/.test(p.type));
        const hasAsyncCallback = asyncCbMatch !== undefined;
        const filteredParams = hasAsyncCallback
            ? method.parameters.filter(p => !/^AsyncCallback<(.+)>$/.test(p.type))
            : method.parameters;

        // 格式化参数（过滤掉回调参数后）
        const params = filteredParams.map(p => this.formatParameter(p));
        const paramStr = params.join(', ');
        const paramNames = filteredParams.map(p => p.name).join(', ');

        lines.push('    /// <summary>');
        lines.push(`    /// ${method.name} 方法`);
        lines.push('    /// </summary>');

        const callArgs = paramNames ? `Module, ${propNameVar}, ${paramNames}` : `Module, ${propNameVar}`;

        if (hasAsyncCallback) {
            // AsyncCallback<T> 参数 → 返回 Task<T>（或 Task 如果 T=void）
            const innerType = asyncCbMatch ? /^AsyncCallback<(.+)>$/.exec(asyncCbMatch.type)?.[1] : null;
            const mappedInner = innerType ? TypeMapper.mapType(innerType) : 'void';
            if (mappedInner === 'void') {
                lines.push(`    public static Task ${pascalName}(${paramStr})`);
                lines.push('    {');
                lines.push(`        return NodeApi.CallMethodAsyncVoid(${callArgs});`);
                lines.push('    }');
            } else {
                lines.push(`    public static Task<${mappedInner}> ${pascalName}(${paramStr})`);
                lines.push('    {');
                lines.push(`        return NodeApi.CallMethodAsync<${mappedInner}>(${callArgs});`);
                lines.push('    }');
            }
        } else {
            const retType = method.returnType || 'void';
            const isVoid = retType === 'void';

            if (isVoid) {
                lines.push(`    public static void ${pascalName}(${paramStr})`);
                lines.push('    {');
                lines.push(`        NodeApi.CallMethodVoid(${callArgs});`);
                lines.push('    }');
            } else {
                const taskMatch = /^Task<(.+)>$/.exec(retType);
                if (taskMatch) {
                    // Task<T> 的 T 如果是未映射类型退回 IntPtr
                    const innerType = this.isUnmappedType(taskMatch[1]) ? 'IntPtr' : taskMatch[1];
                    lines.push(`    public static Task<${innerType}> ${pascalName}(${paramStr})`);
                    lines.push('    {');
                    lines.push(`        return NodeApi.CallMethodAsync<${innerType}>(${callArgs});`);
                    lines.push('    }');
                } else if (retType === 'Task') {
                    lines.push(`    public static Task ${pascalName}(${paramStr})`);
                    lines.push('    {');
                    lines.push(`        return NodeApi.CallMethodAsyncVoid(${callArgs});`);
                    lines.push('    }');
                } else {
                    // 未映射的返回类型退回 IntPtr
                    const safeRetType = this.isUnmappedType(retType) ? 'IntPtr' : retType;
                    lines.push(`    public static ${safeRetType} ${pascalName}(${paramStr})`);
                    lines.push('    {');
                    lines.push(`        return NodeApi.CallMethod<${safeRetType}>(${callArgs});`);
                    lines.push('    }');
                }
            }
        }
        lines.push('');
    }

    private generateGetterExpr(csharpType: string, propNameVar: string): string {
        switch (csharpType) {
            case 'bool':
                return `NativeValue.ToBool(NodeApi.GetProperty(Module, ${propNameVar}))`;
            case 'double':
                return `NativeValue.ToDouble(NodeApi.GetProperty(Module, ${propNameVar}))`;
            case 'string':
                return `NativeValue.ToString(NodeApi.GetProperty(Module, ${propNameVar})) ?? string.Empty`;
            case 'long':
                return `NativeValue.ToLong(NodeApi.GetProperty(Module, ${propNameVar}))`;
            case 'byte':
                return `NativeValue.ToByte(NodeApi.GetProperty(Module, ${propNameVar}))`;
            case 'int':
                return `(int)NativeValue.ToDouble(NodeApi.GetProperty(Module, ${propNameVar}))`;
            case 'uint':
                return `(uint)NativeValue.ToDouble(NodeApi.GetProperty(Module, ${propNameVar}))`;
            case 'IntPtr':
                return `NodeApi.GetProperty(Module, ${propNameVar})`;
            default:
                // 枚举或其他自定义类型：假设底层是 int 枚举
                return `(${csharpType})NativeValue.ToInt(NodeApi.GetProperty(Module, ${propNameVar}))`;
        }
    }

    private formatParameter(param: ParameterInfo): string {
        const cleanType = TypeMapper.cleanOptional(param.type);
        let type = TypeMapper.mapType(cleanType);
        // 未映射的 TS 原始类型（如接口名、Callback<>, Promise<>）退回 IntPtr
        if (/^[a-z]/.test(type) || type.includes('<') && !type.startsWith('Task<') && !type.startsWith('Action<') && !type.startsWith('Func<') && !type.endsWith('[]')) {
            type = 'IntPtr';
        }
        const optionalMark = TypeMapper.isOptional(param.type) ? '?' : '';
        const defaultVal = param.defaultValue ? ` = ${param.defaultValue}` :
                          (TypeMapper.isOptional(param.type) ? ' = null' : '');
        return `${type}${optionalMark} ${param.name}${defaultVal}`;
    }

    private capitalizeFirst(s: string): string {
        return s.charAt(0).toUpperCase() + s.slice(1);
    }

    /** 检测类型是否是未映射的 TS 类型（需要退回 IntPtr） */
    private isUnmappedType(type: string): boolean {
        // 已知的 C# 基础类型和生成类型
        const known = new Set([
            'bool', 'double', 'string', 'long', 'byte', 'int', 'uint', 'IntPtr',
            'void', 'object', 'Task', 'float', 'char',
            // 枚举类型（在 Enums.cs 中生成，但在 HarmonyOS.ArkUI 命名空间下）
            'DeviceTypes', 'PerformanceClassLevel',
        ]);
        if (known.has(type)) return false;
        // Task<T> / Action<T> / Func<T,R> / T[] 递归检查内部类型
        if (type.startsWith('Task<') || type.startsWith('Action<') || type.startsWith('Func<') || type.endsWith('[]')) return false;
        // 所有其他类型（小写开头的原始 TS 类型、大写开头的未生成接口名）都退回 IntPtr
        return true;
    }
}
