// <auto-generated>
// 由 enumGenerator.ts（@ohos.* namespace 绑定路线） 生成。
// 生成器版本：1.0.0；HarmonyOS SDK：26.0.0
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
using System.ComponentModel;

namespace HarmonyOS.ArkUI;

/// <summary>
/// FilePickerPhotoViewMIMETypes 枚举
/// </summary>
public enum FilePickerPhotoViewMIMETypes
{
    [Description("image/*")]
    ImageType,
    [Description("video/*")]
    VideoType,
    [Description("*/*")]
    ImageVideoType
}

/// <summary>
/// DocumentSelectMode 枚举
/// </summary>
public enum DocumentSelectMode
{
    File = 0,
    Folder = 1,
    Mixed = 2
}

/// <summary>
/// DocumentPickerMode 枚举
/// </summary>
public enum DocumentPickerMode
{
    Default = 0,
    Download = 1
}

/// <summary>
/// MergeTypeMode 枚举
/// </summary>
public enum MergeTypeMode
{
    Default = 0,
    Audio = 1,
    Video = 2,
    Document = 3,
    Picture = 4
}