// <auto-generated>
// 由 enumGenerator.ts（@ohos.* namespace 绑定路线） 生成。
// 生成器版本：1.0.0；HarmonyOS SDK：26.0.0
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>

namespace HarmonyOS.ArkUI;

/// <summary>
/// KeyboardType 枚举
/// </summary>
public enum KeyboardType
{
    None = 0,
    Unknown = 1,
    AlphabeticKeyboard = 2,
    DigitalKeyboard = 3,
    HandwritingPen = 4,
    RemoteControl = 5
}

/// <summary>
/// FunctionKey 枚举
/// </summary>
public enum FunctionKey
{
    CapsLock = 1
}