// <auto-generated>
// 由 enumGenerator.ts（@ohos.* namespace 绑定路线） 生成。
// 生成器版本：1.0.0；HarmonyOS SDK：26.0.0
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>

namespace HarmonyOS.ArkUI;

/// <summary>
/// AppPreloadType 枚举
/// </summary>
public enum AppPreloadType
{
    Unspecified = 0,
    TypeCreateProcess = 1,
    TypeCreateAbilityStage = 2,
    TypeCreateWindowStage = 3,
    TypeCreateBackgroundAbility = 4
}