// <auto-generated>
// 由 enumGenerator.ts（@ohos.* namespace 绑定路线） 生成。
// 生成器版本：1.0.0；HarmonyOS SDK：26.0.0
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>

namespace HarmonyOS.ArkUI;

/// <summary>
/// InstanceType 枚举
/// </summary>
public enum InstanceType
{
    Taskpool = 2,
    Worker = 1,
    Main = 0,
    Custom = 3
}

/// <summary>
/// ResourceType 枚举
/// </summary>
public enum ResourceType
{
    PssMemory = 1,
    IonMemory = 2,
    AshmemMemory = 3,
    GpuMemory = 4,
    Fd = 5,
    Thread = 6
}