// <auto-generated>
// 由 apiGenerator.ts 生成（@ohos.* namespace 绑定路线）。
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyOS.Bindings.Runtime;
using HarmonyOS.ArkUI;

namespace HarmonyOS.Bindings.Api.Net;

/// <summary>
/// Eap 绑定（@ohos.net.eap）。
/// 所需权限：ohos.permission.MANAGE_ENTERPRISE_WIFI_CONNECTION
/// </summary>
public static unsafe partial class Eap
{
    private const string ModuleName = "@ohos.net.eap";

    private static NapiReference? _moduleRef;
    private static bool _loadAttempted;

    /// <summary>懒加载的 @ohos 模块对象（internal：同文件包装类的构造函数需要）</summary>
    internal static IntPtr Module
    {
        get
        {
            if (_moduleRef != null) return _moduleRef.Value;
            if (_loadAttempted)
                throw new InvalidOperationException($"{ModuleName} module failed to load (previous attempt)");
            _loadAttempted = true;

            var env = NapiEnv.Current;
            NativeNodeApi.napi_open_handle_scope(env, out var scope).ThrowIfFailed();
            try
            {
                foreach (var name in new[] { "=" + ModuleName, ModuleName })
                {
                    var utf8 = System.Text.Encoding.UTF8.GetBytes(name);
                    fixed (byte* p = utf8)
                    {
                        var status = NativeNodeApi.napi_load_module(env, p, out var module);
                        if (status == napi_status.napi_ok && module != IntPtr.Zero)
                        {
                            _moduleRef = new NapiReference(module);
                            break;
                        }
                        NativeNodeApi.napi_get_and_clear_last_exception(env, out _);
                    }
                }
            }
            finally
            {
                NativeNodeApi.napi_close_handle_scope(env, scope).ThrowIfFailed();
            }

            if (_moduleRef == null)
                throw new InvalidOperationException(
                    $"failed to load {ModuleName} via napi_load_module (tried with and without '=' prefix)");

            HiLog.Info("HarmonyHost", $"[net.eap] module loaded via napi_load_module");
            return _moduleRef.Value;
        }
    }

    private static ReadOnlySpan<byte> _regCustomEapHandler => "regCustomEapHandler"u8;
    private static ReadOnlySpan<byte> _unregCustomEapHandler => "unregCustomEapHandler"u8;
    private static ReadOnlySpan<byte> _replyCustomEapData => "replyCustomEapData"u8;
    private static ReadOnlySpan<byte> _startEthEap => "startEthEap"u8;
    private static ReadOnlySpan<byte> _logOffEthEap => "logOffEthEap"u8;

    /// <summary>
    /// regCustomEapHandler
    /// </summary>
    public static void RegCustomEapHandler(double netType, double eapCode, double eapType, IntPtr callback)
    {
        NodeApi.CallMethodVoid(Module, _regCustomEapHandler, netType, eapCode, eapType, callback);
    }

    /// <summary>
    /// unregCustomEapHandler
    /// </summary>
    public static void UnregCustomEapHandler(double netType, double eapCode, double eapType, IntPtr callback)
    {
        NodeApi.CallMethodVoid(Module, _unregCustomEapHandler, netType, eapCode, eapType, callback);
    }

    /// <summary>
    /// replyCustomEapData
    /// </summary>
    public static void ReplyCustomEapData(global::HarmonyOS.ArkUI.CustomResult result, EapData data)
    {
        NodeApi.CallMethodVoid(Module, _replyCustomEapData, result, NapiArg.Of(data));
    }

    /// <summary>
    /// startEthEap
    /// </summary>
    public static void StartEthEap(double netId, EthEapProfile profile)
    {
        NodeApi.CallMethodVoid(Module, _startEthEap, netId, NapiArg.Of(profile));
    }

    /// <summary>
    /// logOffEthEap
    /// </summary>
    public static void LogOffEthEap(double netId)
    {
        NodeApi.CallMethodVoid(Module, _logOffEthEap, netId);
    }

}

/// <summary>
/// EapData（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record EapData(
    double MsgId,
    byte[] EapBuffer,
    double BufferLen
) : INapiRecord
{
    private static ReadOnlySpan<byte> _msgIdName => "msgId"u8;
    private static ReadOnlySpan<byte> _eapBufferName => "eapBuffer"u8;
    private static ReadOnlySpan<byte> _bufferLenName => "bufferLen"u8;
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _msgIdV = NativeValue.From(MsgId);
        if (_msgIdV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _msgIdName, _msgIdV);
        var _eapBufferV = NativeValue.From(EapBuffer);
        if (_eapBufferV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _eapBufferName, _eapBufferV);
        var _bufferLenV = NativeValue.From(BufferLen);
        if (_bufferLenV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _bufferLenName, _bufferLenV);
    }
}

/// <summary>
/// EthEapProfile（@ohos 命名空间内嵌套纯数据接口，入参对象）。
/// </summary>
public sealed record EthEapProfile(
    global::HarmonyOS.ArkUI.NetEapEapMethod EapMethod,
    global::HarmonyOS.ArkUI.NetEapPhase2Method Phase2Method,
    string Identity,
    string AnonymousIdentity,
    string Password,
    string CaCertAliases,
    string CaPath,
    string ClientCertAliases,
    byte[] CertEntry,
    string CertPassword,
    string AltSubjectMatch,
    string DomainSuffixMatch,
    string Realm,
    string Plmn,
    double EapSubId
) : INapiRecord
{
    private static ReadOnlySpan<byte> _eapMethodName => "eapMethod"u8;
    private static ReadOnlySpan<byte> _phase2MethodName => "phase2Method"u8;
    private static ReadOnlySpan<byte> _identityName => "identity"u8;
    private static ReadOnlySpan<byte> _anonymousIdentityName => "anonymousIdentity"u8;
    private static ReadOnlySpan<byte> _passwordName => "password"u8;
    private static ReadOnlySpan<byte> _caCertAliasesName => "caCertAliases"u8;
    private static ReadOnlySpan<byte> _caPathName => "caPath"u8;
    private static ReadOnlySpan<byte> _clientCertAliasesName => "clientCertAliases"u8;
    private static ReadOnlySpan<byte> _certEntryName => "certEntry"u8;
    private static ReadOnlySpan<byte> _certPasswordName => "certPassword"u8;
    private static ReadOnlySpan<byte> _altSubjectMatchName => "altSubjectMatch"u8;
    private static ReadOnlySpan<byte> _domainSuffixMatchName => "domainSuffixMatch"u8;
    private static ReadOnlySpan<byte> _realmName => "realm"u8;
    private static ReadOnlySpan<byte> _plmnName => "plmn"u8;
    private static ReadOnlySpan<byte> _eapSubIdName => "eapSubId"u8;
    void INapiRecord.WriteTo(NativeNodeApi.napi_env env, NativeNodeApi.napi_value obj)
    {
        var _eapMethodV = NativeValue.From(EapMethod);
        if (_eapMethodV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _eapMethodName, _eapMethodV);
        var _phase2MethodV = NativeValue.From(Phase2Method);
        if (_phase2MethodV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _phase2MethodName, _phase2MethodV);
        var _identityV = NativeValue.From(Identity);
        if (_identityV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _identityName, _identityV);
        var _anonymousIdentityV = NativeValue.From(AnonymousIdentity);
        if (_anonymousIdentityV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _anonymousIdentityName, _anonymousIdentityV);
        var _passwordV = NativeValue.From(Password);
        if (_passwordV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _passwordName, _passwordV);
        var _caCertAliasesV = NativeValue.From(CaCertAliases);
        if (_caCertAliasesV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _caCertAliasesName, _caCertAliasesV);
        var _caPathV = NativeValue.From(CaPath);
        if (_caPathV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _caPathName, _caPathV);
        var _clientCertAliasesV = NativeValue.From(ClientCertAliases);
        if (_clientCertAliasesV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _clientCertAliasesName, _clientCertAliasesV);
        var _certEntryV = NativeValue.From(CertEntry);
        if (_certEntryV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _certEntryName, _certEntryV);
        var _certPasswordV = NativeValue.From(CertPassword);
        if (_certPasswordV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _certPasswordName, _certPasswordV);
        var _altSubjectMatchV = NativeValue.From(AltSubjectMatch);
        if (_altSubjectMatchV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _altSubjectMatchName, _altSubjectMatchV);
        var _domainSuffixMatchV = NativeValue.From(DomainSuffixMatch);
        if (_domainSuffixMatchV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _domainSuffixMatchName, _domainSuffixMatchV);
        var _realmV = NativeValue.From(Realm);
        if (_realmV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _realmName, _realmV);
        var _plmnV = NativeValue.From(Plmn);
        if (_plmnV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _plmnName, _plmnV);
        var _eapSubIdV = NativeValue.From(EapSubId);
        if (_eapSubIdV != IntPtr.Zero)
            NativeNodeApi.napi_set_named_property(env, obj, _eapSubIdName, _eapSubIdV);
    }
}
