// <auto-generated>
// 由 enumGenerator.ts（@ohos.* namespace 绑定路线） 生成。
// 生成器版本：1.0.0；HarmonyOS SDK：26.0.0
// 生成器输入：HarmonyOS SDK .d.ts → astParser → ComponentInfo → 本生成器
// </auto-generated>

namespace HarmonyOS.ArkUI;

/// <summary>
/// HDRFormat 枚举
/// </summary>
public enum HDRFormat
{
    None = 0,
    VideoHlg = 1,
    VideoHdr10 = 2,
    VideoHdrVivid = 3,
    ImageHdrVividDual = 4,
    ImageHdrVividSingle = 5,
    ImageHdrIsoDual = 6,
    ImageHdrIsoSingle = 7,
    VideoAihdr = 8
}