// <auto-generated>由 tools/arkui-bindgen 从 HarmonyOS NDK 头文件生成（语义规则见 tools/arkui-bindgen/config/semantics.yaml），请勿手工编辑</auto-generated>
// 来源: common_type.h, native_animate.h, native_node.h
// ArkUI_NativeAnimateAPI_1 镜像（native_animate.h，API 12+）：显式动画原语。
// 注意：与其它 ArkUI_Native*API_1 表不同，本表以 animateTo 起首、没有 version 字段
// （native_animate.h 逐项核实），勿按惯例补 version。
#nullable enable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace HarmonyOS.Bindings.NativeNode;

#pragma warning disable CS8500

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct ArkUI_ContextCallback
{
    public void* UserData;
    public delegate* unmanaged<void*, void> Callback;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct ArkUI_AnimateCompleteCallback
{
    public ArkUI_FinishCallbackType Type;
    public delegate* unmanaged<void*, void> Callback;
    public void* UserData;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct ArkUI_NativeAnimateAPI_1
{
    public delegate* unmanaged<IntPtr, IntPtr, ArkUI_ContextCallback*, ArkUI_AnimateCompleteCallback*, int> animateTo;
    public delegate* unmanaged<IntPtr, IntPtr, int> keyframeAnimateTo;
    public delegate* unmanaged<IntPtr, IntPtr, IntPtr> createAnimator;
    public delegate* unmanaged<IntPtr, void> disposeAnimator;
}

internal static unsafe partial class ArkUINativeApi
{
    /// <summary>由任意节点取 UIContext（animateTo 的 context 参数）</summary>
    [LibraryImport(ArkuiLib)]
    internal static partial IntPtr OH_ArkUI_GetContextByNode(ArkUI_NodeHandle node);

    [LibraryImport(ArkuiLib)]
    internal static partial IntPtr OH_ArkUI_AnimateOption_Create();

    [LibraryImport(ArkuiLib)]
    internal static partial void OH_ArkUI_AnimateOption_Dispose(IntPtr option);

    [LibraryImport(ArkuiLib)]
    internal static partial void OH_ArkUI_AnimateOption_SetDuration(IntPtr option, int value);

    [LibraryImport(ArkuiLib)]
    internal static partial void OH_ArkUI_AnimateOption_SetCurve(IntPtr option, ArkUI_AnimationCurve value);
}

#pragma warning restore CS8500
