// <auto-generated>由 tools/arkui-bindgen 从 HarmonyOS NDK 头文件生成（语义规则见 tools/arkui-bindgen/config/semantics.yaml），请勿手工编辑</auto-generated>
// 来源: native_node.h, native_type.h
// ArkUINativeApi 自绘节点扩展镜像：ArkUI_NodeCustomEvent 访问器、
// ArkUI_LayoutConstraint 访问器与 ArkUI_DrawContext 访问器（native_node.h / native_type.h）。
#nullable enable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace HarmonyOS.Bindings.NativeNode;

#pragma warning disable CS8500

internal static unsafe partial class ArkUINativeApi
{
    [LibraryImport(ArkuiLib)]
    private static partial int OH_ArkUI_NodeCustomEvent_GetEventType(ArkUI_NodeCustomEvent* @event);

    [LibraryImport(ArkuiLib)]
    private static partial int OH_ArkUI_NodeCustomEvent_GetEventTargetId(ArkUI_NodeCustomEvent* @event);

    [LibraryImport(ArkuiLib)]
    private static partial IntPtr OH_ArkUI_NodeCustomEvent_GetUserData(ArkUI_NodeCustomEvent* @event);

    [LibraryImport(ArkuiLib)]
    private static partial IntPtr OH_ArkUI_NodeCustomEvent_GetDrawContextInDraw(ArkUI_NodeCustomEvent* @event);

    [LibraryImport(ArkuiLib)]
    private static partial ArkUI_LayoutConstraint* OH_ArkUI_NodeCustomEvent_GetLayoutConstraintInMeasure(ArkUI_NodeCustomEvent* @event);

    [LibraryImport(ArkuiLib)]
    private static partial int OH_ArkUI_LayoutConstraint_GetMaxWidth(ArkUI_LayoutConstraint* constraint);

    [LibraryImport(ArkuiLib)]
    private static partial int OH_ArkUI_LayoutConstraint_GetMaxHeight(ArkUI_LayoutConstraint* constraint);

    [LibraryImport(ArkuiLib)]
    private static partial IntPtr OH_ArkUI_DrawContext_GetCanvas(IntPtr context);

    [LibraryImport(ArkuiLib)]
    private static partial ArkUI_IntSize OH_ArkUI_DrawContext_GetSize(IntPtr context);
}

#pragma warning restore CS8500
