// <auto-generated>由 tools/arkui-bindgen 从 HarmonyOS NDK 头文件生成（语义规则见 tools/arkui-bindgen/config/semantics.yaml），请勿手工编辑</auto-generated>
// 来源: native_node.h
// ArkUINativeApi NodeAdapter 扩展镜像：List/Swiper/WaterFlow 虚拟化 adapter（native_node.h API 12+）。
#nullable enable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace HarmonyOS.Bindings.NativeNode;

#pragma warning disable CS8500

/// <summary>ArkUI_NodeAdapterEvent（不透明，经访问器读取）</summary>
public struct ArkUI_NodeAdapterEvent { }

internal static unsafe partial class ArkUINativeApi
{
    [LibraryImport(ArkuiLib)]
    private static partial IntPtr OH_ArkUI_NodeAdapter_Create();

    [LibraryImport(ArkuiLib)]
    private static partial void OH_ArkUI_NodeAdapter_Dispose(IntPtr handle);

    [LibraryImport(ArkuiLib)]
    private static partial int OH_ArkUI_NodeAdapter_SetTotalNodeCount(IntPtr handle, uint size);

    [LibraryImport(ArkuiLib)]
    private static partial int OH_ArkUI_NodeAdapter_RegisterEventReceiver(IntPtr handle, IntPtr userData, delegate* unmanaged<ArkUI_NodeAdapterEvent*, void> receiver);

    [LibraryImport(ArkuiLib)]
    private static partial void OH_ArkUI_NodeAdapter_UnregisterEventReceiver(IntPtr handle);

    [LibraryImport(ArkuiLib)]
    private static partial int OH_ArkUI_NodeAdapter_ReloadAllItems(IntPtr handle);

    [LibraryImport(ArkuiLib)]
    private static partial int OH_ArkUI_NodeAdapter_ReloadItem(IntPtr handle, uint startPosition, uint itemCount);

    [LibraryImport(ArkuiLib)]
    private static partial int OH_ArkUI_NodeAdapter_RemoveItem(IntPtr handle, uint startPosition, uint itemCount);

    [LibraryImport(ArkuiLib)]
    private static partial int OH_ArkUI_NodeAdapter_InsertItem(IntPtr handle, uint startPosition, uint itemCount);

    [LibraryImport(ArkuiLib)]
    private static partial int OH_ArkUI_NodeAdapterEvent_SetItem(ArkUI_NodeAdapterEvent* @event, IntPtr node);

    [LibraryImport(ArkuiLib)]
    private static partial int OH_ArkUI_NodeAdapterEvent_SetNodeId(ArkUI_NodeAdapterEvent* @event, int id);

    [LibraryImport(ArkuiLib)]
    private static partial int OH_ArkUI_NodeAdapterEvent_GetType(ArkUI_NodeAdapterEvent* @event);

    [LibraryImport(ArkuiLib)]
    private static partial IntPtr OH_ArkUI_NodeAdapterEvent_GetRemovedNode(ArkUI_NodeAdapterEvent* @event);

    [LibraryImport(ArkuiLib)]
    private static partial uint OH_ArkUI_NodeAdapterEvent_GetItemIndex(ArkUI_NodeAdapterEvent* @event);

    [LibraryImport(ArkuiLib)]
    private static partial IntPtr OH_ArkUI_NodeAdapterEvent_GetUserData(ArkUI_NodeAdapterEvent* @event);
}

#pragma warning restore CS8500
